// Code generated by h2go; DO NOT EDIT.

package py310

// PyAsyncMethods mirrors the C struct PyAsyncMethods (size 32; object.h:173).
type PyAsyncMethods struct {
	AmAwait uintptr // +0 unaryfunc am_await
	AmAiter uintptr // +8 unaryfunc am_aiter
	AmAnext uintptr // +16 unaryfunc am_anext
	AmSend  uintptr // +24 sendfunc am_send
}

// PyBufferProcs mirrors the C struct PyBufferProcs (size 16; object.h:180).
type PyBufferProcs struct {
	BfGetbuffer     uintptr // +0 getbufferproc bf_getbuffer
	BfReleasebuffer uintptr // +8 releasebufferproc bf_releasebuffer
}

// PyGetSetDef mirrors the C struct PyGetSetDef (size 40; object.h:249).
type PyGetSetDef struct {
	Name    uintptr // +0 const char * name
	Get     uintptr // +8 getter get
	Set     uintptr // +16 setter set
	Doc     uintptr // +24 const char * doc
	Closure uintptr // +32 void * closure
}

// PyHeapTypeObject mirrors the C struct _heaptypeobject (size 888; object.h:276).
type PyHeapTypeObject struct {
	HtType       PyTypeObject      // +0 PyTypeObject ht_type
	AsAsync      PyAsyncMethods    // +408 PyAsyncMethods as_async
	AsNumber     PyNumberMethods   // +440 PyNumberMethods as_number
	AsMapping    PyMappingMethods  // +728 PyMappingMethods as_mapping
	AsSequence   PySequenceMethods // +752 PySequenceMethods as_sequence
	AsBuffer     PyBufferProcs     // +832 PyBufferProcs as_buffer
	HtName       uintptr           // +848 PyObject * ht_name
	HtSlots      uintptr           // +856 PyObject * ht_slots
	HtQualname   uintptr           // +864 PyObject * ht_qualname
	HtCachedKeys uintptr           // +872 struct _dictkeysobject * ht_cached_keys
	HtModule     uintptr           // +880 PyObject * ht_module
}

// PyMappingMethods mirrors the C struct PyMappingMethods (size 24; object.h:165).
type PyMappingMethods struct {
	MpLength       uintptr // +0 lenfunc mp_length
	MpSubscript    uintptr // +8 binaryfunc mp_subscript
	MpAssSubscript uintptr // +16 objobjargproc mp_ass_subscript
}

// PyMethodDef mirrors the C struct PyMethodDef (size 32; object.h:247).
type PyMethodDef struct {
	MlName  uintptr // +0 const char * ml_name
	MlMeth  uintptr // +8 PyCFunction ml_meth
	MlFlags int32   // +16 int ml_flags
	MlDoc   uintptr // +24 const char * ml_doc
}

// PyModuleDef mirrors the C struct PyModuleDef (size 104; object.h:306).
type PyModuleDef struct {
	MBase     PyModuleDefBase // +0 PyModuleDef_Base m_base
	MName     uintptr         // +40 const char * m_name
	MDoc      uintptr         // +48 const char * m_doc
	MSize     int64           // +56 Py_ssize_t m_size
	MMethods  uintptr         // +64 PyMethodDef * m_methods
	MSlots    uintptr         // +72 struct PyModuleDef_Slot * m_slots
	MTraverse uintptr         // +80 traverseproc m_traverse
	MClear    uintptr         // +88 inquiry m_clear
	MFree     uintptr         // +96 freefunc m_free
}

// PyNumberMethods mirrors the C struct PyNumberMethods (size 288; object.h:104).
type PyNumberMethods struct {
	NbAdd                   uintptr // +0 binaryfunc nb_add
	NbSubtract              uintptr // +8 binaryfunc nb_subtract
	NbMultiply              uintptr // +16 binaryfunc nb_multiply
	NbRemainder             uintptr // +24 binaryfunc nb_remainder
	NbDivmod                uintptr // +32 binaryfunc nb_divmod
	NbPower                 uintptr // +40 ternaryfunc nb_power
	NbNegative              uintptr // +48 unaryfunc nb_negative
	NbPositive              uintptr // +56 unaryfunc nb_positive
	NbAbsolute              uintptr // +64 unaryfunc nb_absolute
	NbBool                  uintptr // +72 inquiry nb_bool
	NbInvert                uintptr // +80 unaryfunc nb_invert
	NbLshift                uintptr // +88 binaryfunc nb_lshift
	NbRshift                uintptr // +96 binaryfunc nb_rshift
	NbAnd                   uintptr // +104 binaryfunc nb_and
	NbXor                   uintptr // +112 binaryfunc nb_xor
	NbOr                    uintptr // +120 binaryfunc nb_or
	NbInt                   uintptr // +128 unaryfunc nb_int
	NbReserved              uintptr // +136 void * nb_reserved
	NbFloat                 uintptr // +144 unaryfunc nb_float
	NbInplaceAdd            uintptr // +152 binaryfunc nb_inplace_add
	NbInplaceSubtract       uintptr // +160 binaryfunc nb_inplace_subtract
	NbInplaceMultiply       uintptr // +168 binaryfunc nb_inplace_multiply
	NbInplaceRemainder      uintptr // +176 binaryfunc nb_inplace_remainder
	NbInplacePower          uintptr // +184 ternaryfunc nb_inplace_power
	NbInplaceLshift         uintptr // +192 binaryfunc nb_inplace_lshift
	NbInplaceRshift         uintptr // +200 binaryfunc nb_inplace_rshift
	NbInplaceAnd            uintptr // +208 binaryfunc nb_inplace_and
	NbInplaceXor            uintptr // +216 binaryfunc nb_inplace_xor
	NbInplaceOr             uintptr // +224 binaryfunc nb_inplace_or
	NbFloorDivide           uintptr // +232 binaryfunc nb_floor_divide
	NbTrueDivide            uintptr // +240 binaryfunc nb_true_divide
	NbInplaceFloorDivide    uintptr // +248 binaryfunc nb_inplace_floor_divide
	NbInplaceTrueDivide     uintptr // +256 binaryfunc nb_inplace_true_divide
	NbIndex                 uintptr // +264 unaryfunc nb_index
	NbMatrixMultiply        uintptr // +272 binaryfunc nb_matrix_multiply
	NbInplaceMatrixMultiply uintptr // +280 binaryfunc nb_inplace_matrix_multiply
}

// PySequenceMethods mirrors the C struct PySequenceMethods (size 80; object.h:151).
type PySequenceMethods struct {
	SqLength        uintptr // +0 lenfunc sq_length
	SqConcat        uintptr // +8 binaryfunc sq_concat
	SqRepeat        uintptr // +16 ssizeargfunc sq_repeat
	SqItem          uintptr // +24 ssizeargfunc sq_item
	WasSqSlice      uintptr // +32 void * was_sq_slice
	SqAssItem       uintptr // +40 ssizeobjargproc sq_ass_item
	WasSqAssSlice   uintptr // +48 void * was_sq_ass_slice
	SqContains      uintptr // +56 objobjproc sq_contains
	SqInplaceConcat uintptr // +64 binaryfunc sq_inplace_concat
	SqInplaceRepeat uintptr // +72 ssizeargfunc sq_inplace_repeat
}

// PyThreadState mirrors the C struct _ts (size 280; object.h:517).
type PyThreadState struct {
	Prev                         uintptr        // +0 struct _ts * prev
	Next                         uintptr        // +8 struct _ts * next
	Interp                       uintptr        // +16 PyInterpreterState * interp
	Frame                        uintptr        // +24 PyFrameObject * frame
	RecursionDepth               int32          // +32 int recursion_depth
	RecursionHeadroom            int32          // +36 int recursion_headroom
	StackcheckCounter            int32          // +40 int stackcheck_counter
	Tracing                      int32          // +44 int tracing
	Cframe                       uintptr        // +48 CFrame * cframe
	CProfilefunc                 uintptr        // +56 Py_tracefunc c_profilefunc
	CTracefunc                   uintptr        // +64 Py_tracefunc c_tracefunc
	CProfileobj                  uintptr        // +72 PyObject * c_profileobj
	CTraceobj                    uintptr        // +80 PyObject * c_traceobj
	CurexcType                   uintptr        // +88 PyObject * curexc_type
	CurexcValue                  uintptr        // +96 PyObject * curexc_value
	CurexcTraceback              uintptr        // +104 PyObject * curexc_traceback
	ExcState                     PyErrStackItem // +112 _PyErr_StackItem exc_state
	ExcInfo                      uintptr        // +144 _PyErr_StackItem * exc_info
	Dict                         uintptr        // +152 PyObject * dict
	GilstateCounter              int32          // +160 int gilstate_counter
	AsyncExc                     uintptr        // +168 PyObject * async_exc
	ThreadId                     uint64         // +176 unsigned long thread_id
	TrashDeleteNesting           int32          // +184 int trash_delete_nesting
	TrashDeleteLater             uintptr        // +192 PyObject * trash_delete_later
	OnDelete                     uintptr        // +200 void (*)(void *) on_delete
	OnDeleteData                 uintptr        // +208 void * on_delete_data
	CoroutineOriginTrackingDepth int32          // +216 int coroutine_origin_tracking_depth
	AsyncGenFirstiter            uintptr        // +224 PyObject * async_gen_firstiter
	AsyncGenFinalizer            uintptr        // +232 PyObject * async_gen_finalizer
	Context                      uintptr        // +240 PyObject * context
	ContextVer                   uint64         // +248 uint64_t context_ver
	Id                           uint64         // +256 uint64_t id
	RootCframe                   CFrame         // +264 CFrame root_cframe
}

// PyBuffer mirrors the C struct bufferinfo (size 80; object.h:49).
type PyBuffer struct {
	Buf        uintptr // +0 void * buf
	Obj        uintptr // +8 PyObject * obj
	Len        int64   // +16 Py_ssize_t len
	Itemsize   int64   // +24 Py_ssize_t itemsize
	Readonly   int32   // +32 int readonly
	Ndim       int32   // +36 int ndim
	Format     uintptr // +40 char * format
	Shape      uintptr // +48 Py_ssize_t * shape
	Strides    uintptr // +56 Py_ssize_t * strides
	Suboffsets uintptr // +64 Py_ssize_t * suboffsets
	Internal   uintptr // +72 void * internal
}

// PyIdentifier mirrors the C struct _Py_Identifier (size 16; object.h:37).
type PyIdentifier struct {
	String uintptr // +0 const char * string
	Index  int64   // +8 Py_ssize_t index
}
