// Code generated by h2go; DO NOT EDIT.

package py310

// CFrame mirrors the C struct _cframe (size 16; pystate.h:30).
type CFrame struct {
	UseTracing int32   // +0 int use_tracing
	Previous   uintptr // +8 struct _cframe * previous
}

// PyCrossInterpreterData mirrors the C struct _xid (size 40; pystate.h:250).
type PyCrossInterpreterData struct {
	Data      uintptr // +0 void * data
	Obj       uintptr // +8 PyObject * obj
	Interp    int64   // +16 int64_t interp
	NewObject uintptr // +24 PyObject *(*)(struct _xid *) new_object
	Free      uintptr // +32 void (*)(void *) free
}

// PyErrStackItem mirrors the C struct _err_stackitem (size 32; pystate.h:45).
type PyErrStackItem struct {
	ExcType      uintptr // +0 PyObject * exc_type
	ExcValue     uintptr // +8 PyObject * exc_value
	ExcTraceback uintptr // +16 PyObject * exc_traceback
	PreviousItem uintptr // +24 struct _err_stackitem * previous_item
}
