// Code generated by h2go; DO NOT EDIT.

package py310

// PyGenObjectHEAD mirrors the struct-shaped C macro _PyGenObject_HEAD.
type PyGenObjectHEAD struct {
	PyObjectHEAD                 // +0
	GiFrame       uintptr        // +16 PyFrameObject * gi_frame
	GiCode        uintptr        // +24 PyObject * gi_code
	GiWeakreflist uintptr        // +32 PyObject * gi_weakreflist
	GiName        uintptr        // +40 PyObject * gi_name
	GiQualname    uintptr        // +48 PyObject * gi_qualname
	GiExcState    PyErrStackItem // +56 _PyErr_StackItem gi_exc_state
}

// PyAsyncGenObject mirrors the C struct PyAsyncGenObject (size 112; genobject.h:64).
type PyAsyncGenObject struct {
	PyObjectHEAD                  // +0
	AgFrame        uintptr        // +16 PyFrameObject * ag_frame
	AgCode         uintptr        // +24 PyObject * ag_code
	AgWeakreflist  uintptr        // +32 PyObject * ag_weakreflist
	AgName         uintptr        // +40 PyObject * ag_name
	AgQualname     uintptr        // +48 PyObject * ag_qualname
	AgExcState     PyErrStackItem // +56 _PyErr_StackItem ag_exc_state
	AgFinalizer    uintptr        // +88 PyObject * ag_finalizer
	AgHooksInited  int32          // +96 int ag_hooks_inited
	AgClosed       int32          // +100 int ag_closed
	AgRunningAsync int32          // +104 int ag_running_async
}

// PyCoroObject mirrors the C struct PyCoroObject (size 96; genobject.h:49).
type PyCoroObject struct {
	PyObjectHEAD                 // +0
	CrFrame       uintptr        // +16 PyFrameObject * cr_frame
	CrCode        uintptr        // +24 PyObject * cr_code
	CrWeakreflist uintptr        // +32 PyObject * cr_weakreflist
	CrName        uintptr        // +40 PyObject * cr_name
	CrQualname    uintptr        // +48 PyObject * cr_qualname
	CrExcState    PyErrStackItem // +56 _PyErr_StackItem cr_exc_state
	CrOrigin      uintptr        // +88 PyObject * cr_origin
}

// PyGenObject mirrors the C struct PyGenObject (size 88; genobject.h:30).
type PyGenObject struct {
	PyGenObjectHEAD // +0
}
