// Code generated by h2go; DO NOT EDIT.

package py310

// PyModuleDefBase mirrors the C struct PyModuleDef_Base (size 40; moduleobject.h:44).
type PyModuleDefBase struct {
	PyObjectHEAD         // +0
	MInit        uintptr // +16 PyObject *(*)(void) m_init
	MIndex       int64   // +24 Py_ssize_t m_index
	MCopy        uintptr // +32 PyObject * m_copy
}

// PyModuleDefSlot mirrors the C struct PyModuleDef_Slot (size 16; moduleobject.h:58).
type PyModuleDefSlot struct {
	Slot  int32   // +0 int slot
	Value uintptr // +8 void * value
}
