// Code generated by h2go; DO NOT EDIT.

package py310

// PyFrameObject mirrors the C struct _frame (size 360; pyframe.h:12).
type PyFrameObject struct {
	PyObjectVARHEAD                // +0
	FBack           uintptr        // +24 struct _frame * f_back
	FCode           uintptr        // +32 PyCodeObject * f_code
	FBuiltins       uintptr        // +40 PyObject * f_builtins
	FGlobals        uintptr        // +48 PyObject * f_globals
	FLocals         uintptr        // +56 PyObject * f_locals
	FValuestack     uintptr        // +64 PyObject ** f_valuestack
	FTrace          uintptr        // +72 PyObject * f_trace
	FStackdepth     int32          // +80 int f_stackdepth
	FTraceLines     int8           // +84 char f_trace_lines
	FTraceOpcodes   int8           // +85 char f_trace_opcodes
	FGen            uintptr        // +88 PyObject * f_gen
	FLasti          int32          // +96 int f_lasti
	FLineno         int32          // +100 int f_lineno
	FIblock         int32          // +104 int f_iblock
	FState          int8           // +108 PyFrameState f_state
	FBlockstack     [20]PyTryBlock // +112 PyTryBlock[20] f_blockstack
	FLocalsplus     [1]uintptr     // +352 PyObject *[1] f_localsplus
}
