// Code generated by h2go; DO NOT EDIT.

package py310

// PyLockStatus is the C enum enum PyLockStatus (size 4; pythread.h:17).
type PyLockStatus uint32

// PyTssT mirrors the C struct _Py_tss_t (size 8; pythread.h:123).
type PyTssT struct {
	IsInitialized int32  // +0 int _is_initialized
	Key           uint32 // +4 pthread_key_t _key
}
