// Code generated by h2go; DO NOT EDIT.

package py310

// PySetObject mirrors the C struct PySetObject (size 200; setobject.h:42).
type PySetObject struct {
	PyObjectHEAD             // +0
	Fill         int64       // +16 Py_ssize_t fill
	Used         int64       // +24 Py_ssize_t used
	Mask         int64       // +32 Py_ssize_t mask
	Table        uintptr     // +40 setentry * table
	Hash         int64       // +48 Py_hash_t hash
	Finger       int64       // +56 Py_ssize_t finger
	Smalltable   [8]Setentry // +64 setentry[8] smalltable
	Weakreflist  uintptr     // +192 PyObject * weakreflist
}

// Setentry mirrors the C struct setentry (size 16; setobject.h:26).
type Setentry struct {
	Key  uintptr // +0 PyObject * key
	Hash int64   // +8 Py_hash_t hash
}
