// Code generated by h2go; DO NOT EDIT.

package py314

// PyLongExport mirrors the C struct PyLongExport (size 40; longintrepr.h:153).
type PyLongExport struct {
	Value    int64   // +0 int64_t value
	Negative uint8   // +8 uint8_t negative
	Ndigits  int64   // +16 Py_ssize_t ndigits
	Digits   uintptr // +24 const void * digits
	Reserved uint64  // +32 Py_uintptr_t _reserved
}

// PyLongLayout mirrors the C struct PyLongLayout (size 4; longintrepr.h:144).
type PyLongLayout struct {
	BitsPerDigit    uint8 // +0 uint8_t bits_per_digit
	DigitSize       uint8 // +1 uint8_t digit_size
	DigitsOrder     int8  // +2 int8_t digits_order
	DigitEndianness int8  // +3 int8_t digit_endianness
}

// PyLongValue mirrors the C struct _PyLongValue (size 16; longintrepr.h:93).
type PyLongValue struct {
	LvTag   uint64    // +0 uintptr_t lv_tag
	ObDigit [1]uint32 // +8 digit[1] ob_digit
}
