// Code generated by h2go; DO NOT EDIT.

package py314

// PyMemoryViewObject mirrors the C struct PyMemoryViewObject (size 152; memoryobject.h:27).
type PyMemoryViewObject struct {
	PyObjectVARHEAD          // +0
	Mbuf            uintptr  // +24 _PyManagedBufferObject * mbuf
	Hash            int64    // +32 Py_hash_t hash
	Flags           int32    // +40 int flags
	Exports         int64    // +48 Py_ssize_t exports
	View            PyBuffer // +56 Py_buffer view
	Weakreflist     uintptr  // +136 PyObject * weakreflist
	ObArray         [1]int64 // +144 Py_ssize_t[1] ob_array
}

// PyManagedBufferObject mirrors the C struct _PyManagedBufferObject (size 112; memoryobject.h:11).
type PyManagedBufferObject struct {
	PyObjectHEAD          // +0
	Flags        int32    // +16 int flags
	Exports      int64    // +24 Py_ssize_t exports
	Master       PyBuffer // +32 Py_buffer master
}
