// Code generated by h2go; DO NOT EDIT.

package py314

// PyCompilerFlags mirrors the C struct PyCompilerFlags (size 8; compile.h:27).
type PyCompilerFlags struct {
	CfFlags          int32 // +0 int cf_flags
	CfFeatureVersion int32 // +4 int cf_feature_version
}
