// Code generated by h2go; DO NOT EDIT.

package py314

// PyErrStackItem mirrors the C struct _err_stackitem (size 16; pystate.h:37).
type PyErrStackItem struct {
	ExcValue     uintptr // +0 PyObject * exc_value
	PreviousItem uintptr // +8 struct _err_stackitem * previous_item
}

// PyRemoteDebuggerSupport mirrors the C struct _PyRemoteDebuggerSupport (size 516; pystate.h:32).
type PyRemoteDebuggerSupport struct {
	DebuggerPendingCall int32     // +0 int32_t debugger_pending_call
	DebuggerScriptPath  [512]int8 // +4 char[512] debugger_script_path
}

// PyStackChunk mirrors the C struct _stack_chunk (size 32; pystate.h:57).
type PyStackChunk struct {
	Previous uintptr    // +0 struct _stack_chunk * previous
	Size     uint64     // +8 size_t size
	Top      uint64     // +16 size_t top
	Data     [1]uintptr // +24 PyObject *[1] data
}
