// Code generated by h2go; DO NOT EDIT.

package py314

// PerfMapState mirrors the C struct PerfMapState (size 16; ceval.h:30).
type PerfMapState struct {
	PerfMap uintptr // +0 FILE * perf_map
	MapLock uintptr // +8 PyThread_type_lock map_lock
}
