// Code generated by h2go; DO NOT EDIT.

package py314

// PyTracebackObject mirrors the C struct _traceback (size 40; traceback.h:5).
type PyTracebackObject struct {
	PyObjectHEAD         // +0
	TbNext       uintptr // +16 PyTracebackObject * tb_next
	TbFrame      uintptr // +24 PyFrameObject * tb_frame
	TbLasti      int32   // +32 int tb_lasti
	TbLineno     int32   // +36 int tb_lineno
}
