// Code generated by h2go; DO NOT EDIT.

package py314

// PyTupleObject mirrors the C struct PyTupleObject (size 40; tupleobject.h:5).
type PyTupleObject struct {
	PyObjectVARHEAD            // +0
	ObHash          int64      // +24 Py_hash_t ob_hash
	ObItem          [1]uintptr // +32 PyObject *[1] ob_item
}
