// Code generated by h2go; DO NOT EDIT.

package py314

// PyDictObject mirrors the C struct PyDictObject (size 48; dictobject.h:11).
type PyDictObject struct {
	PyObjectHEAD         // +0
	MaUsed       int64   // +16 Py_ssize_t ma_used
	MaWatcherTag uint64  // +24 uint64_t _ma_watcher_tag
	MaKeys       uintptr // +32 PyDictKeysObject * ma_keys
	MaValues     uintptr // +40 PyDictValues * ma_values
}

// PyDictWatchEvent is the C enum enum PyDict_WatchEvent (size 4; dictobject.h:92).
type PyDictWatchEvent uint32
