// Code generated by h2go; DO NOT EDIT.

package py314

// PyBuffer mirrors the C struct Py_buffer (size 80; pybuffer.h:20).
type PyBuffer struct {
	Buf        uintptr // +0 void * buf
	Obj        uintptr // +8 PyObject * obj
	Len        int64   // +16 Py_ssize_t len
	Itemsize   int64   // +24 Py_ssize_t itemsize
	Readonly   int32   // +32 int readonly
	Ndim       int32   // +36 int ndim
	Format     uintptr // +40 char * format
	Shape      uintptr // +48 Py_ssize_t * shape
	Strides    uintptr // +56 Py_ssize_t * strides
	Suboffsets uintptr // +64 Py_ssize_t * suboffsets
	Internal   uintptr // +72 void * internal
}
