// Code generated by h2go; DO NOT EDIT.

package py30

// PyBytesObject mirrors the C struct PyBytesObject (size 32; bytesobject.h:30).
type PyBytesObject struct {
	PyObjectVARHEAD         // +0
	ObShash         int32   // +24 long ob_shash
	ObSval          [1]int8 // +28 char[1] ob_sval
}
