// Code generated by h2go; DO NOT EDIT.

package py311

// PyByteArrayObject mirrors the C struct PyByteArrayObject (size 56; bytearrayobject.h:6).
type PyByteArrayObject struct {
	PyObjectVARHEAD         // +0
	ObAlloc         int64   // +24 Py_ssize_t ob_alloc
	ObBytes         uintptr // +32 char * ob_bytes
	ObStart         uintptr // +40 char * ob_start
	ObExports       int64   // +48 Py_ssize_t ob_exports
}
