// Code generated by h2go; DO NOT EDIT.

package py311

// PyTraceInfo mirrors the C struct PyTraceInfo (size 48; pystate.h:31).
type PyTraceInfo struct {
	Code   uintptr            // +0 PyCodeObject * code
	Bounds PyCodeAddressRange // +8 PyCodeAddressRange bounds
}

// PyCFrame mirrors the C struct _PyCFrame (size 24; pystate.h:38).
type PyCFrame struct {
	UseTracing   uint8   // +0 uint8_t use_tracing
	CurrentFrame uintptr // +8 struct _PyInterpreterFrame * current_frame
	Previous     uintptr // +16 struct _PyCFrame * previous
}

// PyCrossInterpreterData mirrors the C struct _xid (size 40; pystate.h:314).
type PyCrossInterpreterData struct {
	Data      uintptr // +0 void * data
	Obj       uintptr // +8 PyObject * obj
	Interp    int64   // +16 int64_t interp
	NewObject uintptr // +24 PyObject *(*)(_PyCrossInterpreterData *) new_object
	Free      uintptr // +32 void (*)(void *) free
}

// PyErrStackItem mirrors the C struct _err_stackitem (size 16; pystate.h:55).
type PyErrStackItem struct {
	ExcValue     uintptr // +0 PyObject * exc_value
	PreviousItem uintptr // +8 struct _err_stackitem * previous_item
}

// PyStackChunk mirrors the C struct _stack_chunk (size 32; pystate.h:75).
type PyStackChunk struct {
	Previous uintptr    // +0 struct _stack_chunk * previous
	Size     uint64     // +8 size_t size
	Top      uint64     // +16 size_t top
	Data     [1]uintptr // +24 PyObject *[1] data
}
