// Code generated by h2go; DO NOT EDIT.

package py311

// PyLockStatus is the C enum enum PyLockStatus (size 4; pythread.h:16).
type PyLockStatus uint32

// PyTssT mirrors the C struct _Py_tss_t (size 8; pythread.h:111).
type PyTssT struct {
	IsInitialized int32  // +0 int _is_initialized
	Key           uint32 // +4 unsigned long _key
}
