// Code generated by h2go; DO NOT EDIT.

package py311

// PyObjectVARHEAD mirrors the struct-shaped C macro PyObject_VAR_HEAD.
type PyObjectVARHEAD struct {
	ObBase PyVarObject // +0 PyVarObject ob_base
}

// PyCodeDEF mirrors the struct-shaped C macro _PyCode_DEF.
type PyCodeDEF struct {
	PyObjectVARHEAD              // +0
	CoConsts             uintptr // +24 PyObject * co_consts
	CoNames              uintptr // +32 PyObject * co_names
	CoExceptiontable     uintptr // +40 PyObject * co_exceptiontable
	CoFlags              int32   // +48 int co_flags
	CoWarmup             int16   // +52 short co_warmup
	CoLinearrayEntrySize int16   // +54 short _co_linearray_entry_size
	CoArgcount           int32   // +56 int co_argcount
	CoPosonlyargcount    int32   // +60 int co_posonlyargcount
	CoKwonlyargcount     int32   // +64 int co_kwonlyargcount
	CoStacksize          int32   // +68 int co_stacksize
	CoFirstlineno        int32   // +72 int co_firstlineno
	CoNlocalsplus        int32   // +76 int co_nlocalsplus
	CoNlocals            int32   // +80 int co_nlocals
	CoNplaincellvars     int32   // +84 int co_nplaincellvars
	CoNcellvars          int32   // +88 int co_ncellvars
	CoNfreevars          int32   // +92 int co_nfreevars
	CoLocalsplusnames    uintptr // +96 PyObject * co_localsplusnames
	CoLocalspluskinds    uintptr // +104 PyObject * co_localspluskinds
	CoFilename           uintptr // +112 PyObject * co_filename
	CoName               uintptr // +120 PyObject * co_name
	CoQualname           uintptr // +128 PyObject * co_qualname
	CoLinetable          uintptr // +136 PyObject * co_linetable
	CoWeakreflist        uintptr // +144 PyObject * co_weakreflist
	CoCode               uintptr // +152 PyObject * _co_code
	CoLinearray          uintptr // +160 char * _co_linearray
	CoFirsttraceable     int32   // +168 int _co_firsttraceable
	CoExtra              uintptr // +176 void * co_extra
	CoCodeAdaptive       [1]int8 // +184 char[1] co_code_adaptive
}

// PyCodeObject mirrors the C struct PyCodeObject (size 192; pytypedefs.h:21).
type PyCodeObject struct {
	PyCodeDEF // +0
}

// PyGetSetDef mirrors the C struct PyGetSetDef (size 40; pytypedefs.h:15).
type PyGetSetDef struct {
	Name    uintptr // +0 const char * name
	Get     uintptr // +8 getter get
	Set     uintptr // +16 setter set
	Doc     uintptr // +24 const char * doc
	Closure uintptr // +32 void * closure
}

// PyLongObject mirrors the C struct _longobject (size 32; pytypedefs.h:19).
type PyLongObject struct {
	PyObjectVARHEAD           // +0
	ObDigit         [1]uint32 // +24 digit[1] ob_digit
}

// PyMethodDef mirrors the C struct PyMethodDef (size 32; pytypedefs.h:14).
type PyMethodDef struct {
	MlName  uintptr // +0 const char * ml_name
	MlMeth  uintptr // +8 PyCFunction ml_meth
	MlFlags int32   // +16 int ml_flags
	MlDoc   uintptr // +24 const char * ml_doc
}

// PyModuleDef mirrors the C struct PyModuleDef (size 104; pytypedefs.h:12).
type PyModuleDef struct {
	MBase     PyModuleDefBase // +0 PyModuleDef_Base m_base
	MName     uintptr         // +40 const char * m_name
	MDoc      uintptr         // +48 const char * m_doc
	MSize     int64           // +56 Py_ssize_t m_size
	MMethods  uintptr         // +64 PyMethodDef * m_methods
	MSlots    uintptr         // +72 PyModuleDef_Slot * m_slots
	MTraverse uintptr         // +80 traverseproc m_traverse
	MClear    uintptr         // +88 inquiry m_clear
	MFree     uintptr         // +96 freefunc m_free
}

// PyModuleDefSlot mirrors the C struct PyModuleDef_Slot (size 16; pytypedefs.h:13).
type PyModuleDefSlot struct {
	Slot  int32   // +0 int slot
	Value uintptr // +8 void * value
}

// PyObject mirrors the C struct _object (size 16; pytypedefs.h:18).
type PyObject struct {
	ObRefcnt int64   // +0 Py_ssize_t ob_refcnt
	ObType   uintptr // +8 PyTypeObject * ob_type
}

// PyThreadState mirrors the C struct _ts (size 352; pytypedefs.h:24).
type PyThreadState struct {
	Prev                         uintptr        // +0 PyThreadState * prev
	Next                         uintptr        // +8 PyThreadState * next
	Interp                       uintptr        // +16 PyInterpreterState * interp
	Initialized                  int32          // +24 int _initialized
	Static                       int32          // +28 int _static
	RecursionRemaining           int32          // +32 int recursion_remaining
	RecursionLimit               int32          // +36 int recursion_limit
	RecursionHeadroom            int32          // +40 int recursion_headroom
	Tracing                      int32          // +44 int tracing
	TracingWhat                  int32          // +48 int tracing_what
	Cframe                       uintptr        // +56 _PyCFrame * cframe
	CProfilefunc                 uintptr        // +64 Py_tracefunc c_profilefunc
	CTracefunc                   uintptr        // +72 Py_tracefunc c_tracefunc
	CProfileobj                  uintptr        // +80 PyObject * c_profileobj
	CTraceobj                    uintptr        // +88 PyObject * c_traceobj
	CurexcType                   uintptr        // +96 PyObject * curexc_type
	CurexcValue                  uintptr        // +104 PyObject * curexc_value
	CurexcTraceback              uintptr        // +112 PyObject * curexc_traceback
	ExcInfo                      uintptr        // +120 _PyErr_StackItem * exc_info
	Dict                         uintptr        // +128 PyObject * dict
	GilstateCounter              int32          // +136 int gilstate_counter
	AsyncExc                     uintptr        // +144 PyObject * async_exc
	ThreadId                     uint32         // +152 unsigned long thread_id
	NativeThreadId               uint32         // +156 unsigned long native_thread_id
	TrashDeleteNesting           int32          // +160 int trash_delete_nesting
	TrashDeleteLater             uintptr        // +168 PyObject * trash_delete_later
	OnDelete                     uintptr        // +176 void (*)(void *) on_delete
	OnDeleteData                 uintptr        // +184 void * on_delete_data
	CoroutineOriginTrackingDepth int32          // +192 int coroutine_origin_tracking_depth
	AsyncGenFirstiter            uintptr        // +200 PyObject * async_gen_firstiter
	AsyncGenFinalizer            uintptr        // +208 PyObject * async_gen_finalizer
	Context                      uintptr        // +216 PyObject * context
	ContextVer                   uint64         // +224 uint64_t context_ver
	Id                           uint64         // +232 uint64_t id
	TraceInfo                    PyTraceInfo    // +240 PyTraceInfo trace_info
	DatastackChunk               uintptr        // +288 _PyStackChunk * datastack_chunk
	DatastackTop                 uintptr        // +296 PyObject ** datastack_top
	DatastackLimit               uintptr        // +304 PyObject ** datastack_limit
	ExcState                     PyErrStackItem // +312 _PyErr_StackItem exc_state
	RootCframe                   PyCFrame       // +328 _PyCFrame root_cframe
}

// PyTypeObject mirrors the C struct _typeobject (size 408; pytypedefs.h:20).
type PyTypeObject struct {
	PyObjectVARHEAD            // +0
	TpName             uintptr // +24 const char * tp_name
	TpBasicsize        int64   // +32 Py_ssize_t tp_basicsize
	TpItemsize         int64   // +40 Py_ssize_t tp_itemsize
	TpDealloc          uintptr // +48 destructor tp_dealloc
	TpVectorcallOffset int64   // +56 Py_ssize_t tp_vectorcall_offset
	TpGetattr          uintptr // +64 getattrfunc tp_getattr
	TpSetattr          uintptr // +72 setattrfunc tp_setattr
	TpAsAsync          uintptr // +80 PyAsyncMethods * tp_as_async
	TpRepr             uintptr // +88 reprfunc tp_repr
	TpAsNumber         uintptr // +96 PyNumberMethods * tp_as_number
	TpAsSequence       uintptr // +104 PySequenceMethods * tp_as_sequence
	TpAsMapping        uintptr // +112 PyMappingMethods * tp_as_mapping
	TpHash             uintptr // +120 hashfunc tp_hash
	TpCall             uintptr // +128 ternaryfunc tp_call
	TpStr              uintptr // +136 reprfunc tp_str
	TpGetattro         uintptr // +144 getattrofunc tp_getattro
	TpSetattro         uintptr // +152 setattrofunc tp_setattro
	TpAsBuffer         uintptr // +160 PyBufferProcs * tp_as_buffer
	TpFlags            uint32  // +168 unsigned long tp_flags
	TpDoc              uintptr // +176 const char * tp_doc
	TpTraverse         uintptr // +184 traverseproc tp_traverse
	TpClear            uintptr // +192 inquiry tp_clear
	TpRichcompare      uintptr // +200 richcmpfunc tp_richcompare
	TpWeaklistoffset   int64   // +208 Py_ssize_t tp_weaklistoffset
	TpIter             uintptr // +216 getiterfunc tp_iter
	TpIternext         uintptr // +224 iternextfunc tp_iternext
	TpMethods          uintptr // +232 PyMethodDef * tp_methods
	TpMembers          uintptr // +240 PyMemberDef * tp_members
	TpGetset           uintptr // +248 PyGetSetDef * tp_getset
	TpBase             uintptr // +256 PyTypeObject * tp_base
	TpDict             uintptr // +264 PyObject * tp_dict
	TpDescrGet         uintptr // +272 descrgetfunc tp_descr_get
	TpDescrSet         uintptr // +280 descrsetfunc tp_descr_set
	TpDictoffset       int64   // +288 Py_ssize_t tp_dictoffset
	TpInit             uintptr // +296 initproc tp_init
	TpAlloc            uintptr // +304 allocfunc tp_alloc
	TpNew              uintptr // +312 newfunc tp_new
	TpFree             uintptr // +320 freefunc tp_free
	TpIsGc             uintptr // +328 inquiry tp_is_gc
	TpBases            uintptr // +336 PyObject * tp_bases
	TpMro              uintptr // +344 PyObject * tp_mro
	TpCache            uintptr // +352 PyObject * tp_cache
	TpSubclasses       uintptr // +360 PyObject * tp_subclasses
	TpWeaklist         uintptr // +368 PyObject * tp_weaklist
	TpDel              uintptr // +376 destructor tp_del
	TpVersionTag       uint32  // +384 unsigned int tp_version_tag
	TpFinalize         uintptr // +392 destructor tp_finalize
	TpVectorcall       uintptr // +400 vectorcallfunc tp_vectorcall
}
