// Code generated by h2go; DO NOT EDIT.

package py313

// PyHashFuncDef mirrors the C struct PyHash_FuncDef (size 24; pyhash.h:37).
type PyHashFuncDef struct {
	Hash     uintptr // +0 Py_hash_t (*const)(const void *, Py_ssize_t) hash
	Name     uintptr // +8 const char * name
	HashBits int32   // +16 const int hash_bits
	SeedBits int32   // +20 const int seed_bits
}
