// Code generated by h2go; DO NOT EDIT.

package py313

// PyLongValue mirrors the C struct _PyLongValue (size 16; longintrepr.h:93).
type PyLongValue struct {
	LvTag   uint64    // +0 uintptr_t lv_tag
	ObDigit [1]uint32 // +8 digit[1] ob_digit
}
