// Code generated by h2go; DO NOT EDIT.

package py313

// PyASCIIObject mirrors the C struct PyASCIIObject (size 40; unicodeobject.h:54).
type PyASCIIObject struct {
	PyObjectHEAD         // +0
	Length       int64   // +16 Py_ssize_t length
	Hash         int64   // +24 Py_hash_t hash
	State        [4]byte // +32 struct (unnamed at unicodeobject.h:102:5) state
}

// PyCompactUnicodeObject mirrors the C struct PyCompactUnicodeObject (size 56; unicodeobject.h:156).
type PyCompactUnicodeObject struct {
	Base       PyASCIIObject // +0 PyASCIIObject _base
	Utf8Length int64         // +40 Py_ssize_t utf8_length
	Utf8       uintptr       // +48 char * utf8
}

// PyUnicodeObject mirrors the C struct PyUnicodeObject (size 64; unicodeobject.h:164).
type PyUnicodeObject struct {
	Base PyCompactUnicodeObject // +0 PyCompactUnicodeObject _base
	Data [8]byte                // +56 union (unnamed at unicodeobject.h:166:5) data
}

// PyUnicodeWriter mirrors the C struct _PyUnicodeWriter (size 56; unicodeobject.h:449).
type PyUnicodeWriter struct {
	Buffer       uintptr // +0 PyObject * buffer
	Data         uintptr // +8 void * data
	Kind         int32   // +16 int kind
	Maxchar      uint32  // +20 Py_UCS4 maxchar
	Size         int64   // +24 Py_ssize_t size
	Pos          int64   // +32 Py_ssize_t pos
	MinLength    int64   // +40 Py_ssize_t min_length
	MinChar      uint32  // +48 Py_UCS4 min_char
	Overallocate uint8   // +52 unsigned char overallocate
	Readonly     uint8   // +53 unsigned char readonly
}
