// Code generated by h2go; DO NOT EDIT.

package py313

// PyCodeAddressRange mirrors the C struct _line_offsets (size 40; code.h:291).
type PyCodeAddressRange struct {
	ArStart int32    // +0 int ar_start
	ArEnd   int32    // +4 int ar_end
	ArLine  int32    // +8 int ar_line
	Opaque  [24]byte // +16 struct _opaque opaque
}

// PyCodeEvent is the C enum enum PyCodeEvent (size 4; code.h:252).
type PyCodeEvent uint32

// PyCoCached mirrors the C struct _PyCoCached (size 32; code.h:28).
type PyCoCached struct {
	CoCode     uintptr // +0 PyObject * _co_code
	CoVarnames uintptr // +8 PyObject * _co_varnames
	CoCellvars uintptr // +16 PyObject * _co_cellvars
	CoFreevars uintptr // +24 PyObject * _co_freevars
}

// PyCoLineInstrumentationData mirrors the C struct _PyCoLineInstrumentationData (size 2; code.h:39).
type PyCoLineInstrumentationData struct {
	BytesPerEntry uint8    // +0 uint8_t bytes_per_entry
	Data          [1]uint8 // +1 uint8_t[1] data
}

// PyCoMonitoringData mirrors the C struct _PyCoMonitoringData (size 64; code.h:54).
type PyCoMonitoringData struct {
	LocalMonitors         PyLocalMonitors // +0 _Py_LocalMonitors local_monitors
	ActiveMonitors        PyLocalMonitors // +10 _Py_LocalMonitors active_monitors
	Tools                 uintptr         // +24 uint8_t * tools
	Lines                 uintptr         // +32 _PyCoLineInstrumentationData * lines
	LineTools             uintptr         // +40 uint8_t * line_tools
	PerInstructionOpcodes uintptr         // +48 uint8_t * per_instruction_opcodes
	PerInstructionTools   uintptr         // +56 uint8_t * per_instruction_tools
}

// PyCodeLocationInfoKind is the C enum enum _PyCodeLocationInfoKind (size 4; code.h:352).
type PyCodeLocationInfoKind uint32

// PyExecutorArray mirrors the C struct _PyExecutorArray (size 16; code.h:45).
type PyExecutorArray struct {
	Size      int32      // +0 int size
	Capacity  int32      // +4 int capacity
	Executors [1]uintptr // +8 struct _PyExecutorObject *[1] executors
}

// PyGlobalMonitors mirrors the C struct _Py_GlobalMonitors (size 15; code.h:23).
type PyGlobalMonitors struct {
	Tools [15]uint8 // +0 uint8_t[15] tools
}

// PyLocalMonitors mirrors the C struct _Py_LocalMonitors (size 10; code.h:19).
type PyLocalMonitors struct {
	Tools [10]uint8 // +0 uint8_t[10] tools
}
