// Code generated by h2go; DO NOT EDIT.

package py313

// PyMonitoringState mirrors the C struct _PyMonitoringState (size 2; monitoring.h:37).
type PyMonitoringState struct {
	Active uint8 // +0 uint8_t active
	Opaque uint8 // +1 uint8_t opaque
}
