// Code generated by h2go; DO NOT EDIT.

package py313

// PyObjectArenaAllocator mirrors the C struct PyObjectArenaAllocator (size 24; objimpl.h:59).
type PyObjectArenaAllocator struct {
	Ctx   uintptr // +0 void * ctx
	Alloc uintptr // +8 void *(*)(void *, size_t) alloc
	Free  uintptr // +16 void (*)(void *, void *, size_t) free
}
