// Code generated by h2go; DO NOT EDIT.

package py313

// PyTupleObject mirrors the C struct PyTupleObject (size 32; tupleobject.h:5).
type PyTupleObject struct {
	PyObjectVARHEAD            // +0
	ObItem          [1]uintptr // +24 PyObject *[1] ob_item
}
