// Code generated by h2go; DO NOT EDIT.

package py38

// PyCompilerFlags mirrors the C struct PyCompilerFlags (size 8; compile.h:35).
type PyCompilerFlags struct {
	CfFlags          int32 // +0 int cf_flags
	CfFeatureVersion int32 // +4 int cf_feature_version
}

// PyFutureFeatures mirrors the C struct PyFutureFeatures (size 8; compile.h:46).
type PyFutureFeatures struct {
	FfFeatures int32 // +0 int ff_features
	FfLineno   int32 // +4 int ff_lineno
}
