// Code generated by h2go; DO NOT EDIT.

package py38

// PyExceptionHEAD mirrors the struct-shaped C macro PyException_HEAD.
type PyExceptionHEAD struct {
	PyObjectHEAD            // +0
	Dict            uintptr // +16 PyObject * dict
	Args            uintptr // +24 PyObject * args
	Traceback       uintptr // +32 PyObject * traceback
	Context         uintptr // +40 PyObject * context
	Cause           uintptr // +48 PyObject * cause
	SuppressContext int8    // +56 char suppress_context
}

// PyBaseExceptionObject mirrors the C struct PyBaseExceptionObject (size 64; pyerrors.h:17).
type PyBaseExceptionObject struct {
	PyExceptionHEAD // +0
}

// PyEnvironmentErrorObject is the C typedef "PyOSErrorObject" (pyerrors.h:70).
type PyEnvironmentErrorObject = PyOSErrorObject

// PyImportErrorObject mirrors the C struct PyImportErrorObject (size 88; pyerrors.h:31).
type PyImportErrorObject struct {
	PyExceptionHEAD         // +0
	Msg             uintptr // +64 PyObject * msg
	Name            uintptr // +72 PyObject * name
	Path            uintptr // +80 PyObject * path
}

// PyOSErrorObject mirrors the C struct PyOSErrorObject (size 112; pyerrors.h:52).
type PyOSErrorObject struct {
	PyExceptionHEAD         // +0
	Myerrno         uintptr // +64 PyObject * myerrno
	Strerror        uintptr // +72 PyObject * strerror
	Filename        uintptr // +80 PyObject * filename
	Filename2       uintptr // +88 PyObject * filename2
	Winerror        uintptr // +96 PyObject * winerror
	Written         int64   // +104 Py_ssize_t written
}

// PyStopIterationObject mirrors the C struct PyStopIterationObject (size 72; pyerrors.h:64).
type PyStopIterationObject struct {
	PyExceptionHEAD         // +0
	Value           uintptr // +64 PyObject * value
}

// PySyntaxErrorObject mirrors the C struct PySyntaxErrorObject (size 112; pyerrors.h:21).
type PySyntaxErrorObject struct {
	PyExceptionHEAD          // +0
	Msg              uintptr // +64 PyObject * msg
	Filename         uintptr // +72 PyObject * filename
	Lineno           uintptr // +80 PyObject * lineno
	Offset           uintptr // +88 PyObject * offset
	Text             uintptr // +96 PyObject * text
	PrintFileAndLine uintptr // +104 PyObject * print_file_and_line
}

// PySystemExitObject mirrors the C struct PySystemExitObject (size 72; pyerrors.h:47).
type PySystemExitObject struct {
	PyExceptionHEAD         // +0
	Code            uintptr // +64 PyObject * code
}

// PyUnicodeErrorObject mirrors the C struct PyUnicodeErrorObject (size 104; pyerrors.h:38).
type PyUnicodeErrorObject struct {
	PyExceptionHEAD         // +0
	Encoding        uintptr // +64 PyObject * encoding
	Object          uintptr // +72 PyObject * object
	Start           int64   // +80 Py_ssize_t start
	End             int64   // +88 Py_ssize_t end
	Reason          uintptr // +96 PyObject * reason
}

// PyWindowsErrorObject is the C typedef "PyOSErrorObject" (pyerrors.h:72).
type PyWindowsErrorObject = PyOSErrorObject
