// Code generated by h2go; DO NOT EDIT.

package py38

// PyCFunctionObject mirrors the C struct PyCFunctionObject (size 56; methodobject.h:97).
type PyCFunctionObject struct {
	PyObjectHEAD         // +0
	MMl          uintptr // +16 PyMethodDef * m_ml
	MSelf        uintptr // +24 PyObject * m_self
	MModule      uintptr // +32 PyObject * m_module
	MWeakreflist uintptr // +40 PyObject * m_weakreflist
	Vectorcall   uintptr // +48 vectorcallfunc vectorcall
}
