// Code generated by h2go; DO NOT EDIT.

package py38

// PyArgParser mirrors the C struct _PyArg_Parser (size 64; modsupport.h:89).
type PyArgParser struct {
	Format    uintptr // +0 const char * format
	Keywords  uintptr // +8 const char *const * keywords
	Fname     uintptr // +16 const char * fname
	CustomMsg uintptr // +24 const char * custom_msg
	Pos       int32   // +32 int pos
	Min       int32   // +36 int min
	Max       int32   // +40 int max
	Kwtuple   uintptr // +48 PyObject * kwtuple
	Next      uintptr // +56 struct _PyArg_Parser * next
}
