// Code generated by h2go; DO NOT EDIT.

package py38

// PyGILStateSTATE is the C enum enum PyGILState_STATE (size 4; pystate.h:82).
type PyGILStateSTATE uint32

// PyThreadState mirrors the C struct _ts (size 256; pystate.h:19).
type PyThreadState struct {
	Prev                         uintptr        // +0 struct _ts * prev
	Next                         uintptr        // +8 struct _ts * next
	Interp                       uintptr        // +16 PyInterpreterState * interp
	Frame                        uintptr        // +24 struct _frame * frame
	RecursionDepth               int32          // +32 int recursion_depth
	Overflowed                   int8           // +36 char overflowed
	RecursionCritical            int8           // +37 char recursion_critical
	StackcheckCounter            int32          // +40 int stackcheck_counter
	Tracing                      int32          // +44 int tracing
	UseTracing                   int32          // +48 int use_tracing
	CProfilefunc                 uintptr        // +56 Py_tracefunc c_profilefunc
	CTracefunc                   uintptr        // +64 Py_tracefunc c_tracefunc
	CProfileobj                  uintptr        // +72 PyObject * c_profileobj
	CTraceobj                    uintptr        // +80 PyObject * c_traceobj
	CurexcType                   uintptr        // +88 PyObject * curexc_type
	CurexcValue                  uintptr        // +96 PyObject * curexc_value
	CurexcTraceback              uintptr        // +104 PyObject * curexc_traceback
	ExcState                     PyErrStackItem // +112 _PyErr_StackItem exc_state
	ExcInfo                      uintptr        // +144 _PyErr_StackItem * exc_info
	Dict                         uintptr        // +152 PyObject * dict
	GilstateCounter              int32          // +160 int gilstate_counter
	AsyncExc                     uintptr        // +168 PyObject * async_exc
	ThreadId                     uint32         // +176 unsigned long thread_id
	TrashDeleteNesting           int32          // +180 int trash_delete_nesting
	TrashDeleteLater             uintptr        // +184 PyObject * trash_delete_later
	OnDelete                     uintptr        // +192 void (*)(void *) on_delete
	OnDeleteData                 uintptr        // +200 void * on_delete_data
	CoroutineOriginTrackingDepth int32          // +208 int coroutine_origin_tracking_depth
	AsyncGenFirstiter            uintptr        // +216 PyObject * async_gen_firstiter
	AsyncGenFinalizer            uintptr        // +224 PyObject * async_gen_finalizer
	Context                      uintptr        // +232 PyObject * context
	ContextVer                   uint64         // +240 uint64_t context_ver
	Id                           uint64         // +248 uint64_t id
}
