// Code generated by h2go; DO NOT EDIT.

package py311

// PyGenObjectHEAD mirrors the struct-shaped C macro _PyGenObject_HEAD.
type PyGenObjectHEAD struct {
	PyObjectHEAD                       // +0
	GiCode              uintptr        // +16 PyCodeObject * gi_code
	GiWeakreflist       uintptr        // +24 PyObject * gi_weakreflist
	GiName              uintptr        // +32 PyObject * gi_name
	GiQualname          uintptr        // +40 PyObject * gi_qualname
	GiExcState          PyErrStackItem // +48 _PyErr_StackItem gi_exc_state
	GiOriginOrFinalizer uintptr        // +64 PyObject * gi_origin_or_finalizer
	GiHooksInited       int8           // +72 char gi_hooks_inited
	GiClosed            int8           // +73 char gi_closed
	GiRunningAsync      int8           // +74 char gi_running_async
	GiFrameState        int8           // +75 int8_t gi_frame_state
	GiIframe            [1]uintptr     // +80 PyObject *[1] gi_iframe
}

// PyAsyncGenObject mirrors the C struct PyAsyncGenObject (size 88; genobject.h:67).
type PyAsyncGenObject struct {
	PyObjectHEAD                       // +0
	AgCode              uintptr        // +16 PyCodeObject * ag_code
	AgWeakreflist       uintptr        // +24 PyObject * ag_weakreflist
	AgName              uintptr        // +32 PyObject * ag_name
	AgQualname          uintptr        // +40 PyObject * ag_qualname
	AgExcState          PyErrStackItem // +48 _PyErr_StackItem ag_exc_state
	AgOriginOrFinalizer uintptr        // +64 PyObject * ag_origin_or_finalizer
	AgHooksInited       int8           // +72 char ag_hooks_inited
	AgClosed            int8           // +73 char ag_closed
	AgRunningAsync      int8           // +74 char ag_running_async
	AgFrameState        int8           // +75 int8_t ag_frame_state
	AgIframe            [1]uintptr     // +80 PyObject *[1] ag_iframe
}

// PyCoroObject mirrors the C struct PyCoroObject (size 88; genobject.h:53).
type PyCoroObject struct {
	PyObjectHEAD                       // +0
	CrCode              uintptr        // +16 PyCodeObject * cr_code
	CrWeakreflist       uintptr        // +24 PyObject * cr_weakreflist
	CrName              uintptr        // +32 PyObject * cr_name
	CrQualname          uintptr        // +40 PyObject * cr_qualname
	CrExcState          PyErrStackItem // +48 _PyErr_StackItem cr_exc_state
	CrOriginOrFinalizer uintptr        // +64 PyObject * cr_origin_or_finalizer
	CrHooksInited       int8           // +72 char cr_hooks_inited
	CrClosed            int8           // +73 char cr_closed
	CrRunningAsync      int8           // +74 char cr_running_async
	CrFrameState        int8           // +75 int8_t cr_frame_state
	CrIframe            [1]uintptr     // +80 PyObject *[1] cr_iframe
}

// PyGenObject mirrors the C struct PyGenObject (size 88; genobject.h:33).
type PyGenObject struct {
	PyGenObjectHEAD // +0
}
