// Code generated by h2go; DO NOT EDIT.

package py311

// PyConfig mirrors the C struct PyConfig (size 424; initconfig.h:134).
type PyConfig struct {
	ConfigInit            int32            // +0 int _config_init
	Isolated              int32            // +4 int isolated
	UseEnvironment        int32            // +8 int use_environment
	DevMode               int32            // +12 int dev_mode
	InstallSignalHandlers int32            // +16 int install_signal_handlers
	UseHashSeed           int32            // +20 int use_hash_seed
	HashSeed              uint64           // +24 unsigned long hash_seed
	Faulthandler          int32            // +32 int faulthandler
	Tracemalloc           int32            // +36 int tracemalloc
	ImportTime            int32            // +40 int import_time
	CodeDebugRanges       int32            // +44 int code_debug_ranges
	ShowRefCount          int32            // +48 int show_ref_count
	DumpRefs              int32            // +52 int dump_refs
	DumpRefsFile          uintptr          // +56 wchar_t * dump_refs_file
	MallocStats           int32            // +64 int malloc_stats
	FilesystemEncoding    uintptr          // +72 wchar_t * filesystem_encoding
	FilesystemErrors      uintptr          // +80 wchar_t * filesystem_errors
	PycachePrefix         uintptr          // +88 wchar_t * pycache_prefix
	ParseArgv             int32            // +96 int parse_argv
	OrigArgv              PyWideStringList // +104 PyWideStringList orig_argv
	Argv                  PyWideStringList // +120 PyWideStringList argv
	Xoptions              PyWideStringList // +136 PyWideStringList xoptions
	Warnoptions           PyWideStringList // +152 PyWideStringList warnoptions
	SiteImport            int32            // +168 int site_import
	BytesWarning          int32            // +172 int bytes_warning
	WarnDefaultEncoding   int32            // +176 int warn_default_encoding
	Inspect               int32            // +180 int inspect
	Interactive           int32            // +184 int interactive
	OptimizationLevel     int32            // +188 int optimization_level
	ParserDebug           int32            // +192 int parser_debug
	WriteBytecode         int32            // +196 int write_bytecode
	Verbose               int32            // +200 int verbose
	Quiet                 int32            // +204 int quiet
	UserSiteDirectory     int32            // +208 int user_site_directory
	ConfigureCStdio       int32            // +212 int configure_c_stdio
	BufferedStdio         int32            // +216 int buffered_stdio
	StdioEncoding         uintptr          // +224 wchar_t * stdio_encoding
	StdioErrors           uintptr          // +232 wchar_t * stdio_errors
	CheckHashPycsMode     uintptr          // +240 wchar_t * check_hash_pycs_mode
	UseFrozenModules      int32            // +248 int use_frozen_modules
	SafePath              int32            // +252 int safe_path
	PathconfigWarnings    int32            // +256 int pathconfig_warnings
	ProgramName           uintptr          // +264 wchar_t * program_name
	PythonpathEnv         uintptr          // +272 wchar_t * pythonpath_env
	Home                  uintptr          // +280 wchar_t * home
	Platlibdir            uintptr          // +288 wchar_t * platlibdir
	ModuleSearchPathsSet  int32            // +296 int module_search_paths_set
	ModuleSearchPaths     PyWideStringList // +304 PyWideStringList module_search_paths
	StdlibDir             uintptr          // +320 wchar_t * stdlib_dir
	Executable            uintptr          // +328 wchar_t * executable
	BaseExecutable        uintptr          // +336 wchar_t * base_executable
	Prefix                uintptr          // +344 wchar_t * prefix
	BasePrefix            uintptr          // +352 wchar_t * base_prefix
	ExecPrefix            uintptr          // +360 wchar_t * exec_prefix
	BaseExecPrefix        uintptr          // +368 wchar_t * base_exec_prefix
	SkipSourceFirstLine   int32            // +376 int skip_source_first_line
	RunCommand            uintptr          // +384 wchar_t * run_command
	RunModule             uintptr          // +392 wchar_t * run_module
	RunFilename           uintptr          // +400 wchar_t * run_filename
	InstallImportlib      int32            // +408 int _install_importlib
	InitMain              int32            // +412 int _init_main
	IsolatedInterpreter   int32            // +416 int _isolated_interpreter
	IsPythonBuild         int32            // +420 int _is_python_build
}

// PyPreConfig mirrors the C struct PyPreConfig (size 40; initconfig.h:47).
type PyPreConfig struct {
	ConfigInit        int32 // +0 int _config_init
	ParseArgv         int32 // +4 int parse_argv
	Isolated          int32 // +8 int isolated
	UseEnvironment    int32 // +12 int use_environment
	ConfigureLocale   int32 // +16 int configure_locale
	CoerceCLocale     int32 // +20 int coerce_c_locale
	CoerceCLocaleWarn int32 // +24 int coerce_c_locale_warn
	Utf8Mode          int32 // +28 int utf8_mode
	DevMode           int32 // +32 int dev_mode
	Allocator         int32 // +36 int allocator
}

// PyStatus mirrors the C struct PyStatus (size 32; initconfig.h:10).
type PyStatus struct {
	Type     int32   // +0 enum (unnamed at initconfig.h:11:5) _type
	Func     uintptr // +8 const char * func
	ErrMsg   uintptr // +16 const char * err_msg
	Exitcode int32   // +24 int exitcode
}

// PyWideStringList mirrors the C struct PyWideStringList (size 16; initconfig.h:31).
type PyWideStringList struct {
	Length int64   // +0 Py_ssize_t length
	Items  uintptr // +8 wchar_t ** items
}
