// Code generated by h2go; DO NOT EDIT.

package py311

// PyDescrCOMMON mirrors the struct-shaped C macro PyDescr_COMMON.
type PyDescrCOMMON struct {
	DCommon PyDescrObject // +0 PyDescrObject d_common
}

// PyDescrObject mirrors the C struct PyDescrObject (size 40; descrobject.h:26).
type PyDescrObject struct {
	PyObjectHEAD         // +0
	DType        uintptr // +16 PyTypeObject * d_type
	DName        uintptr // +24 PyObject * d_name
	DQualname    uintptr // +32 PyObject * d_qualname
}

// PyGetSetDescrObject mirrors the C struct PyGetSetDescrObject (size 48; descrobject.h:49).
type PyGetSetDescrObject struct {
	PyDescrCOMMON         // +0
	DGetset       uintptr // +40 PyGetSetDef * d_getset
}

// PyMemberDescrObject mirrors the C struct PyMemberDescrObject (size 48; descrobject.h:44).
type PyMemberDescrObject struct {
	PyDescrCOMMON         // +0
	DMember       uintptr // +40 PyMemberDef * d_member
}

// PyMethodDescrObject mirrors the C struct PyMethodDescrObject (size 56; descrobject.h:38).
type PyMethodDescrObject struct {
	PyDescrCOMMON         // +0
	DMethod       uintptr // +40 PyMethodDef * d_method
	Vectorcall    uintptr // +48 vectorcallfunc vectorcall
}

// PyWrapperDescrObject mirrors the C struct PyWrapperDescrObject (size 56; descrobject.h:54).
type PyWrapperDescrObject struct {
	PyDescrCOMMON         // +0
	DBase         uintptr // +40 struct wrapperbase * d_base
	DWrapped      uintptr // +48 void * d_wrapped
}
