// Code generated by h2go; DO NOT EDIT.

package py37

// PyBytesObject mirrors the C struct PyBytesObject (size 40; bytesobject.h:31).
type PyBytesObject struct {
	PyObjectVARHEAD         // +0
	ObShash         int64   // +24 Py_hash_t ob_shash
	ObSval          [1]int8 // +32 char[1] ob_sval
}

// PyBytesWriter mirrors the C struct _PyBytesWriter (size 552; bytesobject.h:144).
type PyBytesWriter struct {
	Buffer         uintptr   // +0 PyObject * buffer
	Allocated      int64     // +8 Py_ssize_t allocated
	MinSize        int64     // +16 Py_ssize_t min_size
	UseBytearray   int32     // +24 int use_bytearray
	Overallocate   int32     // +28 int overallocate
	UseSmallBuffer int32     // +32 int use_small_buffer
	SmallBuffer    [512]int8 // +36 char[512] small_buffer
}
