// Code generated by h2go; DO NOT EDIT.

package py37

// PyInitError mirrors the C struct _PyInitError (size 24; pylifecycle.h:11).
type PyInitError struct {
	Prefix  uintptr // +0 const char * prefix
	Msg     uintptr // +8 const char * msg
	UserErr int32   // +16 int user_err
}
