// Code generated by h2go; DO NOT EDIT.

package py37

// PyStructSequence is the C typedef "PyTupleObject" (structseq.h:35).
type PyStructSequence = PyTupleObject

// PyStructSequenceDesc mirrors the C struct PyStructSequence_Desc (size 32; structseq.h:15).
type PyStructSequenceDesc struct {
	Name        uintptr // +0 const char * name
	Doc         uintptr // +8 const char * doc
	Fields      uintptr // +16 struct PyStructSequence_Field * fields
	NInSequence int32   // +24 int n_in_sequence
}

// PyStructSequenceField mirrors the C struct PyStructSequence_Field (size 16; structseq.h:10).
type PyStructSequenceField struct {
	Name uintptr // +0 const char * name
	Doc  uintptr // +8 const char * doc
}
