// Code generated by h2go; DO NOT EDIT.

package py27

// PyIntObject mirrors the C struct PyIntObject (size 24; intobject.h:23).
type PyIntObject struct {
	PyObjectHEAD       // +0
	ObIval       int32 // +16 long ob_ival
}
