// Code generated by h2go; DO NOT EDIT.

package py27

// PyCFunctionObject mirrors the C struct PyCFunctionObject (size 40; methodobject.h:81).
type PyCFunctionObject struct {
	PyObjectHEAD         // +0
	MMl          uintptr // +16 PyMethodDef * m_ml
	MSelf        uintptr // +24 PyObject * m_self
	MModule      uintptr // +32 PyObject * m_module
}

// PyMethodChain mirrors the C struct PyMethodChain (size 16; methodobject.h:73).
type PyMethodChain struct {
	Methods uintptr // +0 PyMethodDef * methods
	Link    uintptr // +8 struct PyMethodChain * link
}
