// Code generated by h2go; DO NOT EDIT.

package py27

// PyStringObject mirrors the C struct PyStringObject (size 40; stringobject.h:35).
type PyStringObject struct {
	PyObjectVARHEAD         // +0
	ObShash         int32   // +24 long ob_shash
	ObSstate        int32   // +28 int ob_sstate
	ObSval          [1]int8 // +32 char[1] ob_sval
}
