// Code generated by h2go; DO NOT EDIT.

package py27

// PyStructSequence mirrors the C struct PyStructSequence (size 32; structseq.h:29).
type PyStructSequence struct {
	PyObjectVARHEAD            // +0
	ObItem          [1]uintptr // +24 PyObject *[1] ob_item
}

// PyStructSequenceDesc mirrors the C struct PyStructSequence_Desc (size 32; structseq.h:15).
type PyStructSequenceDesc struct {
	Name        uintptr // +0 char * name
	Doc         uintptr // +8 char * doc
	Fields      uintptr // +16 struct PyStructSequence_Field * fields
	NInSequence int32   // +24 int n_in_sequence
}

// PyStructSequenceField mirrors the C struct PyStructSequence_Field (size 16; structseq.h:10).
type PyStructSequenceField struct {
	Name uintptr // +0 char * name
	Doc  uintptr // +8 char * doc
}
