// Code generated by h2go; DO NOT EDIT.

package py32

// PyMemoryViewObject mirrors the C struct PyMemoryViewObject (size 112; memoryobject.h:69).
type PyMemoryViewObject struct {
	PyObjectHEAD          // +0
	View         PyBuffer // +16 Py_buffer view
}
