// Code generated by h2go; DO NOT EDIT.

package py32

// PyGILStateSTATE is the C enum enum PyGILState_STATE (size 4; pystate.h:164).
type PyGILStateSTATE uint32

// PyInterpreterState mirrors the C struct _is (size 88; pystate.h:14).
type PyInterpreterState struct {
	Next               uintptr // +0 struct _is * next
	TstateHead         uintptr // +8 struct _ts * tstate_head
	Modules            uintptr // +16 PyObject * modules
	ModulesByIndex     uintptr // +24 PyObject * modules_by_index
	Sysdict            uintptr // +32 PyObject * sysdict
	Builtins           uintptr // +40 PyObject * builtins
	ModulesReloading   uintptr // +48 PyObject * modules_reloading
	CodecSearchPath    uintptr // +56 PyObject * codec_search_path
	CodecSearchCache   uintptr // +64 PyObject * codec_search_cache
	CodecErrorRegistry uintptr // +72 PyObject * codec_error_registry
	CodecsInitialized  int32   // +80 int codecs_initialized
	FscodecInitialized int32   // +84 int fscodec_initialized
}

// PyThreadState mirrors the C struct _ts (size 160; pystate.h:13).
type PyThreadState struct {
	Next               uintptr // +0 struct _ts * next
	Interp             uintptr // +8 PyInterpreterState * interp
	Frame              uintptr // +16 struct _frame * frame
	RecursionDepth     int32   // +24 int recursion_depth
	Overflowed         int8    // +28 char overflowed
	RecursionCritical  int8    // +29 char recursion_critical
	Tracing            int32   // +32 int tracing
	UseTracing         int32   // +36 int use_tracing
	CProfilefunc       uintptr // +40 Py_tracefunc c_profilefunc
	CTracefunc         uintptr // +48 Py_tracefunc c_tracefunc
	CProfileobj        uintptr // +56 PyObject * c_profileobj
	CTraceobj          uintptr // +64 PyObject * c_traceobj
	CurexcType         uintptr // +72 PyObject * curexc_type
	CurexcValue        uintptr // +80 PyObject * curexc_value
	CurexcTraceback    uintptr // +88 PyObject * curexc_traceback
	ExcType            uintptr // +96 PyObject * exc_type
	ExcValue           uintptr // +104 PyObject * exc_value
	ExcTraceback       uintptr // +112 PyObject * exc_traceback
	Dict               uintptr // +120 PyObject * dict
	TickCounter        int32   // +128 int tick_counter
	GilstateCounter    int32   // +132 int gilstate_counter
	AsyncExc           uintptr // +136 PyObject * async_exc
	ThreadId           int32   // +144 long thread_id
	TrashDeleteNesting int32   // +148 int trash_delete_nesting
	TrashDeleteLater   uintptr // +152 PyObject * trash_delete_later
}
