// Code generated by h2go; DO NOT EDIT.

package py30

// PyBytesObject mirrors the C struct PyBytesObject (size 40; bytesobject.h:30).
type PyBytesObject struct {
	PyObjectVARHEAD         // +0
	ObShash         int64   // +24 long ob_shash
	ObSval          [1]int8 // +32 char[1] ob_sval
}
