// Code generated by h2go; DO NOT EDIT.

package py30

// PyCellObject mirrors the C struct PyCellObject (size 24; cellobject.h:9).
type PyCellObject struct {
	PyObjectHEAD         // +0
	ObRef        uintptr // +16 PyObject * ob_ref
}
