// Code generated by h2go; DO NOT EDIT.

package py30

// PyAddrPair mirrors the C struct _addr_pair (size 8; code.h:76).
type PyAddrPair struct {
	ApLower int32 // +0 int ap_lower
	ApUpper int32 // +4 int ap_upper
}

// PyCodeObject mirrors the C struct PyCodeObject (size 128; code.h:10).
type PyCodeObject struct {
	PyObjectHEAD             // +0
	CoArgcount       int32   // +16 int co_argcount
	CoKwonlyargcount int32   // +20 int co_kwonlyargcount
	CoNlocals        int32   // +24 int co_nlocals
	CoStacksize      int32   // +28 int co_stacksize
	CoFlags          int32   // +32 int co_flags
	CoCode           uintptr // +40 PyObject * co_code
	CoConsts         uintptr // +48 PyObject * co_consts
	CoNames          uintptr // +56 PyObject * co_names
	CoVarnames       uintptr // +64 PyObject * co_varnames
	CoFreevars       uintptr // +72 PyObject * co_freevars
	CoCellvars       uintptr // +80 PyObject * co_cellvars
	CoFilename       uintptr // +88 PyObject * co_filename
	CoName           uintptr // +96 PyObject * co_name
	CoFirstlineno    int32   // +104 int co_firstlineno
	CoLnotab         uintptr // +112 PyObject * co_lnotab
	CoZombieframe    uintptr // +120 void * co_zombieframe
}
