// Code generated by h2go; DO NOT EDIT.

package py30

// PyFutureFeatures mirrors the C struct PyFutureFeatures (size 8; compile.h:17).
type PyFutureFeatures struct {
	FfFeatures int32 // +0 int ff_features
	FfLineno   int32 // +4 int ff_lineno
}
