// Code generated by h2go; DO NOT EDIT.

package py30

// PyDictEntry mirrors the C struct PyDictEntry (size 24; dictobject.h:50).
type PyDictEntry struct {
	MeHash  int64   // +0 Py_ssize_t me_hash
	MeKey   uintptr // +8 PyObject * me_key
	MeValue uintptr // +16 PyObject * me_value
}

// PyDictObject mirrors the C struct _dictobject (size 248; dictobject.h:69).
type PyDictObject struct {
	PyObjectHEAD                // +0
	MaFill       int64          // +16 Py_ssize_t ma_fill
	MaUsed       int64          // +24 Py_ssize_t ma_used
	MaMask       int64          // +32 Py_ssize_t ma_mask
	MaTable      uintptr        // +40 PyDictEntry * ma_table
	MaLookup     uintptr        // +48 PyDictEntry *(*)(PyDictObject *, PyObject *, long) ma_lookup
	MaSmalltable [8]PyDictEntry // +56 PyDictEntry[8] ma_smalltable
}
