// Code generated by h2go; DO NOT EDIT.

package py30

// PyFunctionObject mirrors the C struct PyFunctionObject (size 104; funcobject.h:21).
type PyFunctionObject struct {
	PyObjectHEAD            // +0
	FuncCode        uintptr // +16 PyObject * func_code
	FuncGlobals     uintptr // +24 PyObject * func_globals
	FuncDefaults    uintptr // +32 PyObject * func_defaults
	FuncKwdefaults  uintptr // +40 PyObject * func_kwdefaults
	FuncClosure     uintptr // +48 PyObject * func_closure
	FuncDoc         uintptr // +56 PyObject * func_doc
	FuncName        uintptr // +64 PyObject * func_name
	FuncDict        uintptr // +72 PyObject * func_dict
	FuncWeakreflist uintptr // +80 PyObject * func_weakreflist
	FuncModule      uintptr // +88 PyObject * func_module
	FuncAnnotations uintptr // +96 PyObject * func_annotations
}
