// Code generated by h2go; DO NOT EDIT.

package py30

// PyGenObject mirrors the C struct PyGenObject (size 48; genobject.h:12).
type PyGenObject struct {
	PyObjectHEAD          // +0
	GiFrame       uintptr // +16 struct _frame * gi_frame
	GiRunning     int32   // +24 int gi_running
	GiCode        uintptr // +32 PyObject * gi_code
	GiWeakreflist uintptr // +40 PyObject * gi_weakreflist
}
