// Code generated by h2go; DO NOT EDIT.

package py314

// PyAsyncMethods mirrors the C struct PyAsyncMethods (size 32; object.h:130).
type PyAsyncMethods struct {
	AmAwait uintptr // +0 unaryfunc am_await
	AmAiter uintptr // +8 unaryfunc am_aiter
	AmAnext uintptr // +16 unaryfunc am_anext
	AmSend  uintptr // +24 sendfunc am_send
}

// PyBufferProcs mirrors the C struct PyBufferProcs (size 16; object.h:137).
type PyBufferProcs struct {
	BfGetbuffer     uintptr // +0 getbufferproc bf_getbuffer
	BfReleasebuffer uintptr // +8 releasebufferproc bf_releasebuffer
}

// PyHeapTypeObject mirrors the C struct _heaptypeobject (size 936; object.h:266).
type PyHeapTypeObject struct {
	HtType       PyTypeObject      // +0 PyTypeObject ht_type
	AsAsync      PyAsyncMethods    // +416 PyAsyncMethods as_async
	AsNumber     PyNumberMethods   // +448 PyNumberMethods as_number
	AsMapping    PyMappingMethods  // +736 PyMappingMethods as_mapping
	AsSequence   PySequenceMethods // +760 PySequenceMethods as_sequence
	AsBuffer     PyBufferProcs     // +840 PyBufferProcs as_buffer
	HtName       uintptr           // +856 PyObject * ht_name
	HtSlots      uintptr           // +864 PyObject * ht_slots
	HtQualname   uintptr           // +872 PyObject * ht_qualname
	HtCachedKeys uintptr           // +880 struct _dictkeysobject * ht_cached_keys
	HtModule     uintptr           // +888 PyObject * ht_module
	HtTpname     uintptr           // +896 char * _ht_tpname
	HtToken      uintptr           // +904 void * ht_token
	SpecCache    [24]byte          // +912 struct _specialization_cache _spec_cache
}

// PyMappingMethods mirrors the C struct PyMappingMethods (size 24; object.h:122).
type PyMappingMethods struct {
	MpLength       uintptr // +0 lenfunc mp_length
	MpSubscript    uintptr // +8 binaryfunc mp_subscript
	MpAssSubscript uintptr // +16 objobjargproc mp_ass_subscript
}

// PyNumberMethods mirrors the C struct PyNumberMethods (size 288; object.h:61).
type PyNumberMethods struct {
	NbAdd                   uintptr // +0 binaryfunc nb_add
	NbSubtract              uintptr // +8 binaryfunc nb_subtract
	NbMultiply              uintptr // +16 binaryfunc nb_multiply
	NbRemainder             uintptr // +24 binaryfunc nb_remainder
	NbDivmod                uintptr // +32 binaryfunc nb_divmod
	NbPower                 uintptr // +40 ternaryfunc nb_power
	NbNegative              uintptr // +48 unaryfunc nb_negative
	NbPositive              uintptr // +56 unaryfunc nb_positive
	NbAbsolute              uintptr // +64 unaryfunc nb_absolute
	NbBool                  uintptr // +72 inquiry nb_bool
	NbInvert                uintptr // +80 unaryfunc nb_invert
	NbLshift                uintptr // +88 binaryfunc nb_lshift
	NbRshift                uintptr // +96 binaryfunc nb_rshift
	NbAnd                   uintptr // +104 binaryfunc nb_and
	NbXor                   uintptr // +112 binaryfunc nb_xor
	NbOr                    uintptr // +120 binaryfunc nb_or
	NbInt                   uintptr // +128 unaryfunc nb_int
	NbReserved              uintptr // +136 void * nb_reserved
	NbFloat                 uintptr // +144 unaryfunc nb_float
	NbInplaceAdd            uintptr // +152 binaryfunc nb_inplace_add
	NbInplaceSubtract       uintptr // +160 binaryfunc nb_inplace_subtract
	NbInplaceMultiply       uintptr // +168 binaryfunc nb_inplace_multiply
	NbInplaceRemainder      uintptr // +176 binaryfunc nb_inplace_remainder
	NbInplacePower          uintptr // +184 ternaryfunc nb_inplace_power
	NbInplaceLshift         uintptr // +192 binaryfunc nb_inplace_lshift
	NbInplaceRshift         uintptr // +200 binaryfunc nb_inplace_rshift
	NbInplaceAnd            uintptr // +208 binaryfunc nb_inplace_and
	NbInplaceXor            uintptr // +216 binaryfunc nb_inplace_xor
	NbInplaceOr             uintptr // +224 binaryfunc nb_inplace_or
	NbFloorDivide           uintptr // +232 binaryfunc nb_floor_divide
	NbTrueDivide            uintptr // +240 binaryfunc nb_true_divide
	NbInplaceFloorDivide    uintptr // +248 binaryfunc nb_inplace_floor_divide
	NbInplaceTrueDivide     uintptr // +256 binaryfunc nb_inplace_true_divide
	NbIndex                 uintptr // +264 unaryfunc nb_index
	NbMatrixMultiply        uintptr // +272 binaryfunc nb_matrix_multiply
	NbInplaceMatrixMultiply uintptr // +280 binaryfunc nb_inplace_matrix_multiply
}

// PyRefTracerEvent is the C enum enum PyRefTracerEvent (size 4; object.h:466).
type PyRefTracerEvent uint32

// PySequenceMethods mirrors the C struct PySequenceMethods (size 80; object.h:108).
type PySequenceMethods struct {
	SqLength        uintptr // +0 lenfunc sq_length
	SqConcat        uintptr // +8 binaryfunc sq_concat
	SqRepeat        uintptr // +16 ssizeargfunc sq_repeat
	SqItem          uintptr // +24 ssizeargfunc sq_item
	WasSqSlice      uintptr // +32 void * was_sq_slice
	SqAssItem       uintptr // +40 ssizeobjargproc sq_ass_item
	WasSqAssSlice   uintptr // +48 void * was_sq_ass_slice
	SqContains      uintptr // +56 objobjproc sq_contains
	SqInplaceConcat uintptr // +64 binaryfunc sq_inplace_concat
	SqInplaceRepeat uintptr // +72 ssizeargfunc sq_inplace_repeat
}

// PyIdentifier mirrors the C struct _Py_Identifier (size 24; object.h:39).
type PyIdentifier struct {
	String uintptr // +0 const char * string
	Index  int64   // +8 Py_ssize_t index
	Mutex  [1]byte // +16 struct (unnamed at object.h:45:5) mutex
}
