// Code generated by h2go; DO NOT EDIT.

package py314

// PyFrameLocalsProxyObject mirrors the C struct PyFrameLocalsProxyObject (size 24; frameobject.h:32).
type PyFrameLocalsProxyObject struct {
	PyObjectHEAD         // +0
	Frame        uintptr // +16 PyFrameObject * frame
}
