// Code generated by h2go; DO NOT EDIT.

package py314

// PyBytesObject mirrors the C struct PyBytesObject (size 40; bytesobject.h:5).
type PyBytesObject struct {
	PyObjectVARHEAD         // +0
	ObShash         int64   // +24 Py_hash_t ob_shash
	ObSval          [1]int8 // +32 char[1] ob_sval
}
