// Code generated by h2go; DO NOT EDIT.

package py314

// PyCodeAddressRange mirrors the C struct _line_offsets (size 40; code.h:273).
type PyCodeAddressRange struct {
	ArStart int32    // +0 int ar_start
	ArEnd   int32    // +4 int ar_end
	ArLine  int32    // +8 int ar_line
	Opaque  [24]byte // +16 struct _opaque opaque
}

// PyCodeEvent is the C enum enum PyCodeEvent (size 4; code.h:234).
type PyCodeEvent uint32

// PyCoCached mirrors the C struct _PyCoCached (size 32; code.h:11).
type PyCoCached struct {
	CoCode     uintptr // +0 PyObject * _co_code
	CoVarnames uintptr // +8 PyObject * _co_varnames
	CoCellvars uintptr // +16 PyObject * _co_cellvars
	CoFreevars uintptr // +24 PyObject * _co_freevars
}

// PyCodeLocationInfoKind is the C enum enum _PyCodeLocationInfoKind (size 4; code.h:334).
type PyCodeLocationInfoKind uint32

// PyExecutorArray mirrors the C struct _PyExecutorArray (size 16; code.h:18).
type PyExecutorArray struct {
	Size      int32      // +0 int size
	Capacity  int32      // +4 int capacity
	Executors [1]uintptr // +8 struct _PyExecutorObject *[1] executors
}
