// Code generated by h2go; DO NOT EDIT.

package py314

// PyInterpreterConfig mirrors the C struct PyInterpreterConfig (size 28; pylifecycle.h:41).
type PyInterpreterConfig struct {
	UseMainObmalloc            int32 // +0 int use_main_obmalloc
	AllowFork                  int32 // +4 int allow_fork
	AllowExec                  int32 // +8 int allow_exec
	AllowThreads               int32 // +12 int allow_threads
	AllowDaemonThreads         int32 // +16 int allow_daemon_threads
	CheckMultiInterpExtensions int32 // +20 int check_multi_interp_extensions
	Gil                        int32 // +24 int gil
}
