// Code generated by h2go; DO NOT EDIT.

package py314

// PyArgParser mirrors the C struct _PyArg_Parser (size 72; modsupport.h:11).
type PyArgParser struct {
	Format         uintptr    // +0 const char * format
	Keywords       uintptr    // +8 const char *const * keywords
	Fname          uintptr    // +16 const char * fname
	CustomMsg      uintptr    // +24 const char * custom_msg
	Once           PyOnceFlag // +32 _PyOnceFlag once
	IsKwtupleOwned int32      // +36 int is_kwtuple_owned
	Pos            int32      // +40 int pos
	Min            int32      // +44 int min
	Max            int32      // +48 int max
	Kwtuple        uintptr    // +56 PyObject * kwtuple
	Next           uintptr    // +64 struct _PyArg_Parser * next
}

// PyOnceFlag mirrors the C struct _PyOnceFlag (size 1; modsupport.h:7).
type PyOnceFlag struct {
	V uint8 // +0 uint8_t v
}
