// Code generated by h2go; DO NOT EDIT.

package py314

// PyObjectHEAD mirrors the struct-shaped C macro PyObject_HEAD.
type PyObjectHEAD struct {
	ObBase PyObject // +0 PyObject ob_base
}

// PyObjectVARHEAD mirrors the struct-shaped C macro PyObject_VAR_HEAD.
type PyObjectVARHEAD struct {
	ObBase PyVarObject // +0 PyVarObject ob_base
}

// PyCodeDEF mirrors the struct-shaped C macro _PyCode_DEF.
type PyCodeDEF struct {
	PyObjectVARHEAD                  // +0
	CoConsts                 uintptr // +24 PyObject * co_consts
	CoNames                  uintptr // +32 PyObject * co_names
	CoExceptiontable         uintptr // +40 PyObject * co_exceptiontable
	CoFlags                  int32   // +48 int co_flags
	CoArgcount               int32   // +52 int co_argcount
	CoPosonlyargcount        int32   // +56 int co_posonlyargcount
	CoKwonlyargcount         int32   // +60 int co_kwonlyargcount
	CoStacksize              int32   // +64 int co_stacksize
	CoFirstlineno            int32   // +68 int co_firstlineno
	CoNlocalsplus            int32   // +72 int co_nlocalsplus
	CoFramesize              int32   // +76 int co_framesize
	CoNlocals                int32   // +80 int co_nlocals
	CoNcellvars              int32   // +84 int co_ncellvars
	CoNfreevars              int32   // +88 int co_nfreevars
	CoVersion                uint32  // +92 uint32_t co_version
	CoLocalsplusnames        uintptr // +96 PyObject * co_localsplusnames
	CoLocalspluskinds        uintptr // +104 PyObject * co_localspluskinds
	CoFilename               uintptr // +112 PyObject * co_filename
	CoName                   uintptr // +120 PyObject * co_name
	CoQualname               uintptr // +128 PyObject * co_qualname
	CoLinetable              uintptr // +136 PyObject * co_linetable
	CoWeakreflist            uintptr // +144 PyObject * co_weakreflist
	CoExecutors              uintptr // +152 _PyExecutorArray * co_executors
	CoCached                 uintptr // +160 _PyCoCached * _co_cached
	CoInstrumentationVersion uint64  // +168 uintptr_t _co_instrumentation_version
	CoMonitoring             uintptr // +176 struct _PyCoMonitoringData * _co_monitoring
	CoUniqueId               int64   // +184 Py_ssize_t _co_unique_id
	CoFirsttraceable         int32   // +192 int _co_firsttraceable
	CoExtra                  uintptr // +200 void * co_extra
	CoCodeAdaptive           [1]int8 // +208 char[1] co_code_adaptive
}

// PyCodeObject mirrors the C struct PyCodeObject (size 216; pytypedefs.h:21).
type PyCodeObject struct {
	PyCodeDEF // +0
}

// PyGetSetDef mirrors the C struct PyGetSetDef (size 40; pytypedefs.h:15).
type PyGetSetDef struct {
	Name    uintptr // +0 const char * name
	Get     uintptr // +8 getter get
	Set     uintptr // +16 setter set
	Doc     uintptr // +24 const char * doc
	Closure uintptr // +32 void * closure
}

// PyLongObject mirrors the C struct _longobject (size 32; pytypedefs.h:19).
type PyLongObject struct {
	PyObjectHEAD             // +0
	LongValue    PyLongValue // +16 _PyLongValue long_value
}

// PyMemberDef mirrors the C struct PyMemberDef (size 40; pytypedefs.h:16).
type PyMemberDef struct {
	Name   uintptr // +0 const char * name
	Type   int32   // +8 int type
	Offset int64   // +16 Py_ssize_t offset
	Flags  int32   // +24 int flags
	Doc    uintptr // +32 const char * doc
}

// PyMethodDef mirrors the C struct PyMethodDef (size 32; pytypedefs.h:14).
type PyMethodDef struct {
	MlName  uintptr // +0 const char * ml_name
	MlMeth  uintptr // +8 PyCFunction ml_meth
	MlFlags int32   // +16 int ml_flags
	MlDoc   uintptr // +24 const char * ml_doc
}

// PyModuleDef mirrors the C struct PyModuleDef (size 104; pytypedefs.h:12).
type PyModuleDef struct {
	MBase     PyModuleDefBase // +0 PyModuleDef_Base m_base
	MName     uintptr         // +40 const char * m_name
	MDoc      uintptr         // +48 const char * m_doc
	MSize     int64           // +56 Py_ssize_t m_size
	MMethods  uintptr         // +64 PyMethodDef * m_methods
	MSlots    uintptr         // +72 PyModuleDef_Slot * m_slots
	MTraverse uintptr         // +80 traverseproc m_traverse
	MClear    uintptr         // +88 inquiry m_clear
	MFree     uintptr         // +96 freefunc m_free
}

// PyModuleDefSlot mirrors the C struct PyModuleDef_Slot (size 16; pytypedefs.h:13).
type PyModuleDefSlot struct {
	Slot  int32   // +0 int slot
	Value uintptr // +8 void * value
}

// PyObject mirrors the C struct _object (size 16; pytypedefs.h:18).
type PyObject struct {
	Field  [8]byte // +0 union _object::(anonymous at object.h:122:5)
	ObType uintptr // +8 PyTypeObject * ob_type
}

// PyThreadState mirrors the C struct _ts (size 832; pytypedefs.h:24).
type PyThreadState struct {
	Prev                         uintptr                 // +0 PyThreadState * prev
	Next                         uintptr                 // +8 PyThreadState * next
	Interp                       uintptr                 // +16 PyInterpreterState * interp
	EvalBreaker                  uint64                  // +24 uintptr_t eval_breaker
	Status                       [4]byte                 // +32 struct (unnamed at pystate.h:78:5) _status
	HoldsGil                     int32                   // +36 int holds_gil
	Whence                       int32                   // +40 int _whence
	State                        int32                   // +44 int state
	PyRecursionRemaining         int32                   // +48 int py_recursion_remaining
	PyRecursionLimit             int32                   // +52 int py_recursion_limit
	RecursionHeadroom            int32                   // +56 int recursion_headroom
	Tracing                      int32                   // +60 int tracing
	WhatEvent                    int32                   // +64 int what_event
	CurrentFrame                 uintptr                 // +72 struct _PyInterpreterFrame * current_frame
	CProfilefunc                 uintptr                 // +80 Py_tracefunc c_profilefunc
	CTracefunc                   uintptr                 // +88 Py_tracefunc c_tracefunc
	CProfileobj                  uintptr                 // +96 PyObject * c_profileobj
	CTraceobj                    uintptr                 // +104 PyObject * c_traceobj
	CurrentException             uintptr                 // +112 PyObject * current_exception
	ExcInfo                      uintptr                 // +120 _PyErr_StackItem * exc_info
	Dict                         uintptr                 // +128 PyObject * dict
	GilstateCounter              int32                   // +136 int gilstate_counter
	AsyncExc                     uintptr                 // +144 PyObject * async_exc
	ThreadId                     uint64                  // +152 unsigned long thread_id
	NativeThreadId               uint64                  // +160 unsigned long native_thread_id
	DeleteLater                  uintptr                 // +168 PyObject * delete_later
	CriticalSection              uint64                  // +176 uintptr_t critical_section
	CoroutineOriginTrackingDepth int32                   // +184 int coroutine_origin_tracking_depth
	AsyncGenFirstiter            uintptr                 // +192 PyObject * async_gen_firstiter
	AsyncGenFinalizer            uintptr                 // +200 PyObject * async_gen_finalizer
	Context                      uintptr                 // +208 PyObject * context
	ContextVer                   uint64                  // +216 uint64_t context_ver
	Id                           uint64                  // +224 uint64_t id
	DatastackChunk               uintptr                 // +232 _PyStackChunk * datastack_chunk
	DatastackTop                 uintptr                 // +240 PyObject ** datastack_top
	DatastackLimit               uintptr                 // +248 PyObject ** datastack_limit
	ExcState                     PyErrStackItem          // +256 _PyErr_StackItem exc_state
	CurrentExecutor              uintptr                 // +272 PyObject * current_executor
	DictGlobalVersion            uint64                  // +280 uint64_t dict_global_version
	ThreadingLocalKey            uintptr                 // +288 PyObject * threading_local_key
	ThreadingLocalSentinel       uintptr                 // +296 PyObject * threading_local_sentinel
	RemoteDebuggerSupport        PyRemoteDebuggerSupport // +304 _PyRemoteDebuggerSupport remote_debugger_support
	DatastackCachedChunk         uintptr                 // +824 _PyStackChunk * datastack_cached_chunk
}

// PyTypeObject mirrors the C struct _typeobject (size 416; pytypedefs.h:20).
type PyTypeObject struct {
	PyObjectVARHEAD            // +0
	TpName             uintptr // +24 const char * tp_name
	TpBasicsize        int64   // +32 Py_ssize_t tp_basicsize
	TpItemsize         int64   // +40 Py_ssize_t tp_itemsize
	TpDealloc          uintptr // +48 destructor tp_dealloc
	TpVectorcallOffset int64   // +56 Py_ssize_t tp_vectorcall_offset
	TpGetattr          uintptr // +64 getattrfunc tp_getattr
	TpSetattr          uintptr // +72 setattrfunc tp_setattr
	TpAsAsync          uintptr // +80 PyAsyncMethods * tp_as_async
	TpRepr             uintptr // +88 reprfunc tp_repr
	TpAsNumber         uintptr // +96 PyNumberMethods * tp_as_number
	TpAsSequence       uintptr // +104 PySequenceMethods * tp_as_sequence
	TpAsMapping        uintptr // +112 PyMappingMethods * tp_as_mapping
	TpHash             uintptr // +120 hashfunc tp_hash
	TpCall             uintptr // +128 ternaryfunc tp_call
	TpStr              uintptr // +136 reprfunc tp_str
	TpGetattro         uintptr // +144 getattrofunc tp_getattro
	TpSetattro         uintptr // +152 setattrofunc tp_setattro
	TpAsBuffer         uintptr // +160 PyBufferProcs * tp_as_buffer
	TpFlags            uint64  // +168 unsigned long tp_flags
	TpDoc              uintptr // +176 const char * tp_doc
	TpTraverse         uintptr // +184 traverseproc tp_traverse
	TpClear            uintptr // +192 inquiry tp_clear
	TpRichcompare      uintptr // +200 richcmpfunc tp_richcompare
	TpWeaklistoffset   int64   // +208 Py_ssize_t tp_weaklistoffset
	TpIter             uintptr // +216 getiterfunc tp_iter
	TpIternext         uintptr // +224 iternextfunc tp_iternext
	TpMethods          uintptr // +232 PyMethodDef * tp_methods
	TpMembers          uintptr // +240 PyMemberDef * tp_members
	TpGetset           uintptr // +248 PyGetSetDef * tp_getset
	TpBase             uintptr // +256 PyTypeObject * tp_base
	TpDict             uintptr // +264 PyObject * tp_dict
	TpDescrGet         uintptr // +272 descrgetfunc tp_descr_get
	TpDescrSet         uintptr // +280 descrsetfunc tp_descr_set
	TpDictoffset       int64   // +288 Py_ssize_t tp_dictoffset
	TpInit             uintptr // +296 initproc tp_init
	TpAlloc            uintptr // +304 allocfunc tp_alloc
	TpNew              uintptr // +312 newfunc tp_new
	TpFree             uintptr // +320 freefunc tp_free
	TpIsGc             uintptr // +328 inquiry tp_is_gc
	TpBases            uintptr // +336 PyObject * tp_bases
	TpMro              uintptr // +344 PyObject * tp_mro
	TpCache            uintptr // +352 PyObject * tp_cache
	TpSubclasses       uintptr // +360 void * tp_subclasses
	TpWeaklist         uintptr // +368 PyObject * tp_weaklist
	TpDel              uintptr // +376 destructor tp_del
	TpVersionTag       uint32  // +384 unsigned int tp_version_tag
	TpFinalize         uintptr // +392 destructor tp_finalize
	TpVectorcall       uintptr // +400 vectorcallfunc tp_vectorcall
	TpWatched          uint8   // +408 unsigned char tp_watched
	TpVersionsUsed     uint16  // +410 uint16_t tp_versions_used
}
