// Code generated by h2go; DO NOT EDIT.

package py31

// PyByteArrayObject mirrors the C struct PyByteArrayObject (size 48; bytearrayobject.h:22).
type PyByteArrayObject struct {
	PyObjectVARHEAD         // +0
	ObExports       int32   // +24 int ob_exports
	ObAlloc         int64   // +32 Py_ssize_t ob_alloc
	ObBytes         uintptr // +40 char * ob_bytes
}
