// Code generated by h2go; DO NOT EDIT.

package py31

// PyTryBlock mirrors the C struct PyTryBlock (size 12; frameobject.h:10).
type PyTryBlock struct {
	BType    int32 // +0 int b_type
	BHandler int32 // +4 int b_handler
	BLevel   int32 // +8 int b_level
}
