// Code generated by h2go; DO NOT EDIT.

package py31

// PyExceptionHEAD mirrors the struct-shaped C macro PyException_HEAD.
type PyExceptionHEAD struct {
	PyObjectHEAD         // +0
	Dict         uintptr // +16 PyObject * dict
	Args         uintptr // +24 PyObject * args
	Traceback    uintptr // +32 PyObject * traceback
	Context      uintptr // +40 PyObject * context
	Cause        uintptr // +48 PyObject * cause
}

// PyBaseExceptionObject mirrors the C struct PyBaseExceptionObject (size 56; pyerrors.h:14).
type PyBaseExceptionObject struct {
	PyExceptionHEAD // +0
}

// PyEnvironmentErrorObject mirrors the C struct PyEnvironmentErrorObject (size 80; pyerrors.h:42).
type PyEnvironmentErrorObject struct {
	PyExceptionHEAD         // +0
	Myerrno         uintptr // +56 PyObject * myerrno
	Strerror        uintptr // +64 PyObject * strerror
	Filename        uintptr // +72 PyObject * filename
}

// PySyntaxErrorObject mirrors the C struct PySyntaxErrorObject (size 104; pyerrors.h:18).
type PySyntaxErrorObject struct {
	PyExceptionHEAD          // +0
	Msg              uintptr // +56 PyObject * msg
	Filename         uintptr // +64 PyObject * filename
	Lineno           uintptr // +72 PyObject * lineno
	Offset           uintptr // +80 PyObject * offset
	Text             uintptr // +88 PyObject * text
	PrintFileAndLine uintptr // +96 PyObject * print_file_and_line
}

// PySystemExitObject mirrors the C struct PySystemExitObject (size 64; pyerrors.h:37).
type PySystemExitObject struct {
	PyExceptionHEAD         // +0
	Code            uintptr // +56 PyObject * code
}

// PyUnicodeErrorObject mirrors the C struct PyUnicodeErrorObject (size 96; pyerrors.h:28).
type PyUnicodeErrorObject struct {
	PyExceptionHEAD         // +0
	Encoding        uintptr // +56 PyObject * encoding
	Object          uintptr // +64 PyObject * object
	Start           int64   // +72 Py_ssize_t start
	End             int64   // +80 Py_ssize_t end
	Reason          uintptr // +88 PyObject * reason
}

// PyWindowsErrorObject mirrors the C struct PyWindowsErrorObject (size 88; pyerrors.h:50).
type PyWindowsErrorObject struct {
	PyExceptionHEAD         // +0
	Myerrno         uintptr // +56 PyObject * myerrno
	Strerror        uintptr // +64 PyObject * strerror
	Filename        uintptr // +72 PyObject * filename
	Winerror        uintptr // +80 PyObject * winerror
}
