// Code generated by h2go; DO NOT EDIT.

package py37

// PyCompilerFlags mirrors the C struct PyCompilerFlags (size 4; compile.h:27).
type PyCompilerFlags struct {
	CfFlags int32 // +0 int cf_flags
}

// PyFutureFeatures mirrors the C struct PyFutureFeatures (size 8; compile.h:34).
type PyFutureFeatures struct {
	FfFeatures int32 // +0 int ff_features
	FfLineno   int32 // +4 int ff_lineno
}
