// Code generated by h2go; DO NOT EDIT.

package py37

// PyDictObject mirrors the C struct PyDictObject (size 48; dictobject.h:23).
type PyDictObject struct {
	PyObjectHEAD         // +0
	MaUsed       int64   // +16 Py_ssize_t ma_used
	MaVersionTag uint64  // +24 uint64_t ma_version_tag
	MaKeys       uintptr // +32 PyDictKeysObject * ma_keys
	MaValues     uintptr // +40 PyObject ** ma_values
}

// PyDictViewObject mirrors the C struct _PyDictViewObject (size 24; dictobject.h:43).
type PyDictViewObject struct {
	PyObjectHEAD         // +0
	DvDict       uintptr // +16 PyDictObject * dv_dict
}
