// Code generated by h2go; DO NOT EDIT.

package py37

// PyGenObjectHEAD mirrors the struct-shaped C macro _PyGenObject_HEAD.
type PyGenObjectHEAD struct {
	PyObjectHEAD                 // +0
	GiFrame       uintptr        // +16 struct _frame * gi_frame
	GiRunning     int8           // +24 char gi_running
	GiCode        uintptr        // +32 PyObject * gi_code
	GiWeakreflist uintptr        // +40 PyObject * gi_weakreflist
	GiName        uintptr        // +48 PyObject * gi_name
	GiQualname    uintptr        // +56 PyObject * gi_qualname
	GiExcState    PyErrStackItem // +64 _PyErr_StackItem gi_exc_state
}

// PyAsyncGenObject mirrors the C struct PyAsyncGenObject (size 112; genobject.h:69).
type PyAsyncGenObject struct {
	PyObjectHEAD                 // +0
	AgFrame       uintptr        // +16 struct _frame * ag_frame
	AgRunning     int8           // +24 char ag_running
	AgCode        uintptr        // +32 PyObject * ag_code
	AgWeakreflist uintptr        // +40 PyObject * ag_weakreflist
	AgName        uintptr        // +48 PyObject * ag_name
	AgQualname    uintptr        // +56 PyObject * ag_qualname
	AgExcState    PyErrStackItem // +64 _PyErr_StackItem ag_exc_state
	AgFinalizer   uintptr        // +96 PyObject * ag_finalizer
	AgHooksInited int32          // +104 int ag_hooks_inited
	AgClosed      int32          // +108 int ag_closed
}

// PyCoroObject mirrors the C struct PyCoroObject (size 104; genobject.h:52).
type PyCoroObject struct {
	PyObjectHEAD                 // +0
	CrFrame       uintptr        // +16 struct _frame * cr_frame
	CrRunning     int8           // +24 char cr_running
	CrCode        uintptr        // +32 PyObject * cr_code
	CrWeakreflist uintptr        // +40 PyObject * cr_weakreflist
	CrName        uintptr        // +48 PyObject * cr_name
	CrQualname    uintptr        // +56 PyObject * cr_qualname
	CrExcState    PyErrStackItem // +64 _PyErr_StackItem cr_exc_state
	CrOrigin      uintptr        // +96 PyObject * cr_origin
}

// PyGenObject mirrors the C struct PyGenObject (size 96; genobject.h:31).
type PyGenObject struct {
	PyGenObjectHEAD // +0
}
