// Code generated by h2go; DO NOT EDIT.

package py37

// PyFrameObject mirrors the C struct _frame (size 368; pystate.h:21).
type PyFrameObject struct {
	PyObjectVARHEAD                // +0
	FBack           uintptr        // +24 struct _frame * f_back
	FCode           uintptr        // +32 PyCodeObject * f_code
	FBuiltins       uintptr        // +40 PyObject * f_builtins
	FGlobals        uintptr        // +48 PyObject * f_globals
	FLocals         uintptr        // +56 PyObject * f_locals
	FValuestack     uintptr        // +64 PyObject ** f_valuestack
	FStacktop       uintptr        // +72 PyObject ** f_stacktop
	FTrace          uintptr        // +80 PyObject * f_trace
	FTraceLines     int8           // +88 char f_trace_lines
	FTraceOpcodes   int8           // +89 char f_trace_opcodes
	FGen            uintptr        // +96 PyObject * f_gen
	FLasti          int32          // +104 int f_lasti
	FLineno         int32          // +108 int f_lineno
	FIblock         int32          // +112 int f_iblock
	FExecuting      int8           // +116 char f_executing
	FBlockstack     [20]PyTryBlock // +120 PyTryBlock[20] f_blockstack
	FLocalsplus     [1]uintptr     // +360 PyObject *[1] f_localsplus
}

// PyGILStateSTATE is the C enum enum PyGILState_STATE (size 4; pystate.h:374).
type PyGILStateSTATE uint32

// PyInterpreterState mirrors the C struct _is (size 2544; pystate.h:20).
type PyInterpreterState struct {
	Next               uintptr                 // +0 struct _is * next
	TstateHead         uintptr                 // +8 struct _ts * tstate_head
	Id                 int64                   // +16 int64_t id
	IdRefcount         int64                   // +24 int64_t id_refcount
	IdMutex            uintptr                 // +32 PyThread_type_lock id_mutex
	Modules            uintptr                 // +40 PyObject * modules
	ModulesByIndex     uintptr                 // +48 PyObject * modules_by_index
	Sysdict            uintptr                 // +56 PyObject * sysdict
	Builtins           uintptr                 // +64 PyObject * builtins
	Importlib          uintptr                 // +72 PyObject * importlib
	CheckInterval      int32                   // +80 int check_interval
	NumThreads         int64                   // +88 long num_threads
	PythreadStacksize  uint64                  // +96 size_t pythread_stacksize
	CodecSearchPath    uintptr                 // +104 PyObject * codec_search_path
	CodecSearchCache   uintptr                 // +112 PyObject * codec_search_cache
	CodecErrorRegistry uintptr                 // +120 PyObject * codec_error_registry
	CodecsInitialized  int32                   // +128 int codecs_initialized
	FscodecInitialized int32                   // +132 int fscodec_initialized
	CoreConfig         PyCoreConfig            // +136 _PyCoreConfig core_config
	Config             PyMainInterpreterConfig // +360 _PyMainInterpreterConfig config
	Dlopenflags        int32                   // +440 int dlopenflags
	BuiltinsCopy       uintptr                 // +448 PyObject * builtins_copy
	ImportFunc         uintptr                 // +456 PyObject * import_func
	EvalFrame          uintptr                 // +464 _PyFrameEvalFunction eval_frame
	CoExtraUserCount   int64                   // +472 Py_ssize_t co_extra_user_count
	CoExtraFreefuncs   [255]uintptr            // +480 freefunc[255] co_extra_freefuncs
	Pyexitfunc         uintptr                 // +2520 void (*)(PyObject *) pyexitfunc
	Pyexitmodule       uintptr                 // +2528 PyObject * pyexitmodule
	TstateNextUniqueId uint64                  // +2536 uint64_t tstate_next_unique_id
}

// PyThreadState mirrors the C struct _ts (size 280; pystate.h:19).
type PyThreadState struct {
	Prev                         uintptr        // +0 struct _ts * prev
	Next                         uintptr        // +8 struct _ts * next
	Interp                       uintptr        // +16 PyInterpreterState * interp
	Frame                        uintptr        // +24 struct _frame * frame
	RecursionDepth               int32          // +32 int recursion_depth
	Overflowed                   int8           // +36 char overflowed
	RecursionCritical            int8           // +37 char recursion_critical
	StackcheckCounter            int32          // +40 int stackcheck_counter
	Tracing                      int32          // +44 int tracing
	UseTracing                   int32          // +48 int use_tracing
	CProfilefunc                 uintptr        // +56 Py_tracefunc c_profilefunc
	CTracefunc                   uintptr        // +64 Py_tracefunc c_tracefunc
	CProfileobj                  uintptr        // +72 PyObject * c_profileobj
	CTraceobj                    uintptr        // +80 PyObject * c_traceobj
	CurexcType                   uintptr        // +88 PyObject * curexc_type
	CurexcValue                  uintptr        // +96 PyObject * curexc_value
	CurexcTraceback              uintptr        // +104 PyObject * curexc_traceback
	ExcState                     PyErrStackItem // +112 _PyErr_StackItem exc_state
	ExcInfo                      uintptr        // +144 _PyErr_StackItem * exc_info
	Dict                         uintptr        // +152 PyObject * dict
	GilstateCounter              int32          // +160 int gilstate_counter
	AsyncExc                     uintptr        // +168 PyObject * async_exc
	ThreadId                     uint64         // +176 unsigned long thread_id
	TrashDeleteNesting           int32          // +184 int trash_delete_nesting
	TrashDeleteLater             uintptr        // +192 PyObject * trash_delete_later
	OnDelete                     uintptr        // +200 void (*)(void *) on_delete
	OnDeleteData                 uintptr        // +208 void * on_delete_data
	CoroutineOriginTrackingDepth int32          // +216 int coroutine_origin_tracking_depth
	CoroutineWrapper             uintptr        // +224 PyObject * coroutine_wrapper
	InCoroutineWrapper           int32          // +232 int in_coroutine_wrapper
	AsyncGenFirstiter            uintptr        // +240 PyObject * async_gen_firstiter
	AsyncGenFinalizer            uintptr        // +248 PyObject * async_gen_finalizer
	Context                      uintptr        // +256 PyObject * context
	ContextVer                   uint64         // +264 uint64_t context_ver
	Id                           uint64         // +272 uint64_t id
}

// PyCoreConfig mirrors the C struct _PyCoreConfig (size 224; pystate.h:29).
type PyCoreConfig struct {
	InstallSignalHandlers int32   // +0 int install_signal_handlers
	IgnoreEnvironment     int32   // +4 int ignore_environment
	UseHashSeed           int32   // +8 int use_hash_seed
	HashSeed              uint64  // +16 unsigned long hash_seed
	Allocator             uintptr // +24 const char * allocator
	DevMode               int32   // +32 int dev_mode
	Faulthandler          int32   // +36 int faulthandler
	Tracemalloc           int32   // +40 int tracemalloc
	ImportTime            int32   // +44 int import_time
	ShowRefCount          int32   // +48 int show_ref_count
	ShowAllocCount        int32   // +52 int show_alloc_count
	DumpRefs              int32   // +56 int dump_refs
	MallocStats           int32   // +60 int malloc_stats
	CoerceCLocale         int32   // +64 int coerce_c_locale
	CoerceCLocaleWarn     int32   // +68 int coerce_c_locale_warn
	Utf8Mode              int32   // +72 int utf8_mode
	ProgramName           uintptr // +80 wchar_t * program_name
	Argc                  int32   // +88 int argc
	Argv                  uintptr // +96 wchar_t ** argv
	Program               uintptr // +104 wchar_t * program
	Nxoption              int32   // +112 int nxoption
	Xoptions              uintptr // +120 wchar_t ** xoptions
	Nwarnoption           int32   // +128 int nwarnoption
	Warnoptions           uintptr // +136 wchar_t ** warnoptions
	ModuleSearchPathEnv   uintptr // +144 wchar_t * module_search_path_env
	Home                  uintptr // +152 wchar_t * home
	NmoduleSearchPath     int32   // +160 int nmodule_search_path
	ModuleSearchPaths     uintptr // +168 wchar_t ** module_search_paths
	Executable            uintptr // +176 wchar_t * executable
	Prefix                uintptr // +184 wchar_t * prefix
	BasePrefix            uintptr // +192 wchar_t * base_prefix
	ExecPrefix            uintptr // +200 wchar_t * exec_prefix
	BaseExecPrefix        uintptr // +208 wchar_t * base_exec_prefix
	DisableImportlib      int32   // +216 int _disable_importlib
}

// PyErrStackItem mirrors the C struct _err_stackitem (size 32; pystate.h:198).
type PyErrStackItem struct {
	ExcType      uintptr // +0 PyObject * exc_type
	ExcValue     uintptr // +8 PyObject * exc_value
	ExcTraceback uintptr // +16 PyObject * exc_traceback
	PreviousItem uintptr // +24 struct _err_stackitem * previous_item
}

// PyMainInterpreterConfig mirrors the C struct _PyMainInterpreterConfig (size 80; pystate.h:96).
type PyMainInterpreterConfig struct {
	InstallSignalHandlers int32   // +0 int install_signal_handlers
	Argv                  uintptr // +8 PyObject * argv
	Executable            uintptr // +16 PyObject * executable
	Prefix                uintptr // +24 PyObject * prefix
	BasePrefix            uintptr // +32 PyObject * base_prefix
	ExecPrefix            uintptr // +40 PyObject * exec_prefix
	BaseExecPrefix        uintptr // +48 PyObject * base_exec_prefix
	Warnoptions           uintptr // +56 PyObject * warnoptions
	Xoptions              uintptr // +64 PyObject * xoptions
	ModuleSearchPath      uintptr // +72 PyObject * module_search_path
}
