// Code generated by h2go; DO NOT EDIT.

package py36

// PyObjectHEAD mirrors the struct-shaped C macro PyObject_HEAD.
type PyObjectHEAD struct {
	ObBase PyObject // +0 PyObject ob_base
}

// PyASCIIObject mirrors the C struct PyASCIIObject (size 48; unicodeobject.h:201).
type PyASCIIObject struct {
	PyObjectHEAD         // +0
	Length       int64   // +16 Py_ssize_t length
	Hash         int64   // +24 Py_hash_t hash
	State        [4]byte // +32 struct (unnamed at unicodeobject.h:278:5) state
	Wstr         uintptr // +40 wchar_t * wstr
}

// PyCompactUnicodeObject mirrors the C struct PyCompactUnicodeObject (size 72; unicodeobject.h:340).
type PyCompactUnicodeObject struct {
	Base       PyASCIIObject // +0 PyASCIIObject _base
	Utf8Length int64         // +48 Py_ssize_t utf8_length
	Utf8       uintptr       // +56 char * utf8
	WstrLength int64         // +64 Py_ssize_t wstr_length
}

// PyUnicodeObject mirrors the C struct PyUnicodeObject (size 80; unicodeobject.h:352).
type PyUnicodeObject struct {
	Base PyCompactUnicodeObject // +0 PyCompactUnicodeObject _base
	Data [8]byte                // +72 union (unnamed at unicodeobject.h:354:5) data
}

// PyUnicodeWriter mirrors the C struct _PyUnicodeWriter (size 56; unicodeobject.h:885).
type PyUnicodeWriter struct {
	Buffer       uintptr // +0 PyObject * buffer
	Data         uintptr // +8 void * data
	Kind         int32   // +16 enum PyUnicode_Kind kind
	Maxchar      uint32  // +20 Py_UCS4 maxchar
	Size         int64   // +24 Py_ssize_t size
	Pos          int64   // +32 Py_ssize_t pos
	MinLength    int64   // +40 Py_ssize_t min_length
	MinChar      uint32  // +48 Py_UCS4 min_char
	Overallocate uint8   // +52 unsigned char overallocate
	Readonly     uint8   // +53 unsigned char readonly
}
