// Code generated by h2go; DO NOT EDIT.

package py35

// PyDictObject mirrors the C struct PyDictObject (size 40; dictobject.h:23).
type PyDictObject struct {
	PyObjectHEAD         // +0
	MaUsed       int64   // +16 Py_ssize_t ma_used
	MaKeys       uintptr // +24 PyDictKeysObject * ma_keys
	MaValues     uintptr // +32 PyObject ** ma_values
}

// PyDictViewObject mirrors the C struct _PyDictViewObject (size 24; dictobject.h:30).
type PyDictViewObject struct {
	PyObjectHEAD         // +0
	DvDict       uintptr // +16 PyDictObject * dv_dict
}
