// Code generated by h2go; DO NOT EDIT.

package py35

// PyGenObjectHEAD mirrors the struct-shaped C macro _PyGenObject_HEAD.
type PyGenObjectHEAD struct {
	PyObjectHEAD          // +0
	GiFrame       uintptr // +16 struct _frame * gi_frame
	GiRunning     int8    // +24 char gi_running
	GiCode        uintptr // +32 PyObject * gi_code
	GiWeakreflist uintptr // +40 PyObject * gi_weakreflist
	GiName        uintptr // +48 PyObject * gi_name
	GiQualname    uintptr // +56 PyObject * gi_qualname
}

// PyCoroObject mirrors the C struct PyCoroObject (size 64; genobject.h:51).
type PyCoroObject struct {
	PyObjectHEAD          // +0
	CrFrame       uintptr // +16 struct _frame * cr_frame
	CrRunning     int8    // +24 char cr_running
	CrCode        uintptr // +32 PyObject * cr_code
	CrWeakreflist uintptr // +40 PyObject * cr_weakreflist
	CrName        uintptr // +48 PyObject * cr_name
	CrQualname    uintptr // +56 PyObject * cr_qualname
}

// PyGenObject mirrors the C struct PyGenObject (size 64; genobject.h:30).
type PyGenObject struct {
	PyGenObjectHEAD // +0
}
