// Code generated by h2go; DO NOT EDIT.

package py35

// PyTimeRoundT is the C enum enum _PyTime_round_t (size 4; pytime.h:34).
type PyTimeRoundT uint32

// PyClockInfoT mirrors the C struct _Py_clock_info_t (size 24; pytime.h:156).
type PyClockInfoT struct {
	Implementation uintptr // +0 const char * implementation
	Monotonic      int32   // +8 int monotonic
	Adjustable     int32   // +12 int adjustable
	Resolution     float64 // +16 double resolution
}
