// Code generated by h2go; DO NOT EDIT.

package py31

// PyMemoryViewObject mirrors the C struct PyMemoryViewObject (size 120; memoryobject.h:64).
type PyMemoryViewObject struct {
	PyObjectHEAD          // +0
	Base         uintptr  // +16 PyObject * base
	View         PyBuffer // +24 Py_buffer view
}
