// Code generated by h2go; DO NOT EDIT.

package py31

// PyFrameObject mirrors the C struct _frame (size 384; traceback.h:8).
type PyFrameObject struct {
	PyObjectVARHEAD                // +0
	FBack           uintptr        // +24 struct _frame * f_back
	FCode           uintptr        // +32 PyCodeObject * f_code
	FBuiltins       uintptr        // +40 PyObject * f_builtins
	FGlobals        uintptr        // +48 PyObject * f_globals
	FLocals         uintptr        // +56 PyObject * f_locals
	FValuestack     uintptr        // +64 PyObject ** f_valuestack
	FStacktop       uintptr        // +72 PyObject ** f_stacktop
	FTrace          uintptr        // +80 PyObject * f_trace
	FExcType        uintptr        // +88 PyObject * f_exc_type
	FExcValue       uintptr        // +96 PyObject * f_exc_value
	FExcTraceback   uintptr        // +104 PyObject * f_exc_traceback
	FTstate         uintptr        // +112 PyThreadState * f_tstate
	FLasti          int32          // +120 int f_lasti
	FLineno         int32          // +124 int f_lineno
	FIblock         int32          // +128 int f_iblock
	FBlockstack     [20]PyTryBlock // +132 PyTryBlock[20] f_blockstack
	FLocalsplus     [1]uintptr     // +376 PyObject *[1] f_localsplus
}

// PyTracebackObject mirrors the C struct _traceback (size 40; traceback.h:12).
type PyTracebackObject struct {
	PyObjectHEAD         // +0
	TbNext       uintptr // +16 struct _traceback * tb_next
	TbFrame      uintptr // +24 struct _frame * tb_frame
	TbLasti      int32   // +32 int tb_lasti
	TbLineno     int32   // +36 int tb_lineno
}
