// Code generated by h2go; DO NOT EDIT.

package py31

// PyObjectHEAD mirrors the struct-shaped C macro PyObject_HEAD.
type PyObjectHEAD struct {
	ObBase PyObject // +0 PyObject ob_base
}

// PyUnicodeObject mirrors the C struct PyUnicodeObject (size 56; unicodeobject.h:438).
type PyUnicodeObject struct {
	PyObjectHEAD         // +0
	Length       int64   // +16 Py_ssize_t length
	Str          uintptr // +24 Py_UNICODE * str
	Hash         int64   // +32 long hash
	State        int32   // +40 int state
	Defenc       uintptr // +48 PyObject * defenc
}
