// Code generated by h2go; DO NOT EDIT.

package py32

// PyModuleDef mirrors the C struct PyModuleDef (size 104; moduleobject.h:25).
type PyModuleDef struct {
	MBase     PyModuleDefBase // +0 PyModuleDef_Base m_base
	MName     uintptr         // +40 const char * m_name
	MDoc      uintptr         // +48 const char * m_doc
	MSize     int64           // +56 Py_ssize_t m_size
	MMethods  uintptr         // +64 PyMethodDef * m_methods
	MReload   uintptr         // +72 inquiry m_reload
	MTraverse uintptr         // +80 traverseproc m_traverse
	MClear    uintptr         // +88 inquiry m_clear
	MFree     uintptr         // +96 freefunc m_free
}

// PyModuleDefBase mirrors the C struct PyModuleDef_Base (size 40; moduleobject.h:28).
type PyModuleDefBase struct {
	PyObjectHEAD         // +0
	MInit        uintptr // +16 PyObject *(*)(void) m_init
	MIndex       int64   // +24 Py_ssize_t m_index
	MCopy        uintptr // +32 PyObject * m_copy
}
