// Code generated by h2go; DO NOT EDIT.

package py32

// PyTimeTimeval mirrors the C struct _PyTime_timeval (size 16; pytime.h:18).
type PyTimeTimeval struct {
	TvSec  int64 // +0 time_t tv_sec
	TvUsec int64 // +8 long tv_usec
}
