// Code generated by h2go; DO NOT EDIT.

package py32

// PySliceObject mirrors the C struct PySliceObject (size 40; sliceobject.h:22).
type PySliceObject struct {
	PyObjectHEAD         // +0
	Start        uintptr // +16 PyObject * start
	Stop         uintptr // +24 PyObject * stop
	Step         uintptr // +32 PyObject * step
}
