// Code generated by h2go; DO NOT EDIT.

package py34

// PyInstanceMethodObject mirrors the C struct PyInstanceMethodObject (size 24; classobject.h:37).
type PyInstanceMethodObject struct {
	PyObjectHEAD         // +0
	Func         uintptr // +16 PyObject * func
}

// PyMethodObject mirrors the C struct PyMethodObject (size 40; classobject.h:12).
type PyMethodObject struct {
	PyObjectHEAD          // +0
	ImFunc        uintptr // +16 PyObject * im_func
	ImSelf        uintptr // +24 PyObject * im_self
	ImWeakreflist uintptr // +32 PyObject * im_weakreflist
}
