// Code generated by h2go; DO NOT EDIT.

package py34

// PyGenObject mirrors the C struct PyGenObject (size 48; genobject.h:13).
type PyGenObject struct {
	PyObjectHEAD          // +0
	GiFrame       uintptr // +16 struct _frame * gi_frame
	GiRunning     int8    // +24 char gi_running
	GiCode        uintptr // +32 PyObject * gi_code
	GiWeakreflist uintptr // +40 PyObject * gi_weakreflist
}
