// Code generated by h2go; DO NOT EDIT.

package py34

// PyListObject mirrors the C struct PyListObject (size 40; listobject.h:23).
type PyListObject struct {
	PyObjectVARHEAD         // +0
	ObItem          uintptr // +24 PyObject ** ob_item
	Allocated       int64   // +32 Py_ssize_t allocated
}
