// Code generated by h2go; DO NOT EDIT.

package py34

// PyLongObject mirrors the C struct _longobject (size 32; longobject.h:10).
type PyLongObject struct {
	PyObjectVARHEAD           // +0
	ObDigit         [1]uint32 // +24 digit[1] ob_digit
}
