// Code generated by h2go; DO NOT EDIT.

package py34

import "unsafe"

// PyGCHead seals the C union _gc_head (size 24; objimpl.h:246).
type PyGCHead [24]byte

// Gc accesses the "gc" member.
func (u *PyGCHead) Gc() *_pygchead_gc { return (*_pygchead_gc)(unsafe.Pointer(u)) }

// Dummy accesses the "dummy" member.
func (u *PyGCHead) Dummy() *float64 { return (*float64)(unsafe.Pointer(u)) }

type _pygchead_gc struct {
	GcNext uintptr // +0 union _gc_head * gc_next
	GcPrev uintptr // +8 union _gc_head * gc_prev
	GcRefs int64   // +16 Py_ssize_t gc_refs
}

// PyObjectArenaAllocator mirrors the C struct PyObjectArenaAllocator (size 24; objimpl.h:202).
type PyObjectArenaAllocator struct {
	Ctx   uintptr // +0 void * ctx
	Alloc uintptr // +8 void *(*)(void *, size_t) alloc
	Free  uintptr // +16 void (*)(void *, void *, size_t) free
}
