// Code generated by h2go; DO NOT EDIT.

package py34

// PyFrameObject mirrors the C struct _frame (size 384; pystate.h:50).
type PyFrameObject struct {
	PyObjectVARHEAD                // +0
	FBack           uintptr        // +24 struct _frame * f_back
	FCode           uintptr        // +32 PyCodeObject * f_code
	FBuiltins       uintptr        // +40 PyObject * f_builtins
	FGlobals        uintptr        // +48 PyObject * f_globals
	FLocals         uintptr        // +56 PyObject * f_locals
	FValuestack     uintptr        // +64 PyObject ** f_valuestack
	FStacktop       uintptr        // +72 PyObject ** f_stacktop
	FTrace          uintptr        // +80 PyObject * f_trace
	FExcType        uintptr        // +88 PyObject * f_exc_type
	FExcValue       uintptr        // +96 PyObject * f_exc_value
	FExcTraceback   uintptr        // +104 PyObject * f_exc_traceback
	FGen            uintptr        // +112 PyObject * f_gen
	FLasti          int32          // +120 int f_lasti
	FLineno         int32          // +124 int f_lineno
	FIblock         int32          // +128 int f_iblock
	FExecuting      int8           // +132 char f_executing
	FBlockstack     [20]PyTryBlock // +136 PyTryBlock[20] f_blockstack
	FLocalsplus     [1]uintptr     // +376 PyObject *[1] f_localsplus
}

// PyGILStateSTATE is the C enum enum PyGILState_STATE (size 4; pystate.h:191).
type PyGILStateSTATE uint32

// PyInterpreterState mirrors the C struct _is (size 104; pystate.h:14).
type PyInterpreterState struct {
	Next               uintptr // +0 struct _is * next
	TstateHead         uintptr // +8 struct _ts * tstate_head
	Modules            uintptr // +16 PyObject * modules
	ModulesByIndex     uintptr // +24 PyObject * modules_by_index
	Sysdict            uintptr // +32 PyObject * sysdict
	Builtins           uintptr // +40 PyObject * builtins
	Importlib          uintptr // +48 PyObject * importlib
	CodecSearchPath    uintptr // +56 PyObject * codec_search_path
	CodecSearchCache   uintptr // +64 PyObject * codec_search_cache
	CodecErrorRegistry uintptr // +72 PyObject * codec_error_registry
	CodecsInitialized  int32   // +80 int codecs_initialized
	FscodecInitialized int32   // +84 int fscodec_initialized
	Dlopenflags        int32   // +88 int dlopenflags
	BuiltinsCopy       uintptr // +96 PyObject * builtins_copy
}

// PyThreadState mirrors the C struct _ts (size 192; pystate.h:13).
type PyThreadState struct {
	Prev               uintptr // +0 struct _ts * prev
	Next               uintptr // +8 struct _ts * next
	Interp             uintptr // +16 PyInterpreterState * interp
	Frame              uintptr // +24 struct _frame * frame
	RecursionDepth     int32   // +32 int recursion_depth
	Overflowed         int8    // +36 char overflowed
	RecursionCritical  int8    // +37 char recursion_critical
	Tracing            int32   // +40 int tracing
	UseTracing         int32   // +44 int use_tracing
	CProfilefunc       uintptr // +48 Py_tracefunc c_profilefunc
	CTracefunc         uintptr // +56 Py_tracefunc c_tracefunc
	CProfileobj        uintptr // +64 PyObject * c_profileobj
	CTraceobj          uintptr // +72 PyObject * c_traceobj
	CurexcType         uintptr // +80 PyObject * curexc_type
	CurexcValue        uintptr // +88 PyObject * curexc_value
	CurexcTraceback    uintptr // +96 PyObject * curexc_traceback
	ExcType            uintptr // +104 PyObject * exc_type
	ExcValue           uintptr // +112 PyObject * exc_value
	ExcTraceback       uintptr // +120 PyObject * exc_traceback
	Dict               uintptr // +128 PyObject * dict
	GilstateCounter    int32   // +136 int gilstate_counter
	AsyncExc           uintptr // +144 PyObject * async_exc
	ThreadId           int64   // +152 long thread_id
	TrashDeleteNesting int32   // +160 int trash_delete_nesting
	TrashDeleteLater   uintptr // +168 PyObject * trash_delete_later
	OnDelete           uintptr // +176 void (*)(void *) on_delete
	OnDeleteData       uintptr // +184 void * on_delete_data
}
