// Code generated by h2go; DO NOT EDIT.

package py34

// PySetObject mirrors the C struct _setobject (size 200; setobject.h:35).
type PySetObject struct {
	PyObjectHEAD             // +0
	Fill         int64       // +16 Py_ssize_t fill
	Used         int64       // +24 Py_ssize_t used
	Mask         int64       // +32 Py_ssize_t mask
	Table        uintptr     // +40 setentry * table
	Lookup       uintptr     // +48 setentry *(*)(PySetObject *, PyObject *, Py_hash_t) lookup
	Hash         int64       // +56 Py_hash_t hash
	Smalltable   [8]Setentry // +64 setentry[8] smalltable
	Weakreflist  uintptr     // +192 PyObject * weakreflist
}

// Setentry mirrors the C struct setentry (size 16; setobject.h:24).
type Setentry struct {
	Key  uintptr // +0 PyObject * key
	Hash int64   // +8 Py_hash_t hash
}
