// Code generated by h2go; DO NOT EDIT.

package py34

// PyMemAllocator mirrors the C struct PyMemAllocator (size 32; pymem.h:128).
type PyMemAllocator struct {
	Ctx     uintptr // +0 void * ctx
	Malloc  uintptr // +8 void *(*)(void *, size_t) malloc
	Realloc uintptr // +16 void *(*)(void *, void *, size_t) realloc
	Free    uintptr // +24 void (*)(void *, void *) free
}

// PyMemAllocatorDomain is the C enum enum PyMemAllocatorDomain (size 4; pymem.h:126).
type PyMemAllocatorDomain uint32
