// Code generated by h2go; DO NOT EDIT.

package py36

// PyMemAllocatorDomain is the C enum enum PyMemAllocatorDomain (size 4; pymem.h:175).
type PyMemAllocatorDomain uint32

// PyMemAllocatorEx mirrors the C struct PyMemAllocatorEx (size 40; pymem.h:177).
type PyMemAllocatorEx struct {
	Ctx     uintptr // +0 void * ctx
	Malloc  uintptr // +8 void *(*)(void *, size_t) malloc
	Calloc  uintptr // +16 void *(*)(void *, size_t, size_t) calloc
	Realloc uintptr // +24 void *(*)(void *, void *, size_t) realloc
	Free    uintptr // +32 void (*)(void *, void *) free
}
