// Code generated by h2go; DO NOT EDIT.

package py35

// PyFloatObject mirrors the C struct PyFloatObject (size 24; floatobject.h:15).
type PyFloatObject struct {
	PyObjectHEAD         // +0
	ObFval       float64 // +16 double ob_fval
}
