// Code generated by h2go; DO NOT EDIT.

package py35

// PyCFunctionObject mirrors the C struct PyCFunctionObject (size 48; methodobject.h:75).
type PyCFunctionObject struct {
	PyObjectHEAD         // +0
	MMl          uintptr // +16 PyMethodDef * m_ml
	MSelf        uintptr // +24 PyObject * m_self
	MModule      uintptr // +32 PyObject * m_module
	MWeakreflist uintptr // +40 PyObject * m_weakreflist
}
