// Code generated by h2go; DO NOT EDIT.

package py35

// PyCompilerFlags mirrors the C struct PyCompilerFlags (size 4; pythonrun.h:21).
type PyCompilerFlags struct {
	CfFlags int32 // +0 int cf_flags
}
