// Code generated by h2go; DO NOT EDIT.

package py312

// PyCFrame mirrors the C struct _PyCFrame (size 16; pystate.h:67).
type PyCFrame struct {
	CurrentFrame uintptr // +0 struct _PyInterpreterFrame * current_frame
	Previous     uintptr // +8 struct _PyCFrame * previous
}

// PyCrossInterpreterData mirrors the C struct _xid (size 40; pystate.h:388).
type PyCrossInterpreterData struct {
	Data      uintptr // +0 void * data
	Obj       uintptr // +8 PyObject * obj
	Interp    int64   // +16 int64_t interp
	NewObject uintptr // +24 xid_newobjectfunc new_object
	Free      uintptr // +32 xid_freefunc free
}

// PyErrStackItem mirrors the C struct _err_stackitem (size 16; pystate.h:83).
type PyErrStackItem struct {
	ExcValue     uintptr // +0 PyObject * exc_value
	PreviousItem uintptr // +8 struct _err_stackitem * previous_item
}

// PyStackChunk mirrors the C struct _stack_chunk (size 32; pystate.h:103).
type PyStackChunk struct {
	Previous uintptr    // +0 struct _stack_chunk * previous
	Size     uint64     // +8 size_t size
	Top      uint64     // +16 size_t top
	Data     [1]uintptr // +24 PyObject *[1] data
}
