// Code generated by h2go; DO NOT EDIT.

package py312

// PyArgParser mirrors the C struct _PyArg_Parser (size 72; modsupport.h:53).
type PyArgParser struct {
	Initialized int32   // +0 int initialized
	Format      uintptr // +8 const char * format
	Keywords    uintptr // +16 const char *const * keywords
	Fname       uintptr // +24 const char * fname
	CustomMsg   uintptr // +32 const char * custom_msg
	Pos         int32   // +40 int pos
	Min         int32   // +44 int min
	Max         int32   // +48 int max
	Kwtuple     uintptr // +56 PyObject * kwtuple
	Next        uintptr // +64 struct _PyArg_Parser * next
}
