// Code generated by h2go; DO NOT EDIT.

package py312

// PyCOMMONFIELDS mirrors the struct-shaped C macro _Py_COMMON_FIELDS.
type PyCOMMONFIELDS struct {
	FcGlobals    uintptr // +0 PyObject * fc_globals
	FcBuiltins   uintptr // +8 PyObject * fc_builtins
	FcName       uintptr // +16 PyObject * fc_name
	FcQualname   uintptr // +24 PyObject * fc_qualname
	FcCode       uintptr // +32 PyObject * fc_code
	FcDefaults   uintptr // +40 PyObject * fc_defaults
	FcKwdefaults uintptr // +48 PyObject * fc_kwdefaults
	FcClosure    uintptr // +56 PyObject * fc_closure
}

// PyFrameConstructor mirrors the C struct PyFrameConstructor (size 64; funcobject.h:21).
type PyFrameConstructor struct {
	PyCOMMONFIELDS // +0
}

// PyFunctionObject mirrors the C struct PyFunctionObject (size 144; funcobject.h:36).
type PyFunctionObject struct {
	PyObjectHEAD            // +0
	FuncGlobals     uintptr // +16 PyObject * func_globals
	FuncBuiltins    uintptr // +24 PyObject * func_builtins
	FuncName        uintptr // +32 PyObject * func_name
	FuncQualname    uintptr // +40 PyObject * func_qualname
	FuncCode        uintptr // +48 PyObject * func_code
	FuncDefaults    uintptr // +56 PyObject * func_defaults
	FuncKwdefaults  uintptr // +64 PyObject * func_kwdefaults
	FuncClosure     uintptr // +72 PyObject * func_closure
	FuncDoc         uintptr // +80 PyObject * func_doc
	FuncDict        uintptr // +88 PyObject * func_dict
	FuncWeakreflist uintptr // +96 PyObject * func_weakreflist
	FuncModule      uintptr // +104 PyObject * func_module
	FuncAnnotations uintptr // +112 PyObject * func_annotations
	FuncTypeparams  uintptr // +120 PyObject * func_typeparams
	Vectorcall      uintptr // +128 vectorcallfunc vectorcall
	FuncVersion     uint32  // +136 uint32_t func_version
}

// PyFunctionWatchEvent is the C enum enum PyFunction_WatchEvent (size 4; funcobject.h:148).
type PyFunctionWatchEvent uint32
