// Code generated by h2go; DO NOT EDIT.

package py312

// PyComplexObject mirrors the C struct PyComplexObject (size 32; complexobject.h:26).
type PyComplexObject struct {
	PyObjectHEAD           // +0
	Cval         PyComplex // +16 Py_complex cval
}

// PyComplex mirrors the C struct Py_complex (size 16; complexobject.h:5).
type PyComplex struct {
	Real float64 // +0 double real
	Imag float64 // +8 double imag
}
