// Code generated by h2go; DO NOT EDIT.

package py312

// PySendResult is the C enum enum PySendResult (size 4; object.h:876).
type PySendResult int32

// PyTypeSlot mirrors the C struct PyType_Slot (size 16; object.h:342).
type PyTypeSlot struct {
	Slot  int32   // +0 int slot
	Pfunc uintptr // +8 void * pfunc
}

// PyTypeSpec mirrors the C struct PyType_Spec (size 32; object.h:347).
type PyTypeSpec struct {
	Name      uintptr // +0 const char * name
	Basicsize int32   // +8 int basicsize
	Itemsize  int32   // +12 int itemsize
	Flags     uint32  // +16 unsigned int flags
	Slots     uintptr // +24 PyType_Slot * slots
}

// PyVarObject mirrors the C struct PyVarObject (size 24; object.h:196).
type PyVarObject struct {
	PyObjectHEAD       // +0
	ObSize       int64 // +16 Py_ssize_t ob_size
}
