// Code generated by h2go; DO NOT EDIT.

package py39

// PyConfig mirrors the C struct PyConfig (size 392; initconfig.h:133).
type PyConfig struct {
	ConfigInit            int32            // +0 int _config_init
	Isolated              int32            // +4 int isolated
	UseEnvironment        int32            // +8 int use_environment
	DevMode               int32            // +12 int dev_mode
	InstallSignalHandlers int32            // +16 int install_signal_handlers
	UseHashSeed           int32            // +20 int use_hash_seed
	HashSeed              uint64           // +24 unsigned long hash_seed
	Faulthandler          int32            // +32 int faulthandler
	UsePegParser          int32            // +36 int _use_peg_parser
	Tracemalloc           int32            // +40 int tracemalloc
	ImportTime            int32            // +44 int import_time
	ShowRefCount          int32            // +48 int show_ref_count
	DumpRefs              int32            // +52 int dump_refs
	MallocStats           int32            // +56 int malloc_stats
	FilesystemEncoding    uintptr          // +64 wchar_t * filesystem_encoding
	FilesystemErrors      uintptr          // +72 wchar_t * filesystem_errors
	PycachePrefix         uintptr          // +80 wchar_t * pycache_prefix
	ParseArgv             int32            // +88 int parse_argv
	Argv                  PyWideStringList // +96 PyWideStringList argv
	ProgramName           uintptr          // +112 wchar_t * program_name
	Xoptions              PyWideStringList // +120 PyWideStringList xoptions
	Warnoptions           PyWideStringList // +136 PyWideStringList warnoptions
	SiteImport            int32            // +152 int site_import
	BytesWarning          int32            // +156 int bytes_warning
	Inspect               int32            // +160 int inspect
	Interactive           int32            // +164 int interactive
	OptimizationLevel     int32            // +168 int optimization_level
	ParserDebug           int32            // +172 int parser_debug
	WriteBytecode         int32            // +176 int write_bytecode
	Verbose               int32            // +180 int verbose
	Quiet                 int32            // +184 int quiet
	UserSiteDirectory     int32            // +188 int user_site_directory
	ConfigureCStdio       int32            // +192 int configure_c_stdio
	BufferedStdio         int32            // +196 int buffered_stdio
	StdioEncoding         uintptr          // +200 wchar_t * stdio_encoding
	StdioErrors           uintptr          // +208 wchar_t * stdio_errors
	CheckHashPycsMode     uintptr          // +216 wchar_t * check_hash_pycs_mode
	PathconfigWarnings    int32            // +224 int pathconfig_warnings
	PythonpathEnv         uintptr          // +232 wchar_t * pythonpath_env
	Home                  uintptr          // +240 wchar_t * home
	ModuleSearchPathsSet  int32            // +248 int module_search_paths_set
	ModuleSearchPaths     PyWideStringList // +256 PyWideStringList module_search_paths
	Executable            uintptr          // +272 wchar_t * executable
	BaseExecutable        uintptr          // +280 wchar_t * base_executable
	Prefix                uintptr          // +288 wchar_t * prefix
	BasePrefix            uintptr          // +296 wchar_t * base_prefix
	ExecPrefix            uintptr          // +304 wchar_t * exec_prefix
	BaseExecPrefix        uintptr          // +312 wchar_t * base_exec_prefix
	Platlibdir            uintptr          // +320 wchar_t * platlibdir
	SkipSourceFirstLine   int32            // +328 int skip_source_first_line
	RunCommand            uintptr          // +336 wchar_t * run_command
	RunModule             uintptr          // +344 wchar_t * run_module
	RunFilename           uintptr          // +352 wchar_t * run_filename
	InstallImportlib      int32            // +360 int _install_importlib
	InitMain              int32            // +364 int _init_main
	IsolatedInterpreter   int32            // +368 int _isolated_interpreter
	OrigArgv              PyWideStringList // +376 PyWideStringList _orig_argv
}

// PyPreConfig mirrors the C struct PyPreConfig (size 40; initconfig.h:47).
type PyPreConfig struct {
	ConfigInit        int32 // +0 int _config_init
	ParseArgv         int32 // +4 int parse_argv
	Isolated          int32 // +8 int isolated
	UseEnvironment    int32 // +12 int use_environment
	ConfigureLocale   int32 // +16 int configure_locale
	CoerceCLocale     int32 // +20 int coerce_c_locale
	CoerceCLocaleWarn int32 // +24 int coerce_c_locale_warn
	Utf8Mode          int32 // +28 int utf8_mode
	DevMode           int32 // +32 int dev_mode
	Allocator         int32 // +36 int allocator
}

// PyStatus mirrors the C struct PyStatus (size 32; initconfig.h:10).
type PyStatus struct {
	Type     int32   // +0 enum (unnamed at initconfig.h:11:5) _type
	Func     uintptr // +8 const char * func
	ErrMsg   uintptr // +16 const char * err_msg
	Exitcode int32   // +24 int exitcode
}

// PyWideStringList mirrors the C struct PyWideStringList (size 16; initconfig.h:31).
type PyWideStringList struct {
	Length int64   // +0 Py_ssize_t length
	Items  uintptr // +8 wchar_t ** items
}
