// Code generated by h2go; DO NOT EDIT.

package py39

// PyAddrPair mirrors the C struct _addr_pair (size 8; code.h:138).
type PyAddrPair struct {
	ApLower int32 // +0 int ap_lower
	ApUpper int32 // +4 int ap_upper
}
