// Code generated by h2go; DO NOT EDIT.

package py39

// PyFrameObject mirrors the C struct _frame (size 368; pyframe.h:12).
type PyFrameObject struct {
	PyObjectVARHEAD                // +0
	FBack           uintptr        // +24 struct _frame * f_back
	FCode           uintptr        // +32 PyCodeObject * f_code
	FBuiltins       uintptr        // +40 PyObject * f_builtins
	FGlobals        uintptr        // +48 PyObject * f_globals
	FLocals         uintptr        // +56 PyObject * f_locals
	FValuestack     uintptr        // +64 PyObject ** f_valuestack
	FStacktop       uintptr        // +72 PyObject ** f_stacktop
	FTrace          uintptr        // +80 PyObject * f_trace
	FTraceLines     int8           // +88 char f_trace_lines
	FTraceOpcodes   int8           // +89 char f_trace_opcodes
	FGen            uintptr        // +96 PyObject * f_gen
	FLasti          int32          // +104 int f_lasti
	FLineno         int32          // +108 int f_lineno
	FIblock         int32          // +112 int f_iblock
	FExecuting      int8           // +116 char f_executing
	FBlockstack     [20]PyTryBlock // +120 PyTryBlock[20] f_blockstack
	FLocalsplus     [1]uintptr     // +360 PyObject *[1] f_localsplus
}
