// Code generated by h2go; DO NOT EDIT.

package py33

// PyAtomicAddress mirrors the C struct _Py_atomic_address (size 8; pyatomic.h:31).
type PyAtomicAddress struct {
	Value uintptr // +0 void * _value
}

// PyAtomicInt mirrors the C struct _Py_atomic_int (size 4; pyatomic.h:35).
type PyAtomicInt struct {
	Value int32 // +0 int _value
}

// PyMemoryOrder is the C enum enum _Py_memory_order (size 4; pyatomic.h:29).
type PyMemoryOrder uint32
