// Code generated by h2go; DO NOT EDIT.

package py33

// PyTimeTimeval mirrors the C struct _PyTime_timeval (size 16; pytime.h:19).
type PyTimeTimeval struct {
	TvSec  int64 // +0 time_t tv_sec
	TvUsec int32 // +8 long tv_usec
}

// PyClockInfoT mirrors the C struct _Py_clock_info_t (size 24; pytime.h:26).
type PyClockInfoT struct {
	Implementation uintptr // +0 const char * implementation
	Monotonic      int32   // +8 int monotonic
	Adjustable     int32   // +12 int adjustable
	Resolution     float64 // +16 double resolution
}
