// Code generated by h2go; DO NOT EDIT.

package py39

// PyCodeObject mirrors the C struct PyCodeObject (size 176; code.h:9).
type PyCodeObject struct {
	PyObjectHEAD              // +0
	CoArgcount        int32   // +16 int co_argcount
	CoPosonlyargcount int32   // +20 int co_posonlyargcount
	CoKwonlyargcount  int32   // +24 int co_kwonlyargcount
	CoNlocals         int32   // +28 int co_nlocals
	CoStacksize       int32   // +32 int co_stacksize
	CoFlags           int32   // +36 int co_flags
	CoFirstlineno     int32   // +40 int co_firstlineno
	CoCode            uintptr // +48 PyObject * co_code
	CoConsts          uintptr // +56 PyObject * co_consts
	CoNames           uintptr // +64 PyObject * co_names
	CoVarnames        uintptr // +72 PyObject * co_varnames
	CoFreevars        uintptr // +80 PyObject * co_freevars
	CoCellvars        uintptr // +88 PyObject * co_cellvars
	CoCell2arg        uintptr // +96 Py_ssize_t * co_cell2arg
	CoFilename        uintptr // +104 PyObject * co_filename
	CoName            uintptr // +112 PyObject * co_name
	CoLnotab          uintptr // +120 PyObject * co_lnotab
	CoZombieframe     uintptr // +128 void * co_zombieframe
	CoWeakreflist     uintptr // +136 PyObject * co_weakreflist
	CoExtra           uintptr // +144 void * co_extra
	CoOpcacheMap      uintptr // +152 unsigned char * co_opcache_map
	CoOpcache         uintptr // +160 _PyOpcache * co_opcache
	CoOpcacheFlag     int32   // +168 int co_opcache_flag
	CoOpcacheSize     uint8   // +172 unsigned char co_opcache_size
}
