// Code generated by h2go; DO NOT EDIT.

package py39

// PyCompilerFlags mirrors the C struct PyCompilerFlags (size 8; compile.h:37).
type PyCompilerFlags struct {
	CfFlags          int32 // +0 int cf_flags
	CfFeatureVersion int32 // +4 int cf_feature_version
}

// PyFutureFeatures mirrors the C struct PyFutureFeatures (size 8; compile.h:48).
type PyFutureFeatures struct {
	FfFeatures int32 // +0 int ff_features
	FfLineno   int32 // +4 int ff_lineno
}

// PyASTOptimizeState mirrors the C struct _PyASTOptimizeState (size 8; compile.h:94).
type PyASTOptimizeState struct {
	Optimize   int32 // +0 int optimize
	FfFeatures int32 // +4 int ff_features
}
