// Code generated by h2go; DO NOT EDIT.

package py39

// PyTracebackObject mirrors the C struct _traceback (size 40; traceback.h:9).
type PyTracebackObject struct {
	PyObjectHEAD         // +0
	TbNext       uintptr // +16 struct _traceback * tb_next
	TbFrame      uintptr // +24 PyFrameObject * tb_frame
	TbLasti      int32   // +32 int tb_lasti
	TbLineno     int32   // +36 int tb_lineno
}
