// Code generated by h2go; DO NOT EDIT.

package py39

import "unsafe"

// PyHashFuncDef mirrors the C struct PyHash_FuncDef (size 24; pyhash.h:89).
type PyHashFuncDef struct {
	Hash     uintptr // +0 Py_hash_t (*const)(const void *, Py_ssize_t) hash
	Name     uintptr // +8 const char * name
	HashBits int32   // +16 const int hash_bits
	SeedBits int32   // +20 const int seed_bits
}

// PyHashSecretT seals the C union _Py_HashSecret_t (size 24; pyhash.h:56).
type PyHashSecretT [24]byte

// Uc accesses the "uc" member.
func (u *PyHashSecretT) Uc() *[24]uint8 { return (*[24]uint8)(unsafe.Pointer(u)) }

// Fnv accesses the "fnv" member.
func (u *PyHashSecretT) Fnv() *_pyhashsecrett_fnv { return (*_pyhashsecrett_fnv)(unsafe.Pointer(u)) }

// Siphash accesses the "siphash" member.
func (u *PyHashSecretT) Siphash() *_pyhashsecrett_siphash {
	return (*_pyhashsecrett_siphash)(unsafe.Pointer(u))
}

// Djbx33a accesses the "djbx33a" member.
func (u *PyHashSecretT) Djbx33a() *_pyhashsecrett_djbx33a {
	return (*_pyhashsecrett_djbx33a)(unsafe.Pointer(u))
}

// Expat accesses the "expat" member.
func (u *PyHashSecretT) Expat() *_pyhashsecrett_expat {
	return (*_pyhashsecrett_expat)(unsafe.Pointer(u))
}

type _pyhashsecrett_fnv struct {
	Prefix int64 // +0 Py_hash_t prefix
	Suffix int64 // +8 Py_hash_t suffix
}

type _pyhashsecrett_siphash struct {
	K0 uint64 // +0 uint64_t k0
	K1 uint64 // +8 uint64_t k1
}

type _pyhashsecrett_djbx33a struct {
	Padding [16]uint8 // +0 unsigned char[16] padding
	Suffix  int64     // +16 Py_hash_t suffix
}

type _pyhashsecrett_expat struct {
	Padding  [16]uint8 // +0 unsigned char[16] padding
	Hashsalt int64     // +16 Py_hash_t hashsalt
}
