// Code generated by h2go; DO NOT EDIT.

package py310

// PyCodeAddressRange mirrors the C struct _line_offsets (size 40; code.h:144).
type PyCodeAddressRange struct {
	ArStart int32    // +0 int ar_start
	ArEnd   int32    // +4 int ar_end
	ArLine  int32    // +8 int ar_line
	Opaque  [24]byte // +16 struct _opaque opaque
}
