// Code generated by h2go; DO NOT EDIT.

package py310

// PyConfig mirrors the C struct PyConfig (size 400; initconfig.h:134).
type PyConfig struct {
	ConfigInit            int32            // +0 int _config_init
	Isolated              int32            // +4 int isolated
	UseEnvironment        int32            // +8 int use_environment
	DevMode               int32            // +12 int dev_mode
	InstallSignalHandlers int32            // +16 int install_signal_handlers
	UseHashSeed           int32            // +20 int use_hash_seed
	HashSeed              uint32           // +24 unsigned long hash_seed
	Faulthandler          int32            // +28 int faulthandler
	Tracemalloc           int32            // +32 int tracemalloc
	ImportTime            int32            // +36 int import_time
	ShowRefCount          int32            // +40 int show_ref_count
	DumpRefs              int32            // +44 int dump_refs
	MallocStats           int32            // +48 int malloc_stats
	FilesystemEncoding    uintptr          // +56 wchar_t * filesystem_encoding
	FilesystemErrors      uintptr          // +64 wchar_t * filesystem_errors
	PycachePrefix         uintptr          // +72 wchar_t * pycache_prefix
	ParseArgv             int32            // +80 int parse_argv
	OrigArgv              PyWideStringList // +88 PyWideStringList orig_argv
	Argv                  PyWideStringList // +104 PyWideStringList argv
	Xoptions              PyWideStringList // +120 PyWideStringList xoptions
	Warnoptions           PyWideStringList // +136 PyWideStringList warnoptions
	SiteImport            int32            // +152 int site_import
	BytesWarning          int32            // +156 int bytes_warning
	WarnDefaultEncoding   int32            // +160 int warn_default_encoding
	Inspect               int32            // +164 int inspect
	Interactive           int32            // +168 int interactive
	OptimizationLevel     int32            // +172 int optimization_level
	ParserDebug           int32            // +176 int parser_debug
	WriteBytecode         int32            // +180 int write_bytecode
	Verbose               int32            // +184 int verbose
	Quiet                 int32            // +188 int quiet
	UserSiteDirectory     int32            // +192 int user_site_directory
	ConfigureCStdio       int32            // +196 int configure_c_stdio
	BufferedStdio         int32            // +200 int buffered_stdio
	StdioEncoding         uintptr          // +208 wchar_t * stdio_encoding
	StdioErrors           uintptr          // +216 wchar_t * stdio_errors
	LegacyWindowsStdio    int32            // +224 int legacy_windows_stdio
	CheckHashPycsMode     uintptr          // +232 wchar_t * check_hash_pycs_mode
	PathconfigWarnings    int32            // +240 int pathconfig_warnings
	ProgramName           uintptr          // +248 wchar_t * program_name
	PythonpathEnv         uintptr          // +256 wchar_t * pythonpath_env
	Home                  uintptr          // +264 wchar_t * home
	Platlibdir            uintptr          // +272 wchar_t * platlibdir
	ModuleSearchPathsSet  int32            // +280 int module_search_paths_set
	ModuleSearchPaths     PyWideStringList // +288 PyWideStringList module_search_paths
	Executable            uintptr          // +304 wchar_t * executable
	BaseExecutable        uintptr          // +312 wchar_t * base_executable
	Prefix                uintptr          // +320 wchar_t * prefix
	BasePrefix            uintptr          // +328 wchar_t * base_prefix
	ExecPrefix            uintptr          // +336 wchar_t * exec_prefix
	BaseExecPrefix        uintptr          // +344 wchar_t * base_exec_prefix
	SkipSourceFirstLine   int32            // +352 int skip_source_first_line
	RunCommand            uintptr          // +360 wchar_t * run_command
	RunModule             uintptr          // +368 wchar_t * run_module
	RunFilename           uintptr          // +376 wchar_t * run_filename
	InstallImportlib      int32            // +384 int _install_importlib
	InitMain              int32            // +388 int _init_main
	IsolatedInterpreter   int32            // +392 int _isolated_interpreter
}

// PyPreConfig mirrors the C struct PyPreConfig (size 44; initconfig.h:47).
type PyPreConfig struct {
	ConfigInit              int32 // +0 int _config_init
	ParseArgv               int32 // +4 int parse_argv
	Isolated                int32 // +8 int isolated
	UseEnvironment          int32 // +12 int use_environment
	ConfigureLocale         int32 // +16 int configure_locale
	CoerceCLocale           int32 // +20 int coerce_c_locale
	CoerceCLocaleWarn       int32 // +24 int coerce_c_locale_warn
	LegacyWindowsFsEncoding int32 // +28 int legacy_windows_fs_encoding
	Utf8Mode                int32 // +32 int utf8_mode
	DevMode                 int32 // +36 int dev_mode
	Allocator               int32 // +40 int allocator
}

// PyStatus mirrors the C struct PyStatus (size 32; initconfig.h:10).
type PyStatus struct {
	Type     int32   // +0 enum (unnamed at initconfig.h:11:5) _type
	Func     uintptr // +8 const char * func
	ErrMsg   uintptr // +16 const char * err_msg
	Exitcode int32   // +24 int exitcode
}

// PyWideStringList mirrors the C struct PyWideStringList (size 16; initconfig.h:31).
type PyWideStringList struct {
	Length int64   // +0 Py_ssize_t length
	Items  uintptr // +8 wchar_t ** items
}
