// Code generated by h2go; DO NOT EDIT.

package py310

// PyObjectVARHEAD mirrors the struct-shaped C macro PyObject_VAR_HEAD.
type PyObjectVARHEAD struct {
	ObBase PyVarObject // +0 PyVarObject ob_base
}

// PyObject mirrors the C struct _object (size 16; object.h:105).
type PyObject struct {
	ObRefcnt int64   // +0 Py_ssize_t ob_refcnt
	ObType   uintptr // +8 PyTypeObject * ob_type
}

// PySendResult is the C enum enum PySendResult (size 4; object.h:639).
type PySendResult int32

// PyTypeObject mirrors the C struct _typeobject (size 408; object.h:66).
type PyTypeObject struct {
	PyObjectVARHEAD            // +0
	TpName             uintptr // +24 const char * tp_name
	TpBasicsize        int64   // +32 Py_ssize_t tp_basicsize
	TpItemsize         int64   // +40 Py_ssize_t tp_itemsize
	TpDealloc          uintptr // +48 destructor tp_dealloc
	TpVectorcallOffset int64   // +56 Py_ssize_t tp_vectorcall_offset
	TpGetattr          uintptr // +64 getattrfunc tp_getattr
	TpSetattr          uintptr // +72 setattrfunc tp_setattr
	TpAsAsync          uintptr // +80 PyAsyncMethods * tp_as_async
	TpRepr             uintptr // +88 reprfunc tp_repr
	TpAsNumber         uintptr // +96 PyNumberMethods * tp_as_number
	TpAsSequence       uintptr // +104 PySequenceMethods * tp_as_sequence
	TpAsMapping        uintptr // +112 PyMappingMethods * tp_as_mapping
	TpHash             uintptr // +120 hashfunc tp_hash
	TpCall             uintptr // +128 ternaryfunc tp_call
	TpStr              uintptr // +136 reprfunc tp_str
	TpGetattro         uintptr // +144 getattrofunc tp_getattro
	TpSetattro         uintptr // +152 setattrofunc tp_setattro
	TpAsBuffer         uintptr // +160 PyBufferProcs * tp_as_buffer
	TpFlags            uint32  // +168 unsigned long tp_flags
	TpDoc              uintptr // +176 const char * tp_doc
	TpTraverse         uintptr // +184 traverseproc tp_traverse
	TpClear            uintptr // +192 inquiry tp_clear
	TpRichcompare      uintptr // +200 richcmpfunc tp_richcompare
	TpWeaklistoffset   int64   // +208 Py_ssize_t tp_weaklistoffset
	TpIter             uintptr // +216 getiterfunc tp_iter
	TpIternext         uintptr // +224 iternextfunc tp_iternext
	TpMethods          uintptr // +232 struct PyMethodDef * tp_methods
	TpMembers          uintptr // +240 struct PyMemberDef * tp_members
	TpGetset           uintptr // +248 struct PyGetSetDef * tp_getset
	TpBase             uintptr // +256 struct _typeobject * tp_base
	TpDict             uintptr // +264 PyObject * tp_dict
	TpDescrGet         uintptr // +272 descrgetfunc tp_descr_get
	TpDescrSet         uintptr // +280 descrsetfunc tp_descr_set
	TpDictoffset       int64   // +288 Py_ssize_t tp_dictoffset
	TpInit             uintptr // +296 initproc tp_init
	TpAlloc            uintptr // +304 allocfunc tp_alloc
	TpNew              uintptr // +312 newfunc tp_new
	TpFree             uintptr // +320 freefunc tp_free
	TpIsGc             uintptr // +328 inquiry tp_is_gc
	TpBases            uintptr // +336 PyObject * tp_bases
	TpMro              uintptr // +344 PyObject * tp_mro
	TpCache            uintptr // +352 PyObject * tp_cache
	TpSubclasses       uintptr // +360 PyObject * tp_subclasses
	TpWeaklist         uintptr // +368 PyObject * tp_weaklist
	TpDel              uintptr // +376 destructor tp_del
	TpVersionTag       uint32  // +384 unsigned int tp_version_tag
	TpFinalize         uintptr // +392 destructor tp_finalize
	TpVectorcall       uintptr // +400 vectorcallfunc tp_vectorcall
}

// PyTypeSlot mirrors the C struct PyType_Slot (size 16; object.h:217).
type PyTypeSlot struct {
	Slot  int32   // +0 int slot
	Pfunc uintptr // +8 void * pfunc
}

// PyTypeSpec mirrors the C struct PyType_Spec (size 32; object.h:222).
type PyTypeSpec struct {
	Name      uintptr // +0 const char * name
	Basicsize int32   // +8 int basicsize
	Itemsize  int32   // +12 int itemsize
	Flags     uint32  // +16 unsigned int flags
	Slots     uintptr // +24 PyType_Slot * slots
}

// PyVarObject mirrors the C struct PyVarObject (size 24; object.h:115).
type PyVarObject struct {
	PyObjectHEAD       // +0
	ObSize       int64 // +16 Py_ssize_t ob_size
}
