// Code generated by h2go; DO NOT EDIT.

package py313

// PyConfig mirrors the C struct PyConfig (size 448; initconfig.h:134).
type PyConfig struct {
	ConfigInit            int32            // +0 int _config_init
	Isolated              int32            // +4 int isolated
	UseEnvironment        int32            // +8 int use_environment
	DevMode               int32            // +12 int dev_mode
	InstallSignalHandlers int32            // +16 int install_signal_handlers
	UseHashSeed           int32            // +20 int use_hash_seed
	HashSeed              uint64           // +24 unsigned long hash_seed
	Faulthandler          int32            // +32 int faulthandler
	Tracemalloc           int32            // +36 int tracemalloc
	PerfProfiling         int32            // +40 int perf_profiling
	ImportTime            int32            // +44 int import_time
	CodeDebugRanges       int32            // +48 int code_debug_ranges
	ShowRefCount          int32            // +52 int show_ref_count
	DumpRefs              int32            // +56 int dump_refs
	DumpRefsFile          uintptr          // +64 wchar_t * dump_refs_file
	MallocStats           int32            // +72 int malloc_stats
	FilesystemEncoding    uintptr          // +80 wchar_t * filesystem_encoding
	FilesystemErrors      uintptr          // +88 wchar_t * filesystem_errors
	PycachePrefix         uintptr          // +96 wchar_t * pycache_prefix
	ParseArgv             int32            // +104 int parse_argv
	OrigArgv              PyWideStringList // +112 PyWideStringList orig_argv
	Argv                  PyWideStringList // +128 PyWideStringList argv
	Xoptions              PyWideStringList // +144 PyWideStringList xoptions
	Warnoptions           PyWideStringList // +160 PyWideStringList warnoptions
	SiteImport            int32            // +176 int site_import
	BytesWarning          int32            // +180 int bytes_warning
	WarnDefaultEncoding   int32            // +184 int warn_default_encoding
	Inspect               int32            // +188 int inspect
	Interactive           int32            // +192 int interactive
	OptimizationLevel     int32            // +196 int optimization_level
	ParserDebug           int32            // +200 int parser_debug
	WriteBytecode         int32            // +204 int write_bytecode
	Verbose               int32            // +208 int verbose
	Quiet                 int32            // +212 int quiet
	UserSiteDirectory     int32            // +216 int user_site_directory
	ConfigureCStdio       int32            // +220 int configure_c_stdio
	BufferedStdio         int32            // +224 int buffered_stdio
	StdioEncoding         uintptr          // +232 wchar_t * stdio_encoding
	StdioErrors           uintptr          // +240 wchar_t * stdio_errors
	CheckHashPycsMode     uintptr          // +248 wchar_t * check_hash_pycs_mode
	UseFrozenModules      int32            // +256 int use_frozen_modules
	SafePath              int32            // +260 int safe_path
	IntMaxStrDigits       int32            // +264 int int_max_str_digits
	CpuCount              int32            // +268 int cpu_count
	PathconfigWarnings    int32            // +272 int pathconfig_warnings
	ProgramName           uintptr          // +280 wchar_t * program_name
	PythonpathEnv         uintptr          // +288 wchar_t * pythonpath_env
	Home                  uintptr          // +296 wchar_t * home
	Platlibdir            uintptr          // +304 wchar_t * platlibdir
	ModuleSearchPathsSet  int32            // +312 int module_search_paths_set
	ModuleSearchPaths     PyWideStringList // +320 PyWideStringList module_search_paths
	StdlibDir             uintptr          // +336 wchar_t * stdlib_dir
	Executable            uintptr          // +344 wchar_t * executable
	BaseExecutable        uintptr          // +352 wchar_t * base_executable
	Prefix                uintptr          // +360 wchar_t * prefix
	BasePrefix            uintptr          // +368 wchar_t * base_prefix
	ExecPrefix            uintptr          // +376 wchar_t * exec_prefix
	BaseExecPrefix        uintptr          // +384 wchar_t * base_exec_prefix
	SkipSourceFirstLine   int32            // +392 int skip_source_first_line
	RunCommand            uintptr          // +400 wchar_t * run_command
	RunModule             uintptr          // +408 wchar_t * run_module
	RunFilename           uintptr          // +416 wchar_t * run_filename
	SysPath0              uintptr          // +424 wchar_t * sys_path_0
	InstallImportlib      int32            // +432 int _install_importlib
	InitMain              int32            // +436 int _init_main
	IsPythonBuild         int32            // +440 int _is_python_build
}

// PyPreConfig mirrors the C struct PyPreConfig (size 40; initconfig.h:47).
type PyPreConfig struct {
	ConfigInit        int32 // +0 int _config_init
	ParseArgv         int32 // +4 int parse_argv
	Isolated          int32 // +8 int isolated
	UseEnvironment    int32 // +12 int use_environment
	ConfigureLocale   int32 // +16 int configure_locale
	CoerceCLocale     int32 // +20 int coerce_c_locale
	CoerceCLocaleWarn int32 // +24 int coerce_c_locale_warn
	Utf8Mode          int32 // +28 int utf8_mode
	DevMode           int32 // +32 int dev_mode
	Allocator         int32 // +36 int allocator
}

// PyStatus mirrors the C struct PyStatus (size 32; initconfig.h:10).
type PyStatus struct {
	Type     int32   // +0 enum (unnamed at initconfig.h:11:5) _type
	Func     uintptr // +8 const char * func
	ErrMsg   uintptr // +16 const char * err_msg
	Exitcode int32   // +24 int exitcode
}

// PyWideStringList mirrors the C struct PyWideStringList (size 16; initconfig.h:31).
type PyWideStringList struct {
	Length int64   // +0 Py_ssize_t length
	Items  uintptr // +8 wchar_t ** items
}
