// Code generated by h2go; DO NOT EDIT.

package py313

// PyGenObjectHEAD mirrors the struct-shaped C macro _PyGenObject_HEAD.
type PyGenObjectHEAD struct {
	PyObjectHEAD                       // +0
	GiWeakreflist       uintptr        // +16 PyObject * gi_weakreflist
	GiName              uintptr        // +24 PyObject * gi_name
	GiQualname          uintptr        // +32 PyObject * gi_qualname
	GiExcState          PyErrStackItem // +40 _PyErr_StackItem gi_exc_state
	GiOriginOrFinalizer uintptr        // +56 PyObject * gi_origin_or_finalizer
	GiHooksInited       int8           // +64 char gi_hooks_inited
	GiClosed            int8           // +65 char gi_closed
	GiRunningAsync      int8           // +66 char gi_running_async
	GiFrameState        int8           // +67 int8_t gi_frame_state
	GiIframe            [1]uintptr     // +72 PyObject *[1] gi_iframe
}

// PyAsyncGenObject mirrors the C struct PyAsyncGenObject (size 80; genobject.h:62).
type PyAsyncGenObject struct {
	PyObjectHEAD                       // +0
	AgWeakreflist       uintptr        // +16 PyObject * ag_weakreflist
	AgName              uintptr        // +24 PyObject * ag_name
	AgQualname          uintptr        // +32 PyObject * ag_qualname
	AgExcState          PyErrStackItem // +40 _PyErr_StackItem ag_exc_state
	AgOriginOrFinalizer uintptr        // +56 PyObject * ag_origin_or_finalizer
	AgHooksInited       int8           // +64 char ag_hooks_inited
	AgClosed            int8           // +65 char ag_closed
	AgRunningAsync      int8           // +66 char ag_running_async
	AgFrameState        int8           // +67 int8_t ag_frame_state
	AgIframe            [1]uintptr     // +72 PyObject *[1] ag_iframe
}

// PyCoroObject mirrors the C struct PyCoroObject (size 80; genobject.h:49).
type PyCoroObject struct {
	PyObjectHEAD                       // +0
	CrWeakreflist       uintptr        // +16 PyObject * cr_weakreflist
	CrName              uintptr        // +24 PyObject * cr_name
	CrQualname          uintptr        // +32 PyObject * cr_qualname
	CrExcState          PyErrStackItem // +40 _PyErr_StackItem cr_exc_state
	CrOriginOrFinalizer uintptr        // +56 PyObject * cr_origin_or_finalizer
	CrHooksInited       int8           // +64 char cr_hooks_inited
	CrClosed            int8           // +65 char cr_closed
	CrRunningAsync      int8           // +66 char cr_running_async
	CrFrameState        int8           // +67 int8_t cr_frame_state
	CrIframe            [1]uintptr     // +72 PyObject *[1] cr_iframe
}

// PyGenObject mirrors the C struct PyGenObject (size 80; genobject.h:31).
type PyGenObject struct {
	PyGenObjectHEAD // +0
}
