// Code generated by h2go; DO NOT EDIT.

package py313

// PyExceptionHEAD mirrors the struct-shaped C macro PyException_HEAD.
type PyExceptionHEAD struct {
	PyObjectHEAD            // +0
	Dict            uintptr // +16 PyObject * dict
	Args            uintptr // +24 PyObject * args
	Notes           uintptr // +32 PyObject * notes
	Traceback       uintptr // +40 PyObject * traceback
	Context         uintptr // +48 PyObject * context
	Cause           uintptr // +56 PyObject * cause
	SuppressContext int8    // +64 char suppress_context
}

// PyAttributeErrorObject mirrors the C struct PyAttributeErrorObject (size 88; pyerrors.h:80).
type PyAttributeErrorObject struct {
	PyExceptionHEAD         // +0
	Obj             uintptr // +72 PyObject * obj
	Name            uintptr // +80 PyObject * name
}

// PyBaseExceptionGroupObject mirrors the C struct PyBaseExceptionGroupObject (size 96; pyerrors.h:17).
type PyBaseExceptionGroupObject struct {
	PyExceptionHEAD         // +0
	Msg             uintptr // +72 PyObject * msg
	Excs            uintptr // +80 PyObject * excs
	ExcsStr         uintptr // +88 PyObject * excs_str
}

// PyBaseExceptionObject mirrors the C struct PyBaseExceptionObject (size 72; pyerrors.h:13).
type PyBaseExceptionObject struct {
	PyExceptionHEAD // +0
}

// PyEnvironmentErrorObject is the C typedef "PyOSErrorObject" (pyerrors.h:87).
type PyEnvironmentErrorObject = PyOSErrorObject

// PyImportErrorObject mirrors the C struct PyImportErrorObject (size 104; pyerrors.h:36).
type PyImportErrorObject struct {
	PyExceptionHEAD         // +0
	Msg             uintptr // +72 PyObject * msg
	Name            uintptr // +80 PyObject * name
	Path            uintptr // +88 PyObject * path
	NameFrom        uintptr // +96 PyObject * name_from
}

// PyNameErrorObject mirrors the C struct PyNameErrorObject (size 80; pyerrors.h:75).
type PyNameErrorObject struct {
	PyExceptionHEAD         // +0
	Name            uintptr // +72 PyObject * name
}

// PyOSErrorObject mirrors the C struct PyOSErrorObject (size 112; pyerrors.h:58).
type PyOSErrorObject struct {
	PyExceptionHEAD         // +0
	Myerrno         uintptr // +72 PyObject * myerrno
	Strerror        uintptr // +80 PyObject * strerror
	Filename        uintptr // +88 PyObject * filename
	Filename2       uintptr // +96 PyObject * filename2
	Written         int64   // +104 Py_ssize_t written
}

// PyStopIterationObject mirrors the C struct PyStopIterationObject (size 80; pyerrors.h:70).
type PyStopIterationObject struct {
	PyExceptionHEAD         // +0
	Value           uintptr // +72 PyObject * value
}

// PySyntaxErrorObject mirrors the C struct PySyntaxErrorObject (size 136; pyerrors.h:24).
type PySyntaxErrorObject struct {
	PyExceptionHEAD          // +0
	Msg              uintptr // +72 PyObject * msg
	Filename         uintptr // +80 PyObject * filename
	Lineno           uintptr // +88 PyObject * lineno
	Offset           uintptr // +96 PyObject * offset
	EndLineno        uintptr // +104 PyObject * end_lineno
	EndOffset        uintptr // +112 PyObject * end_offset
	Text             uintptr // +120 PyObject * text
	PrintFileAndLine uintptr // +128 PyObject * print_file_and_line
}

// PySystemExitObject mirrors the C struct PySystemExitObject (size 80; pyerrors.h:53).
type PySystemExitObject struct {
	PyExceptionHEAD         // +0
	Code            uintptr // +72 PyObject * code
}

// PyUnicodeErrorObject mirrors the C struct PyUnicodeErrorObject (size 112; pyerrors.h:44).
type PyUnicodeErrorObject struct {
	PyExceptionHEAD         // +0
	Encoding        uintptr // +72 PyObject * encoding
	Object          uintptr // +80 PyObject * object
	Start           int64   // +88 Py_ssize_t start
	End             int64   // +96 Py_ssize_t end
	Reason          uintptr // +104 PyObject * reason
}
