// Code generated by h2go; DO NOT EDIT.

package py313

// PyFloatObject mirrors the C struct PyFloatObject (size 24; floatobject.h:5).
type PyFloatObject struct {
	PyObjectHEAD         // +0
	ObFval       float64 // +16 double ob_fval
}
