// Code generated by h2go; DO NOT EDIT.

package py313

// PyErrStackItem mirrors the C struct _err_stackitem (size 16; pystate.h:32).
type PyErrStackItem struct {
	ExcValue     uintptr // +0 PyObject * exc_value
	PreviousItem uintptr // +8 struct _err_stackitem * previous_item
}

// PyStackChunk mirrors the C struct _stack_chunk (size 32; pystate.h:52).
type PyStackChunk struct {
	Previous uintptr    // +0 struct _stack_chunk * previous
	Size     uint64     // +8 size_t size
	Top      uint64     // +16 size_t top
	Data     [1]uintptr // +24 PyObject *[1] data
}
