// Code generated by h2go; DO NOT EDIT.

package py313

// PerfMapState mirrors the C struct PerfMapState (size 16; sysmodule.h:9).
type PerfMapState struct {
	PerfMap uintptr // +0 FILE * perf_map
	MapLock uintptr // +8 PyThread_type_lock map_lock
}
