// Code generated by h2go; DO NOT EDIT.

package py313

// PyModuleDefBase mirrors the C struct PyModuleDef_Base (size 40; moduleobject.h:39).
type PyModuleDefBase struct {
	PyObjectHEAD         // +0
	MInit        uintptr // +16 PyObject *(*)(void) m_init
	MIndex       int64   // +24 Py_ssize_t m_index
	MCopy        uintptr // +32 PyObject * m_copy
}
