// Code generated by h2go; DO NOT EDIT.

package py312

// PyCompilerFlags mirrors the C struct PyCompilerFlags (size 8; compile.h:26).
type PyCompilerFlags struct {
	CfFlags          int32 // +0 int cf_flags
	CfFeatureVersion int32 // +4 int cf_feature_version
}

// PyFutureFeatures mirrors the C struct PyFutureFeatures (size 20; compile.h:51).
type PyFutureFeatures struct {
	FfFeatures int32                 // +0 int ff_features
	FfLocation PyCompilerSrcLocation // +4 _PyCompilerSrcLocation ff_location
}

// PyCompilerSrcLocation mirrors the C struct _PyCompilerSrcLocation (size 16; compile.h:35).
type PyCompilerSrcLocation struct {
	Lineno       int32 // +0 int lineno
	EndLineno    int32 // +4 int end_lineno
	ColOffset    int32 // +8 int col_offset
	EndColOffset int32 // +12 int end_col_offset
}
