// Code generated by h2go; DO NOT EDIT.

package py312

// PyDictObject mirrors the C struct PyDictObject (size 48; dictobject.h:11).
type PyDictObject struct {
	PyObjectHEAD         // +0
	MaUsed       int64   // +16 Py_ssize_t ma_used
	MaVersionTag uint64  // +24 uint64_t ma_version_tag
	MaKeys       uintptr // +32 PyDictKeysObject * ma_keys
	MaValues     uintptr // +40 PyDictValues * ma_values
}

// PyDictWatchEvent is the C enum enum PyDict_WatchEvent (size 4; dictobject.h:105).
type PyDictWatchEvent uint32

// PyDictViewObject mirrors the C struct _PyDictViewObject (size 24; dictobject.h:83).
type PyDictViewObject struct {
	PyObjectHEAD         // +0
	DvDict       uintptr // +16 PyDictObject * dv_dict
}
