// Code generated by h2go; DO NOT EDIT.

package py312

import "unsafe"

// PyCodeAddressRange mirrors the C struct _line_offsets (size 40; code.h:322).
type PyCodeAddressRange struct {
	ArStart int32    // +0 int ar_start
	ArEnd   int32    // +4 int ar_end
	ArLine  int32    // +8 int ar_line
	Opaque  [24]byte // +16 struct _opaque opaque
}

// PyCodeEvent is the C enum enum PyCodeEvent (size 4; code.h:283).
type PyCodeEvent uint32

// PyCoCached mirrors the C struct _PyCoCached (size 32; code.h:71).
type PyCoCached struct {
	CoCode     uintptr // +0 PyObject * _co_code
	CoVarnames uintptr // +8 PyObject * _co_varnames
	CoCellvars uintptr // +16 PyObject * _co_cellvars
	CoFreevars uintptr // +24 PyObject * _co_freevars
}

// PyCoLineInstrumentationData mirrors the C struct _PyCoLineInstrumentationData (size 2; code.h:81).
type PyCoLineInstrumentationData struct {
	OriginalOpcode uint8 // +0 uint8_t original_opcode
	LineDelta      int8  // +1 int8_t line_delta
}

// PyCoMonitoringData mirrors the C struct _PyCoMonitoringData (size 72; code.h:89).
type PyCoMonitoringData struct {
	LocalMonitors         PyLocalMonitors // +0 _Py_LocalMonitors local_monitors
	ActiveMonitors        PyLocalMonitors // +15 _Py_LocalMonitors active_monitors
	Tools                 uintptr         // +32 uint8_t * tools
	Lines                 uintptr         // +40 _PyCoLineInstrumentationData * lines
	LineTools             uintptr         // +48 uint8_t * line_tools
	PerInstructionOpcodes uintptr         // +56 uint8_t * per_instruction_opcodes
	PerInstructionTools   uintptr         // +64 uint8_t * per_instruction_tools
}

// PyCodeLocationInfoKind is the C enum enum _PyCodeLocationInfoKind (size 4; code.h:383).
type PyCodeLocationInfoKind uint32

// PyCODEUNIT seals the C union _Py_CODEUNIT (size 2; code.h:38).
type PyCODEUNIT [2]byte

// Cache accesses the "cache" member.
func (u *PyCODEUNIT) Cache() *uint16 { return (*uint16)(unsafe.Pointer(u)) }

// Op accesses the "op" member.
func (u *PyCODEUNIT) Op() *_pycodeunit_op { return (*_pycodeunit_op)(unsafe.Pointer(u)) }

type _pycodeunit_op struct {
	Code uint8 // +0 uint8_t code
	Arg  uint8 // +1 uint8_t arg
}

// PyGlobalMonitors mirrors the C struct _Py_GlobalMonitors (size 15; code.h:25).
type PyGlobalMonitors struct {
	Tools [15]uint8 // +0 uint8_t[15] tools
}

// PyLocalMonitors mirrors the C struct _Py_LocalMonitors (size 15; code.h:20).
type PyLocalMonitors struct {
	Tools [15]uint8 // +0 uint8_t[15] tools
}
