// Code generated by h2go; DO NOT EDIT.

package py27

// PyClassObject mirrors the C struct PyClassObject (size 72; classobject.h:12).
type PyClassObject struct {
	PyObjectHEAD          // +0
	ClBases       uintptr // +16 PyObject * cl_bases
	ClDict        uintptr // +24 PyObject * cl_dict
	ClName        uintptr // +32 PyObject * cl_name
	ClGetattr     uintptr // +40 PyObject * cl_getattr
	ClSetattr     uintptr // +48 PyObject * cl_setattr
	ClDelattr     uintptr // +56 PyObject * cl_delattr
	ClWeakreflist uintptr // +64 PyObject * cl_weakreflist
}

// PyInstanceObject mirrors the C struct PyInstanceObject (size 40; classobject.h:24).
type PyInstanceObject struct {
	PyObjectHEAD          // +0
	InClass       uintptr // +16 PyClassObject * in_class
	InDict        uintptr // +24 PyObject * in_dict
	InWeakreflist uintptr // +32 PyObject * in_weakreflist
}

// PyMethodObject mirrors the C struct PyMethodObject (size 48; classobject.h:31).
type PyMethodObject struct {
	PyObjectHEAD          // +0
	ImFunc        uintptr // +16 PyObject * im_func
	ImSelf        uintptr // +24 PyObject * im_self
	ImClass       uintptr // +32 PyObject * im_class
	ImWeakreflist uintptr // +40 PyObject * im_weakreflist
}
