// Code generated by h2go; DO NOT EDIT.

package py27

// PyCObject mirrors the C struct PyCObject (size 40; cobject.h:78).
type PyCObject struct {
	PyObjectHEAD         // +0
	Cobject      uintptr // +16 void * cobject
	Desc         uintptr // +24 void * desc
	Destructor   uintptr // +32 void (*)(void *) destructor
}
