// Code generated by h2go; DO NOT EDIT.

package py27

// PyAddrPair mirrors the C struct _addr_pair (size 8; code.h:90).
type PyAddrPair struct {
	ApLower int32 // +0 int ap_lower
	ApUpper int32 // +4 int ap_upper
}

// PyCodeObject mirrors the C struct PyCodeObject (size 128; code.h:10).
type PyCodeObject struct {
	PyObjectHEAD          // +0
	CoArgcount    int32   // +16 int co_argcount
	CoNlocals     int32   // +20 int co_nlocals
	CoStacksize   int32   // +24 int co_stacksize
	CoFlags       int32   // +28 int co_flags
	CoCode        uintptr // +32 PyObject * co_code
	CoConsts      uintptr // +40 PyObject * co_consts
	CoNames       uintptr // +48 PyObject * co_names
	CoVarnames    uintptr // +56 PyObject * co_varnames
	CoFreevars    uintptr // +64 PyObject * co_freevars
	CoCellvars    uintptr // +72 PyObject * co_cellvars
	CoFilename    uintptr // +80 PyObject * co_filename
	CoName        uintptr // +88 PyObject * co_name
	CoFirstlineno int32   // +96 int co_firstlineno
	CoLnotab      uintptr // +104 PyObject * co_lnotab
	CoZombieframe uintptr // +112 void * co_zombieframe
	CoWeakreflist uintptr // +120 PyObject * co_weakreflist
}
