// Code generated by h2go; DO NOT EDIT.

package py27

// PyDescrCOMMON mirrors the struct-shaped C macro PyDescr_COMMON.
type PyDescrCOMMON struct {
	PyObjectHEAD         // +0
	DType        uintptr // +16 PyTypeObject * d_type
	DName        uintptr // +24 PyObject * d_name
}

// PyDescrObject mirrors the C struct PyDescrObject (size 32; descrobject.h:45).
type PyDescrObject struct {
	PyDescrCOMMON // +0
}

// PyGetSetDescrObject mirrors the C struct PyGetSetDescrObject (size 40; descrobject.h:59).
type PyGetSetDescrObject struct {
	PyDescrCOMMON         // +0
	DGetset       uintptr // +32 PyGetSetDef * d_getset
}

// PyMemberDescrObject mirrors the C struct PyMemberDescrObject (size 40; descrobject.h:54).
type PyMemberDescrObject struct {
	PyDescrCOMMON         // +0
	DMember       uintptr // +32 struct PyMemberDef * d_member
}

// PyMethodDescrObject mirrors the C struct PyMethodDescrObject (size 40; descrobject.h:49).
type PyMethodDescrObject struct {
	PyDescrCOMMON         // +0
	DMethod       uintptr // +32 PyMethodDef * d_method
}

// PyWrapperDescrObject mirrors the C struct PyWrapperDescrObject (size 48; descrobject.h:64).
type PyWrapperDescrObject struct {
	PyDescrCOMMON         // +0
	DBase         uintptr // +32 struct wrapperbase * d_base
	DWrapped      uintptr // +40 void * d_wrapped
}
