// Code generated by h2go; DO NOT EDIT.

package py27

// PyFileObject mirrors the C struct PyFileObject (size 144; fileobject.h:10).
type PyFileObject struct {
	PyObjectHEAD          // +0
	FFp           uintptr // +16 FILE * f_fp
	FName         uintptr // +24 PyObject * f_name
	FMode         uintptr // +32 PyObject * f_mode
	FClose        uintptr // +40 int (*)(FILE *) f_close
	FSoftspace    int32   // +48 int f_softspace
	FBinary       int32   // +52 int f_binary
	FBuf          uintptr // +56 char * f_buf
	FBufend       uintptr // +64 char * f_bufend
	FBufptr       uintptr // +72 char * f_bufptr
	FSetbuf       uintptr // +80 char * f_setbuf
	FUnivNewline  int32   // +88 int f_univ_newline
	FNewlinetypes int32   // +92 int f_newlinetypes
	FSkipnextlf   int32   // +96 int f_skipnextlf
	FEncoding     uintptr // +104 PyObject * f_encoding
	FErrors       uintptr // +112 PyObject * f_errors
	Weakreflist   uintptr // +120 PyObject * weakreflist
	UnlockedCount int32   // +128 int unlocked_count
	Readable      int32   // +132 int readable
	Writable      int32   // +136 int writable
}
