// Code generated by h2go; DO NOT EDIT.

package py27

// PyObjectHEAD mirrors the struct-shaped C macro PyObject_HEAD.
type PyObjectHEAD struct {
	ObRefcnt int64   // +0 Py_ssize_t ob_refcnt
	ObType   uintptr // +8 struct _typeobject * ob_type
}

// PyObjectVARHEAD mirrors the struct-shaped C macro PyObject_VAR_HEAD.
type PyObjectVARHEAD struct {
	PyObjectHEAD       // +0
	ObSize       int64 // +16 Py_ssize_t ob_size
}

// PyBufferProcs mirrors the C struct PyBufferProcs (size 48; object.h:295).
type PyBufferProcs struct {
	BfGetreadbuffer  uintptr // +0 readbufferproc bf_getreadbuffer
	BfGetwritebuffer uintptr // +8 writebufferproc bf_getwritebuffer
	BfGetsegcount    uintptr // +16 segcountproc bf_getsegcount
	BfGetcharbuffer  uintptr // +24 charbufferproc bf_getcharbuffer
	BfGetbuffer      uintptr // +32 getbufferproc bf_getbuffer
	BfReleasebuffer  uintptr // +40 releasebufferproc bf_releasebuffer
}

// PyGetSetDef mirrors the C struct PyGetSetDef (size 40; object.h:382).
type PyGetSetDef struct {
	Name    uintptr // +0 char * name
	Get     uintptr // +8 getter get
	Set     uintptr // +16 setter set
	Doc     uintptr // +24 char * doc
	Closure uintptr // +32 void * closure
}

// PyHeapTypeObject mirrors the C struct _heaptypeobject (size 872; object.h:415).
type PyHeapTypeObject struct {
	HtType     PyTypeObject      // +0 PyTypeObject ht_type
	AsNumber   PyNumberMethods   // +392 PyNumberMethods as_number
	AsMapping  PyMappingMethods  // +704 PyMappingMethods as_mapping
	AsSequence PySequenceMethods // +728 PySequenceMethods as_sequence
	AsBuffer   PyBufferProcs     // +808 PyBufferProcs as_buffer
	HtName     uintptr           // +856 PyObject * ht_name
	HtSlots    uintptr           // +864 PyObject * ht_slots
}

// PyMappingMethods mirrors the C struct PyMappingMethods (size 24; object.h:289).
type PyMappingMethods struct {
	MpLength       uintptr // +0 lenfunc mp_length
	MpSubscript    uintptr // +8 binaryfunc mp_subscript
	MpAssSubscript uintptr // +16 objobjargproc mp_ass_subscript
}

// PyMethodDef mirrors the C struct PyMethodDef (size 32; object.h:380).
type PyMethodDef struct {
	MlName  uintptr // +0 const char * ml_name
	MlMeth  uintptr // +8 PyCFunction ml_meth
	MlFlags int32   // +16 int ml_flags
	MlDoc   uintptr // +24 const char * ml_doc
}

// PyNumberMethods mirrors the C struct PyNumberMethods (size 312; object.h:219).
type PyNumberMethods struct {
	NbAdd                uintptr // +0 binaryfunc nb_add
	NbSubtract           uintptr // +8 binaryfunc nb_subtract
	NbMultiply           uintptr // +16 binaryfunc nb_multiply
	NbDivide             uintptr // +24 binaryfunc nb_divide
	NbRemainder          uintptr // +32 binaryfunc nb_remainder
	NbDivmod             uintptr // +40 binaryfunc nb_divmod
	NbPower              uintptr // +48 ternaryfunc nb_power
	NbNegative           uintptr // +56 unaryfunc nb_negative
	NbPositive           uintptr // +64 unaryfunc nb_positive
	NbAbsolute           uintptr // +72 unaryfunc nb_absolute
	NbNonzero            uintptr // +80 inquiry nb_nonzero
	NbInvert             uintptr // +88 unaryfunc nb_invert
	NbLshift             uintptr // +96 binaryfunc nb_lshift
	NbRshift             uintptr // +104 binaryfunc nb_rshift
	NbAnd                uintptr // +112 binaryfunc nb_and
	NbXor                uintptr // +120 binaryfunc nb_xor
	NbOr                 uintptr // +128 binaryfunc nb_or
	NbCoerce             uintptr // +136 coercion nb_coerce
	NbInt                uintptr // +144 unaryfunc nb_int
	NbLong               uintptr // +152 unaryfunc nb_long
	NbFloat              uintptr // +160 unaryfunc nb_float
	NbOct                uintptr // +168 unaryfunc nb_oct
	NbHex                uintptr // +176 unaryfunc nb_hex
	NbInplaceAdd         uintptr // +184 binaryfunc nb_inplace_add
	NbInplaceSubtract    uintptr // +192 binaryfunc nb_inplace_subtract
	NbInplaceMultiply    uintptr // +200 binaryfunc nb_inplace_multiply
	NbInplaceDivide      uintptr // +208 binaryfunc nb_inplace_divide
	NbInplaceRemainder   uintptr // +216 binaryfunc nb_inplace_remainder
	NbInplacePower       uintptr // +224 ternaryfunc nb_inplace_power
	NbInplaceLshift      uintptr // +232 binaryfunc nb_inplace_lshift
	NbInplaceRshift      uintptr // +240 binaryfunc nb_inplace_rshift
	NbInplaceAnd         uintptr // +248 binaryfunc nb_inplace_and
	NbInplaceXor         uintptr // +256 binaryfunc nb_inplace_xor
	NbInplaceOr          uintptr // +264 binaryfunc nb_inplace_or
	NbFloorDivide        uintptr // +272 binaryfunc nb_floor_divide
	NbTrueDivide         uintptr // +280 binaryfunc nb_true_divide
	NbInplaceFloorDivide uintptr // +288 binaryfunc nb_inplace_floor_divide
	NbInplaceTrueDivide  uintptr // +296 binaryfunc nb_inplace_true_divide
	NbIndex              uintptr // +304 unaryfunc nb_index
}

// PyObject mirrors the C struct _object (size 16; object.h:106).
type PyObject struct {
	PyObjectHEAD // +0
}

// PySequenceMethods mirrors the C struct PySequenceMethods (size 80; object.h:275).
type PySequenceMethods struct {
	SqLength        uintptr // +0 lenfunc sq_length
	SqConcat        uintptr // +8 binaryfunc sq_concat
	SqRepeat        uintptr // +16 ssizeargfunc sq_repeat
	SqItem          uintptr // +24 ssizeargfunc sq_item
	SqSlice         uintptr // +32 ssizessizeargfunc sq_slice
	SqAssItem       uintptr // +40 ssizeobjargproc sq_ass_item
	SqAssSlice      uintptr // +48 ssizessizeobjargproc sq_ass_slice
	SqContains      uintptr // +56 objobjproc sq_contains
	SqInplaceConcat uintptr // +64 binaryfunc sq_inplace_concat
	SqInplaceRepeat uintptr // +72 ssizeargfunc sq_inplace_repeat
}

// PyTypeObject mirrors the C struct _typeobject (size 392; object.h:107).
type PyTypeObject struct {
	PyObjectVARHEAD          // +0
	TpName           uintptr // +24 const char * tp_name
	TpBasicsize      int64   // +32 Py_ssize_t tp_basicsize
	TpItemsize       int64   // +40 Py_ssize_t tp_itemsize
	TpDealloc        uintptr // +48 destructor tp_dealloc
	TpPrint          uintptr // +56 printfunc tp_print
	TpGetattr        uintptr // +64 getattrfunc tp_getattr
	TpSetattr        uintptr // +72 setattrfunc tp_setattr
	TpCompare        uintptr // +80 cmpfunc tp_compare
	TpRepr           uintptr // +88 reprfunc tp_repr
	TpAsNumber       uintptr // +96 PyNumberMethods * tp_as_number
	TpAsSequence     uintptr // +104 PySequenceMethods * tp_as_sequence
	TpAsMapping      uintptr // +112 PyMappingMethods * tp_as_mapping
	TpHash           uintptr // +120 hashfunc tp_hash
	TpCall           uintptr // +128 ternaryfunc tp_call
	TpStr            uintptr // +136 reprfunc tp_str
	TpGetattro       uintptr // +144 getattrofunc tp_getattro
	TpSetattro       uintptr // +152 setattrofunc tp_setattro
	TpAsBuffer       uintptr // +160 PyBufferProcs * tp_as_buffer
	TpFlags          int64   // +168 long tp_flags
	TpDoc            uintptr // +176 const char * tp_doc
	TpTraverse       uintptr // +184 traverseproc tp_traverse
	TpClear          uintptr // +192 inquiry tp_clear
	TpRichcompare    uintptr // +200 richcmpfunc tp_richcompare
	TpWeaklistoffset int64   // +208 Py_ssize_t tp_weaklistoffset
	TpIter           uintptr // +216 getiterfunc tp_iter
	TpIternext       uintptr // +224 iternextfunc tp_iternext
	TpMethods        uintptr // +232 struct PyMethodDef * tp_methods
	TpMembers        uintptr // +240 struct PyMemberDef * tp_members
	TpGetset         uintptr // +248 struct PyGetSetDef * tp_getset
	TpBase           uintptr // +256 struct _typeobject * tp_base
	TpDict           uintptr // +264 PyObject * tp_dict
	TpDescrGet       uintptr // +272 descrgetfunc tp_descr_get
	TpDescrSet       uintptr // +280 descrsetfunc tp_descr_set
	TpDictoffset     int64   // +288 Py_ssize_t tp_dictoffset
	TpInit           uintptr // +296 initproc tp_init
	TpAlloc          uintptr // +304 allocfunc tp_alloc
	TpNew            uintptr // +312 newfunc tp_new
	TpFree           uintptr // +320 freefunc tp_free
	TpIsGc           uintptr // +328 inquiry tp_is_gc
	TpBases          uintptr // +336 PyObject * tp_bases
	TpMro            uintptr // +344 PyObject * tp_mro
	TpCache          uintptr // +352 PyObject * tp_cache
	TpSubclasses     uintptr // +360 PyObject * tp_subclasses
	TpWeaklist       uintptr // +368 PyObject * tp_weaklist
	TpDel            uintptr // +376 destructor tp_del
	TpVersionTag     uint32  // +384 unsigned int tp_version_tag
}

// PyVarObject mirrors the C struct PyVarObject (size 24; object.h:110).
type PyVarObject struct {
	PyObjectVARHEAD // +0
}

// PyBuffer mirrors the C struct bufferinfo (size 96; object.h:164).
type PyBuffer struct {
	Buf        uintptr  // +0 void * buf
	Obj        uintptr  // +8 PyObject * obj
	Len        int64    // +16 Py_ssize_t len
	Itemsize   int64    // +24 Py_ssize_t itemsize
	Readonly   int32    // +32 int readonly
	Ndim       int32    // +36 int ndim
	Format     uintptr  // +40 char * format
	Shape      uintptr  // +48 Py_ssize_t * shape
	Strides    uintptr  // +56 Py_ssize_t * strides
	Suboffsets uintptr  // +64 Py_ssize_t * suboffsets
	Smalltable [2]int64 // +72 Py_ssize_t[2] smalltable
	Internal   uintptr  // +88 void * internal
}

// PyHashSecretT mirrors the C struct _Py_HashSecret_t (size 16; object.h:520).
type PyHashSecretT struct {
	Prefix int64 // +0 long prefix
	Suffix int64 // +8 long suffix
}
