// Code generated by h2go; DO NOT EDIT.

package py27

import "unsafe"

// PyGCHead seals the C union _gc_head (size 32; objimpl.h:255).
type PyGCHead [32]byte

// Gc accesses the "gc" member.
func (u *PyGCHead) Gc() *_pygchead_gc { return (*_pygchead_gc)(unsafe.Pointer(u)) }

// Dummy accesses the "dummy" member.
func (u *PyGCHead) Dummy() *float64 { return (*float64)(unsafe.Pointer(u)) }

// DummyPadding accesses the "dummy_padding" member.
func (u *PyGCHead) DummyPadding() *[32]int8 { return (*[32]int8)(unsafe.Pointer(u)) }

type _pygchead_gc struct {
	GcNext uintptr // +0 union _gc_head * gc_next
	GcPrev uintptr // +8 union _gc_head * gc_prev
	GcRefs int64   // +16 Py_ssize_t gc_refs
}
