// Code generated by h2go; DO NOT EDIT.

package py27

// PyBaseExceptionObject mirrors the C struct PyBaseExceptionObject (size 40; pyerrors.h:9).
type PyBaseExceptionObject struct {
	PyObjectHEAD         // +0
	Dict         uintptr // +16 PyObject * dict
	Args         uintptr // +24 PyObject * args
	Message      uintptr // +32 PyObject * message
}

// PyEnvironmentErrorObject mirrors the C struct PyEnvironmentErrorObject (size 64; pyerrors.h:51).
type PyEnvironmentErrorObject struct {
	PyObjectHEAD         // +0
	Dict         uintptr // +16 PyObject * dict
	Args         uintptr // +24 PyObject * args
	Message      uintptr // +32 PyObject * message
	Myerrno      uintptr // +40 PyObject * myerrno
	Strerror     uintptr // +48 PyObject * strerror
	Filename     uintptr // +56 PyObject * filename
}

// PySyntaxErrorObject mirrors the C struct PySyntaxErrorObject (size 88; pyerrors.h:16).
type PySyntaxErrorObject struct {
	PyObjectHEAD             // +0
	Dict             uintptr // +16 PyObject * dict
	Args             uintptr // +24 PyObject * args
	Message          uintptr // +32 PyObject * message
	Msg              uintptr // +40 PyObject * msg
	Filename         uintptr // +48 PyObject * filename
	Lineno           uintptr // +56 PyObject * lineno
	Offset           uintptr // +64 PyObject * offset
	Text             uintptr // +72 PyObject * text
	PrintFileAndLine uintptr // +80 PyObject * print_file_and_line
}

// PySystemExitObject mirrors the C struct PySystemExitObject (size 48; pyerrors.h:43).
type PySystemExitObject struct {
	PyObjectHEAD         // +0
	Dict         uintptr // +16 PyObject * dict
	Args         uintptr // +24 PyObject * args
	Message      uintptr // +32 PyObject * message
	Code         uintptr // +40 PyObject * code
}

// PyUnicodeErrorObject mirrors the C struct PyUnicodeErrorObject (size 80; pyerrors.h:30).
type PyUnicodeErrorObject struct {
	PyObjectHEAD         // +0
	Dict         uintptr // +16 PyObject * dict
	Args         uintptr // +24 PyObject * args
	Message      uintptr // +32 PyObject * message
	Encoding     uintptr // +40 PyObject * encoding
	Object       uintptr // +48 PyObject * object
	Start        int64   // +56 Py_ssize_t start
	End          int64   // +64 Py_ssize_t end
	Reason       uintptr // +72 PyObject * reason
}
