// Code generated by h2go; DO NOT EDIT.

package py27

// PyGILStateSTATE is the C enum enum PyGILState_STATE (size 4; pystate.h:137).
type PyGILStateSTATE uint32

// PyInterpreterState mirrors the C struct _is (size 80; pystate.h:14).
type PyInterpreterState struct {
	Next               uintptr // +0 struct _is * next
	TstateHead         uintptr // +8 struct _ts * tstate_head
	Modules            uintptr // +16 PyObject * modules
	Sysdict            uintptr // +24 PyObject * sysdict
	Builtins           uintptr // +32 PyObject * builtins
	ModulesReloading   uintptr // +40 PyObject * modules_reloading
	CodecSearchPath    uintptr // +48 PyObject * codec_search_path
	CodecSearchCache   uintptr // +56 PyObject * codec_search_cache
	CodecErrorRegistry uintptr // +64 PyObject * codec_error_registry
	Dlopenflags        int32   // +72 int dlopenflags
}

// PyThreadState mirrors the C struct _ts (size 168; pystate.h:13).
type PyThreadState struct {
	Next               uintptr // +0 struct _ts * next
	Interp             uintptr // +8 PyInterpreterState * interp
	Frame              uintptr // +16 struct _frame * frame
	RecursionDepth     int32   // +24 int recursion_depth
	Tracing            int32   // +28 int tracing
	UseTracing         int32   // +32 int use_tracing
	CProfilefunc       uintptr // +40 Py_tracefunc c_profilefunc
	CTracefunc         uintptr // +48 Py_tracefunc c_tracefunc
	CProfileobj        uintptr // +56 PyObject * c_profileobj
	CTraceobj          uintptr // +64 PyObject * c_traceobj
	CurexcType         uintptr // +72 PyObject * curexc_type
	CurexcValue        uintptr // +80 PyObject * curexc_value
	CurexcTraceback    uintptr // +88 PyObject * curexc_traceback
	ExcType            uintptr // +96 PyObject * exc_type
	ExcValue           uintptr // +104 PyObject * exc_value
	ExcTraceback       uintptr // +112 PyObject * exc_traceback
	Dict               uintptr // +120 PyObject * dict
	TickCounter        int32   // +128 int tick_counter
	GilstateCounter    int32   // +132 int gilstate_counter
	AsyncExc           uintptr // +136 PyObject * async_exc
	ThreadId           int64   // +144 long thread_id
	TrashDeleteNesting int32   // +152 int trash_delete_nesting
	TrashDeleteLater   uintptr // +160 PyObject * trash_delete_later
}
