// Code generated by h2go; DO NOT EDIT.

package py27

// PySetObject mirrors the C struct _setobject (size 200; setobject.h:34).
type PySetObject struct {
	PyObjectHEAD             // +0
	Fill         int64       // +16 Py_ssize_t fill
	Used         int64       // +24 Py_ssize_t used
	Mask         int64       // +32 Py_ssize_t mask
	Table        uintptr     // +40 setentry * table
	Lookup       uintptr     // +48 setentry *(*)(PySetObject *, PyObject *, long) lookup
	Smalltable   [8]Setentry // +56 setentry[8] smalltable
	Hash         int64       // +184 long hash
	Weakreflist  uintptr     // +192 PyObject * weakreflist
}

// Setentry mirrors the C struct setentry (size 16; setobject.h:24).
type Setentry struct {
	Hash int64   // +0 long hash
	Key  uintptr // +8 PyObject * key
}
