// Code generated by h2go; DO NOT EDIT.

package py27

// PyUnicodeObject mirrors the C struct PyUnicodeObject (size 48; unicodeobject.h:415).
type PyUnicodeObject struct {
	PyObjectHEAD         // +0
	Length       int64   // +16 Py_ssize_t length
	Str          uintptr // +24 Py_UNICODE * str
	Hash         int64   // +32 long hash
	Defenc       uintptr // +40 PyObject * defenc
}
