// Code generated by h2go; DO NOT EDIT.

package py38

// PyGCHead mirrors the C struct PyGC_Head (size 16; objimpl.h:46).
type PyGCHead struct {
	GcNext uint64 // +0 uintptr_t _gc_next
	GcPrev uint64 // +8 uintptr_t _gc_prev
}

// PyObjectArenaAllocator mirrors the C struct PyObjectArenaAllocator (size 24; objimpl.h:18).
type PyObjectArenaAllocator struct {
	Ctx   uintptr // +0 void * ctx
	Alloc uintptr // +8 void *(*)(void *, size_t) alloc
	Free  uintptr // +16 void (*)(void *, void *, size_t) free
}
