// Code generated by h2go; DO NOT EDIT.

package py38

// PyAsyncMethods mirrors the C struct PyAsyncMethods (size 24; object.h:162).
type PyAsyncMethods struct {
	AmAwait uintptr // +0 unaryfunc am_await
	AmAiter uintptr // +8 unaryfunc am_aiter
	AmAnext uintptr // +16 unaryfunc am_anext
}

// PyBufferProcs mirrors the C struct PyBufferProcs (size 16; object.h:168).
type PyBufferProcs struct {
	BfGetbuffer     uintptr // +0 getbufferproc bf_getbuffer
	BfReleasebuffer uintptr // +8 releasebufferproc bf_releasebuffer
}

// PyGetSetDef mirrors the C struct PyGetSetDef (size 40; object.h:235).
type PyGetSetDef struct {
	Name    uintptr // +0 const char * name
	Get     uintptr // +8 getter get
	Set     uintptr // +16 setter set
	Doc     uintptr // +24 const char * doc
	Closure uintptr // +32 void * closure
}

// PyHeapTypeObject mirrors the C struct _heaptypeobject (size 880; object.h:273).
type PyHeapTypeObject struct {
	HtType       PyTypeObject      // +0 PyTypeObject ht_type
	AsAsync      PyAsyncMethods    // +416 PyAsyncMethods as_async
	AsNumber     PyNumberMethods   // +440 PyNumberMethods as_number
	AsMapping    PyMappingMethods  // +728 PyMappingMethods as_mapping
	AsSequence   PySequenceMethods // +752 PySequenceMethods as_sequence
	AsBuffer     PyBufferProcs     // +832 PyBufferProcs as_buffer
	HtName       uintptr           // +848 PyObject * ht_name
	HtSlots      uintptr           // +856 PyObject * ht_slots
	HtQualname   uintptr           // +864 PyObject * ht_qualname
	HtCachedKeys uintptr           // +872 struct _dictkeysobject * ht_cached_keys
}

// PyMappingMethods mirrors the C struct PyMappingMethods (size 24; object.h:156).
type PyMappingMethods struct {
	MpLength       uintptr // +0 lenfunc mp_length
	MpSubscript    uintptr // +8 binaryfunc mp_subscript
	MpAssSubscript uintptr // +16 objobjargproc mp_ass_subscript
}

// PyMethodDef mirrors the C struct PyMethodDef (size 32; object.h:233).
type PyMethodDef struct {
	MlName  uintptr // +0 const char * ml_name
	MlMeth  uintptr // +8 PyCFunction ml_meth
	MlFlags int32   // +16 int ml_flags
	MlDoc   uintptr // +24 const char * ml_doc
}

// PyNumberMethods mirrors the C struct PyNumberMethods (size 288; object.h:95).
type PyNumberMethods struct {
	NbAdd                   uintptr // +0 binaryfunc nb_add
	NbSubtract              uintptr // +8 binaryfunc nb_subtract
	NbMultiply              uintptr // +16 binaryfunc nb_multiply
	NbRemainder             uintptr // +24 binaryfunc nb_remainder
	NbDivmod                uintptr // +32 binaryfunc nb_divmod
	NbPower                 uintptr // +40 ternaryfunc nb_power
	NbNegative              uintptr // +48 unaryfunc nb_negative
	NbPositive              uintptr // +56 unaryfunc nb_positive
	NbAbsolute              uintptr // +64 unaryfunc nb_absolute
	NbBool                  uintptr // +72 inquiry nb_bool
	NbInvert                uintptr // +80 unaryfunc nb_invert
	NbLshift                uintptr // +88 binaryfunc nb_lshift
	NbRshift                uintptr // +96 binaryfunc nb_rshift
	NbAnd                   uintptr // +104 binaryfunc nb_and
	NbXor                   uintptr // +112 binaryfunc nb_xor
	NbOr                    uintptr // +120 binaryfunc nb_or
	NbInt                   uintptr // +128 unaryfunc nb_int
	NbReserved              uintptr // +136 void * nb_reserved
	NbFloat                 uintptr // +144 unaryfunc nb_float
	NbInplaceAdd            uintptr // +152 binaryfunc nb_inplace_add
	NbInplaceSubtract       uintptr // +160 binaryfunc nb_inplace_subtract
	NbInplaceMultiply       uintptr // +168 binaryfunc nb_inplace_multiply
	NbInplaceRemainder      uintptr // +176 binaryfunc nb_inplace_remainder
	NbInplacePower          uintptr // +184 ternaryfunc nb_inplace_power
	NbInplaceLshift         uintptr // +192 binaryfunc nb_inplace_lshift
	NbInplaceRshift         uintptr // +200 binaryfunc nb_inplace_rshift
	NbInplaceAnd            uintptr // +208 binaryfunc nb_inplace_and
	NbInplaceXor            uintptr // +216 binaryfunc nb_inplace_xor
	NbInplaceOr             uintptr // +224 binaryfunc nb_inplace_or
	NbFloorDivide           uintptr // +232 binaryfunc nb_floor_divide
	NbTrueDivide            uintptr // +240 binaryfunc nb_true_divide
	NbInplaceFloorDivide    uintptr // +248 binaryfunc nb_inplace_floor_divide
	NbInplaceTrueDivide     uintptr // +256 binaryfunc nb_inplace_true_divide
	NbIndex                 uintptr // +264 unaryfunc nb_index
	NbMatrixMultiply        uintptr // +272 binaryfunc nb_matrix_multiply
	NbInplaceMatrixMultiply uintptr // +280 binaryfunc nb_inplace_matrix_multiply
}

// PySequenceMethods mirrors the C struct PySequenceMethods (size 80; object.h:142).
type PySequenceMethods struct {
	SqLength        uintptr // +0 lenfunc sq_length
	SqConcat        uintptr // +8 binaryfunc sq_concat
	SqRepeat        uintptr // +16 ssizeargfunc sq_repeat
	SqItem          uintptr // +24 ssizeargfunc sq_item
	WasSqSlice      uintptr // +32 void * was_sq_slice
	SqAssItem       uintptr // +40 ssizeobjargproc sq_ass_item
	WasSqAssSlice   uintptr // +48 void * was_sq_ass_slice
	SqContains      uintptr // +56 objobjproc sq_contains
	SqInplaceConcat uintptr // +64 binaryfunc sq_inplace_concat
	SqInplaceRepeat uintptr // +72 ssizeargfunc sq_inplace_repeat
}

// PyBuffer mirrors the C struct bufferinfo (size 80; object.h:40).
type PyBuffer struct {
	Buf        uintptr // +0 void * buf
	Obj        uintptr // +8 PyObject * obj
	Len        int64   // +16 Py_ssize_t len
	Itemsize   int64   // +24 Py_ssize_t itemsize
	Readonly   int32   // +32 int readonly
	Ndim       int32   // +36 int ndim
	Format     uintptr // +40 char * format
	Shape      uintptr // +48 Py_ssize_t * shape
	Strides    uintptr // +56 Py_ssize_t * strides
	Suboffsets uintptr // +64 Py_ssize_t * suboffsets
	Internal   uintptr // +72 void * internal
}

// PyIdentifier mirrors the C struct _Py_Identifier (size 24; object.h:29).
type PyIdentifier struct {
	Next   uintptr // +0 struct _Py_Identifier * next
	String uintptr // +8 const char * string
	Object uintptr // +16 PyObject * object
}
