// Code generated by h2go; DO NOT EDIT.

package py38

// PyModuleDef mirrors the C struct PyModuleDef (size 104; moduleobject.h:35).
type PyModuleDef struct {
	MBase     PyModuleDefBase // +0 PyModuleDef_Base m_base
	MName     uintptr         // +40 const char * m_name
	MDoc      uintptr         // +48 const char * m_doc
	MSize     int64           // +56 Py_ssize_t m_size
	MMethods  uintptr         // +64 PyMethodDef * m_methods
	MSlots    uintptr         // +72 struct PyModuleDef_Slot * m_slots
	MTraverse uintptr         // +80 traverseproc m_traverse
	MClear    uintptr         // +88 inquiry m_clear
	MFree     uintptr         // +96 freefunc m_free
}

// PyModuleDefBase mirrors the C struct PyModuleDef_Base (size 40; moduleobject.h:44).
type PyModuleDefBase struct {
	PyObjectHEAD         // +0
	MInit        uintptr // +16 PyObject *(*)(void) m_init
	MIndex       int64   // +24 Py_ssize_t m_index
	MCopy        uintptr // +32 PyObject * m_copy
}

// PyModuleDefSlot mirrors the C struct PyModuleDef_Slot (size 16; moduleobject.h:58).
type PyModuleDefSlot struct {
	Slot  int32   // +0 int slot
	Value uintptr // +8 void * value
}
