// Code generated by h2go; DO NOT EDIT.

package py33

// PyWeakReference mirrors the C struct _PyWeakReference (size 56; weakrefobject.h:10).
type PyWeakReference struct {
	PyObjectHEAD         // +0
	WrObject     uintptr // +16 PyObject * wr_object
	WrCallback   uintptr // +24 PyObject * wr_callback
	Hash         int64   // +32 Py_hash_t hash
	WrPrev       uintptr // +40 PyWeakReference * wr_prev
	WrNext       uintptr // +48 PyWeakReference * wr_next
}
